### ISSUE TITLE
Hangs when audio device cannot be opened

### ISSUE THREAD

**Issue by simonvanderveldt** [VCVRack/Rack#10]
First of all thanks for this awesome piece of software, really looking forward to messing around with it!

When adding a device that VCV Rack can't open VCV Rack hangs. This happened to me on Linux when selecting ALSA, whilst the audio device was already in use by PulseAudio.

This issue also triggers when starting VCV Rack after the crash since it always opens `autosave.json`, which has the audio device in it and thus causes an instant crash.

**Comment by jackokring** [comment]
I think the only way round this is a multithreading timeout. Why not use pulse audio? Latency? Not an option? In the early 90s, ASIO and stuff was important, but a fast PC with plenty of memory, and a high priority audio mixer, and it's a very small delay.

**Comment by AndrewBelt** [comment]
Yes, timeout of 1sec should be added in Audio Interface. A big refactor will be done in a couple weeks, so I'll do it then.

**Comment by AndrewBelt** [comment]
I support whatever PortAudio supports. I don't remember if it supports Pulse Audio, but if not, it would be easier to contribute to that project rather than add it into Rack.

Or Audio Interface could switch to https://github.com/andrewrk/libsoundio It's probably a lot more ready than it was when I evaluated it over a year ago.

**Comment by modlfo** [comment]
Closing this one because seems obsolete. PortAudio was replaced by RtAudio
