### ISSUE TITLE
Please make the CPU meters even better

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1000]
The new CPU power meters are great. I hope they will help people diagnose their pops and crackles and take action to fix it.

Of course I have a wish list of improvements. It’s too late for 0.6.1, but maybe the next one.

The current meters work really well for plugins that use huge amounts of CPU, and have relatively constant CPU usage. They work less well for lean plugins, and for plugins with blocky/spikey CPU usage.
Many of try to keep our plugins from using more than one percent of the CPU, or ten milli-salami, as it has been called. It is very difficult to get a good reading for a plugin that uses less than 10. Since you have only one digit on the screen, any noise at all in the reading makes the number flicker around, and it’s impossible to read.

Wish #1 – make the time constant longer, so that short readings can be read.

Wish #2 – add a decimal place if the value is small.

Another issue is that blocky plugins, like the ones that do FFT on the audio thread have readings that are deceptively small. These kinds of plugins may potentially cause underflows, while showing light usage on the meters. They also tend to have very unstable readings, as the blockiness manifests as noise to the meters.

Wish #3 – add a “peak” meter. Perhaps it could show biggest value? Or more usefully the total time per audio buffer divided by buffer size? Realize this ask is not easy, and my not be practical.

Thanks again for adding this great feature.

**Comment by modlfo** [comment]
I second the wish number 3. I was thinking that a plugin can take a long time to compute one specific sample, while the other samples are calculated very fast making the mean value low.

**Comment by alfonso73** [comment]
I think that a number showing the sum of all modules consumption would be good.

**Comment by AndrewBelt** [comment]
Congratulations on opening the thousandth issue!

1. shouldn't be solved by making the time constant longer, but the numbers could be "held" for 10 frames or so, although this is non-vital information to be stored in `Module` which I try to keep minimal for ABI reasons.
2. non-realtime operating systems can't reliably measure time durations lower than 0.1us, and decimal points are beyond this accuracy, even when averaged over a long duration, so this would be useless.
3. I can't see why this would be useful. Even a constant-time algorithm gives incredibly noisy time measurements. Replace
```cpp
			// module->cpuTime += (cpuTime - module->cpuTime) * sampleTime / 0.5f;
```
in `engine.cpp` with
```cpp
			if (cpuTime > module->cpuTime)
				module->cpuTime = cpuTime;
			else
				module->cpuTime *= 0.99999f;
```
to see how completely useless this would be.

Playing around with time constants again, it seems that 0.5s is about right, and since that's all I'm willing to change, I'm closing this.

**Comment by AndrewBelt** [comment]
@alfonso73 The sum of all modules is always equal to 1000mS, see https://vcvrack.com/manual/Toolbar.html

**Comment by modlfo** [comment]
Just to confirm. I tried a few approaches as well to improve the CPU meter but they did not provide a result that worths the extra CPU cost of calculating them.

**Comment by squinkylabs** [comment]
I did the same. No surprise - Andrew is correct. Strangely, on my PC various modules meters would suddenly spike up pretty high, then drop back down. Seemingly random. Even modules I know do nothing at all in their step() (like my thread booster that does nothing, and various super light utilities like a+b. maybe my Win Box has some dumb process that takes over the CPU every now and then. don't know.
