### ISSUE TITLE
Auto-build

### ISSUE THREAD

**Issue by Lewiscowles1986** [VCVRack/Rack#1020]
# For feature requests

Have you considered using Travis to build this project? You could display a badge and save your time building commits. It would also help answer user queries about building the project.

Do you have a build script or is it muscle memory at this point to setup the deps?

**Comment by AndrewBelt** [comment]
No automated build system would be capable of building Rack, unless there's one out that actually runs Windows 7-10 with MSYS2, Mac 10.7+, and Ubuntu 16.04, and allows you to install all the dependencies listed at https://github.com/VCVRack/Rack#setting-up-your-development-environment. Let me know if you find one though!

**Comment by Lewiscowles1986** [comment]
I understand your concerns, mine is more about verification for people that are not you.

https://travis-ci.org/Lewiscowles1986/Rack/builds/394444388 from https://github.com/Lewiscowles1986/Rack/commit/afcf605210fa935f0828b2248d9d6a08ae45a2b5 is my latest attempt at CI build where I have linux from gcc5 to 8, clang5 and osx with xcode 9.4. It's not a finished effort, but it's a start.

As you've pointed out msys2 builds are not setup yet although there should be no reason a windows binary cannot compile in linux with the right setup so I'll keep looking into that as well as deployment.

There is also a vagrant file which builds xenial as-per instructions. Maybe it doesn't help, but I think rather than having textual instructions, it might be easier to have tested verified build scripts between commits.

**Comment by AndrewBelt** [comment]
>there should be no reason a windows binary cannot compile in linux

Yes there is. Rack depends on jansson, libspeexdsp, libcurl, libzip, rtmidi, and openssl, all of which use configure for their build system which, as you might know, needs to run binaries it builds in order to check whether it can build. This is dumb, but this is how they decided the system should work in the 1980's. So you'll need a kosher Windows installation to build Rack on Windows.

**Comment by pronvit** [comment]
Obviously, `configure` and cmake both support cross-compilation during which they don't run binaries, as you might know.

**Comment by AndrewBelt** [comment]
PRs are certainly welcome, but good luck working out the problems.

However, that gives me an idea. Can you trick configure into cross compiling for your own architecture to make ./configure stop its build/test/build/test cycle? That would surely speed up build time.

**Comment by Lewiscowles1986** [comment]
@pronvit check out work done, I'd love to get something going. So far deployment should be simple enough once we can get build for windows it's just another make command (which I'm very happy for @AndrewBelt for)

I'm also interested in pre-building images and bringing the fork https://github.com/mi-rack/Rack back into line with the main build so it's not a total divergence.

I Can submit Linux & Mac CI as a PR now, it's linked above

**Comment by pronvit** [comment]
@Lewiscowles1986 Sorry I'm not a big fan of automatic builds myself. I just pointed out it's certainly possible, although it didn't work straight away - openssl needed different flags (not the usual `configure --host`), then all the deps built except for libzip which seemed to try using system zlib instead of the built one, and then I gave up because I'm not really interested.

As for the tricking, there's caching https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Cache-Files.html

**Comment by Lewiscowles1986** [comment]
@pronvit any links or references would be greatly appreciated.

**Comment by TronicLabs** [comment]
For windows Appveyor works perfectly.

**Comment by AndrewBelt** [comment]
I'm going to close this, since it's useless for VCV, but you may still continue the conversation if you're wanting to automate the build yourselves for some reason.

**Comment by Lewiscowles1986** [comment]
Just an update. Everything apart from bridge now builds for windows, mac and Linux using Github actions.

The main problem for bridge is automating the various closed source parts to download, unpack ready for compilation.

Once I've finished it for 0.6 I'll try going up releases and see what bites.
