### ISSUE TITLE
Add Patch Info

### ISSUE THREAD

**Issue by dschiller** [VCVRack/Rack#1026]
Add a Patch Info Button with following Informations:

- Cable Amount
   . Amount of different Colors
   . Amount of all Cables
- Module Amount
   . Amount of different Modules
   . Amount of all Modules

Why: It's a good way to plan Hardware

**Comment by AndrewBelt** [comment]
I can somewhat imagine that the total number of modules could be useful, but I can't see a reason for any other information. Since Rack modules often don't correspond to hardware modules, it's a stretch to say that even the number of modules is useful information.
Seems like unnecessary bloat, won't add.
