### ISSUE TITLE
Plugin usage stats

### ISSUE THREAD

**Issue by lckypckt** [VCVRack/Rack#1028]
Hey,

Would it be possible to list the plugins by popularity, or perhaps get a list of the top (say) 20 most used plugins?

I've been making my own MIDI controllers for various other uses, and would like to create something for the VCV community. Ideally, the layout would be based on the most popular plugins, but can also be customized per person (modular even if I figure out a way to get that working!).

Thanks!

**Comment by AndrewBelt** [comment]
This was proposed in https://github.com/VCVRack/community/issues/226, and I added rankings for a day, but I quickly realized it was a bad idea, both because the algorithm artificially affects users' view of certain plugins (judgements should be done completely objectively), and the legality is unclear based on my current [privacy policy](https://vcvrack.com/privacy.html).
