### ISSUE TITLE
Restoration of tag list in browser author view

### ISSUE THREAD

**Issue by lnikj** [VCVRack/Rack#1032]
In the author view in the 0.6.0 browser it was useful to see the tags for a module.

In 0.6.1 the module package and version number is listed instead, a long repeating list.

Arguably, a list of the module tags would be more informative and useful.

A module tag 'commercial' or 'paid' could be added to flag up to the user that they have paid for that module.

If module name plus tag list exceeds the available space then it could be truncated and ellipsis inserted, or it could go on to the next line.

If the former then perhaps it might encourage parsimony amongst devs.

**Comment by lnikj** [comment]
An alternative to a 'paid' module tag would be to make module names belonging to different packages subtly different shades of grey.

**Comment by n6smith** [comment]
I have to say, I prefer the 'new' look.. Much cleaner and for me, much easier and faster to use and scroll through... especially when you have a lot of plugins installed.. The search capability adds the tag component if needed...  Just my 5c worth....

**Comment by rubyglow** [comment]
I agree that the condensed space of the browser is better in 0.6.1. I also agree with Inikj that, especially given a condensed view, a long list of identical text is kind of pointless, and could be better used, and would be much more informative, by showing the tags to the right of the module name, rather than a repetition of the author and version.

**Comment by AndrewBelt** [comment]
This issue is obsolete since the Module Browser was overhauled in Rack v1.
