### ISSUE TITLE
BridgeVST.cpp - Compiling between VSTi and VSTfx

### ISSUE THREAD

**Issue by Uriel-A** [VCVRack/Rack#1035]
Operating system(s):
Windows (10)

Rack version:
Compiling from source (commit 9abc6743902b587f359fb4d232c0ba4cadab48d5, branch v0.6)

Problem:
```make dist FX=1``` still compiles the bridge as an VSTi instrument instead of a VST FX.

https://github.com/VCVRack/Bridge/blob/v0.6/VST/BridgeVST.cpp#L19
```C++
#if FX
		isSynth(false);
#else
		isSynth(true);
#endif
```
isSynth(); should not be called when compiling a VST FX.
isSynth() doesn't take any argument either when compiling a VSTi instrument, so it should be something like this instead:
```C++
#if FX
		return;
#else
		isSynth();
#endif
```

**Comment by AndrewBelt** [comment]
Please state the *problem*, not your guess at a *solution*. http://xyproblem.info/ What result do you expect? What result is actually happening?

**Comment by Uriel-A** [comment]
Not guess. Just don't know of a more elegant way to code it. I'm not a coder and my C++ is extremely rusty.

**Comment by AndrewBelt** [comment]
Closing as this is not a real problem.

**Comment by Uriel-A** [comment]
Well, you're the one who asked me to post this bug report... #1017

**Comment by AndrewBelt** [comment]
That was because I expected that you compiled it, tried it out, and it didn't work for you.

**Comment by Uriel-A** [comment]
I compiled it and it worked.

**Comment by AndrewBelt** [comment]
You *just* said that my commit "will not work". I'd appreciate it if you didn't outright lie on the issue tracker, causing me unnecessary effort and frustration. Locking threads.

**Comment by AndrewBelt** [comment]
In fact, hovering my mouse over your profile picture reveals

>Honestly not a fan of open source projects. Often it's really just programmers going on an ego trip at the end of the day.

This hurts me, because I know so many open-source developers and myself who dedicate the majority of their social lives and free time to developing free software for the purpose of benefiting those who can't afford things like modular synthesizers, web servers, databases, etc. This puts a brick in my stomach that will be in my mind all day. For the community's sake, I ask that you uninstall Rack, remove yourself from the Facebook, and move onto something else. This type of for-granted attitude is so damaging to projects like these, we simply can't have you around. If I start offering commercial plugins that don't deliver to people's expectations, feel free to criticize all you like.
