### ISSUE TITLE
Parametra output level vs Console output level

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1057]
Rack version 0.6.1 (dev) with latest version of Parametra plugin. Platform: Windows 10

Feeding a VCO into Parametra the output shows clipping in default settings. Feeding Parametra into the Console the output shows -6 dB. Increasing the Parametra output level, the waveform becomes more and more distorted, but the output level on the Console does not change.

I would have expected the output level on the Parametra and Console show the same level, but maybe there is a reason for this?

![parametra_output](https://user-images.githubusercontent.com/624427/42470286-3bc2a23e-8377-11e8-9e4d-452830ede8d9.png)

**Comment by AndrewBelt** [comment]
Your signal into Parametra is just *barely* clipping, since it clips at 5V and VCO generates slightly greater than 5V signals due to bandlimiting.

Console attenuates due to its -3dB pan law, and then attenuates by an additional -3dB to "artistically" set output level to more sane levels.

Now it makes sense to not apply an additional -3dB artistic gain but 3dB gain to account for the center position of the pan. Now, Console is a unity mixer with all parameters set to their default values. Also note that the red LED on Console is labeled -3dB, not CLIP. This is because Parametra clips at 5V, while Console clips at 10V. This is because some users want to apply gain to their audio signal to reach the full range +/-1.0 of their sound card.

**Comment by AndrewBelt** [comment]
I have released an update that turns Console into a unity gain mixer at default parameter positions.

**Comment by cschol** [comment]
Thanks for the explanation. 

For clarification: It looks like Console also clips at 5V now in the new version. Was that intended? 

It means at default settings, putting just a VCO into it, one has to always adjust the Master down to about 10:00 to not get clipping (at least "indicated" clipping). Audible clipping (and visible on Scope) occurs going beyond 12:00.
