### ISSUE TITLE
MIDI computer keyboard

### ISSUE THREAD

**Issue by stephen147** [VCVRack/Rack#109]
Hi, could there be support for pc keyboard for when I on the move and just want to use my keyboard as midi in?

**Comment by synthi** [comment]
You could use something like this: 
http://vmpk.sourceforge.net/

**Comment by AndrewBelt** [comment]
This should be completed with #375

**Comment by bontric** [comment]
@AndrewBelt I just read your comment on #470 and was thinking: Should the "Midi computer Keyboard" really be a feature _blocking_ the use of certain keys for other features. (This might be a more sensible topic to me then to others but I love having handy key commands).

Instead of this I'd suggest to implement the Midi Keyboard as separate module and only use the keys to play midi notes while it is focused with the mouse or while it is turned on (You could simply add a button on the module to turn the keyboard On/Off). This would allow us to use the Keys for other things, while not compromising on the Midi Keyboard.

**Comment by AndrewBelt** [comment]
I actually considered making the computer midi keyboard only active when the mouse was hovering it, as you said, but I backed off of that idea a bit and decided to make it a global state (where the keys are picked up either by RackScene, the root of the scene graph, or through glfwGetKey()), but making it only work in certain state of Rack's UI decreases my trust that the key would make sound when playing. It's really not a huge deal to break this trust, but keep in mind that there are still a ton of keys available through the use of modifiers. So I think we should use those first until we run out. I like vim and its single-key commands, but I think others would prefer a command to use the Cmd or Ctrl keys. So perhaps the answer to choosing cable colors is to simply use Ctrl+0 through Ctrl+5 or whatever. But it'll be a feature that's added in the distant future.

**Comment by AndrewBelt** [comment]
This issue depends on #375

**Comment by teolaz** [comment]
As requested on #498 , could be pleasant to have the UI keyboard present with cv/gate linkable to any parameter you want...

**Comment by MikkoAM74** [comment]
Couldn't this keyboard be implemented like Bitwig does it.

When caps lock is "on", asdfghjkl etc.. keys are midi keyboard , z and x change octaves
and if caps lock is "off" all keyboard commands work as expected.

**Comment by AndrewBelt** [comment]
@MikkoAM74 I like the caps lock idea.

**Comment by AndrewBelt** [comment]
With the new MIDI restructure, this will be easy to add. It will be enabled only when Caps Lock is enabled and will work globally (all key input at any moment will be sent to all MIDI interfaces) except when a text box is focused.

**Comment by AndrewBelt** [comment]
Last cleanup finished with d2a308f56b461833fff9a79b24ac5c94eed15db1, closing
