### ISSUE TITLE
Computer crash

### ISSUE THREAD

**Issue by MUSICOELECTRO** [VCVRack/Rack#1137]
Hi
Is repetitive:
If the chrome navigator is open,  the Computer is totally blocked and is needed a hard reset of the machine.

Any suggestion? 

Thanks

See https://github.com/VCVRack/Rack/issues/1021 for issue report standards and https://github.com/VCVRack/Rack/issues/730 before posting any code or terminal output.

# For bug reports

Operating system(s):
Version of Rack if using official binary, or commit hash and branch if compiling from source:
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

# For feature requests

# For discussions

**Comment by modlfo** [comment]
I'm closing this one since there's not information about the operating system or any hardware that the computer has. As a recommendation, check that you have updated the graphic drivers of your computer since outdated or missing drivers could show this issue.

If you are still having the same problem with a recent version fo Rack, and after updating your drivers, feel free to comment and provide more information.
