### ISSUE TITLE
onMouseUp event doesn't fire after dragging a knob

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#1242]
It seems it doesn't work on a knob, after a drag (which probably move the mouse over the knob area).

**Comment by Coirt** [comment]
I came across a similar bug when coding with C#, some computer keyboards and mice will not trigger that event. Have you got a different mouse to test if it is the mouse, also does mouse down work? 

iirc, I had to use `onMouseDown && onMouseUp` when I came across it.

**Comment by Nowhk** [comment]
mouseDown work, as well mouseUp, but "only" if I'm with the cursor over the knob area. If I do mouseDown (triggered), drag (so mouse go out of the knob scope) and than mouseUp, this last won't trigger.

Tried with two mouses, its the same. Win 10 Pro 64 bit

**Comment by TronicLabs** [comment]
@Nowhk 
for now the default behavior of onMouseUp in the source [code](https://github.com/VCVRack/Rack/blob/7b7f24923480bf309c0fca6ba4b3586ac360d08e/src/widgets/Widget.cpp#L126) is as you have described,
it executes the check if the mouse position is inside the bounds box of the widget, otherwise it does not execute the event, but I think it should always return the event, but if it exceeds the bounds box widget it must return the maximum value of the boundaries of the box as current position.

**Comment by AndrewBelt** [comment]
Closing as obsolete, since `onMouseUp()` has been replaced with `onButton()`.
