### ISSUE TITLE
Smoothing user migration to Rack v1

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#1321]
My goal is to drive as many people off of Rack v0.6 as possible. But if the default Rack user dir is set to the same location as what Rack v0.6 uses, word will get around that it messes up Rack v0.6 installations, which will dissuade people from upgrading.

A possible solution is to install Rack to `Program Files/Rack-v1` with a `Rack v1` start menu shortcut on Windows.
Mac users can manually rename the app bundle to `Rack v1` if they wish.
Finally, and most importantly, I could change the Rack user dir to `whatever/Rack-v1` on all OS's.

That's the best I can think of.
Later this year when Rack v2 releases, people might be frustrated that they have several versions of Rack on their computer.
To solve this, I could overwrite the Rack installation as usual on Windows (unless users manually change the install location in the install wizard) but still use `Rack-v1` as the user dir.

I welcome any alternative solutions, such as intelligent detection of Rack v0.6 user dirs.

**Comment by baconpaul** [comment]
Rather than change rack user to whatever/Rack-v1 you could also make it so you had

```
whatever/Rack/plugins-v1
whatever/Rack/log-v1.txt
whatever/Rack/settings-v1.json
```

etc...

which would allow one Rack directory to safely span multiple versions. (Patches are already versioned so I don't think you need to split the patches directory). Also means a future v2 and v3 and so on could intersperse and users don't have to do or really even think about anything. You could add a code point and a make variable to know the suffix even, so people could code and script to it if they needed.

Cost seems low; it would break some scripts, those of us using rack 1 now would see our plugins "disappear" when you did this; etc... but may be another route.

Only real cost is "those 0.6.2 plugins never get cleaned up". But you kinda want that for users who keep the old rack around.

**Comment by lnikj** [comment]
> To solve this, I could overwrite the Rack installation as usual on Windows (unless users manually change the install location in the install wizard) but still use Rack-v1 as the user dir.

That will be confusing when people are on v2, v3 etc.  Why not abandon 'rack' altogether and go to 'vcvrack' with no version number?

**Comment by AndrewBelt** [comment]
@baconpaul That might work. `plugins-v1`, `settings-v1.json`, `autosave-v1.vcv` are all that's needed I think.

**Comment by AndrewBelt** [comment]
Solved in ca89558bb4af86e197a38d056aa0aa7160cb938d

**Comment by baconpaul** [comment]
That's super cool. It would be useful for a couple of my custom makefile rules to know ABI_VERSION in make and shell also. Any chance of adding it as a make- time symbol also? (If not I can always just code it to 1 in my dumb little scripts and stuff).

**Comment by AndrewBelt** [comment]
No I don't want to support conditional ABI builds.

**Comment by baconpaul** [comment]
OK thanks for considering it! And you are right - while I didn't want conditional builds you could use it for that, and those are nasty.

**Comment by squinkylabs** [comment]
I've been  doing conditional builds for the last few months so that I don't have to "commit" my code base to any specific release date of V1.0. But as soon as 1.0 "ships" I'm going to start removing that and/or letting it rot.

```c++
# compile for V1 vs 0.6
FLAGS += -D __V1x
```
