### ISSUE TITLE
Host crashes whenever trying to load VST

### ISSUE THREAD

**Issue by sinan166** [VCVRack/Rack#1356]
[log.txt](https://github.com/VCVRack/Rack/files/3305851/log.txt)

Operating system: windows 10
Rack version: v1.0 dev
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Nvidia geforce GTX860M

### Rack crashes whenever I try to load a VST on Host. Even the drop down menu doesn't show up. 
...

**Comment by vprknt** [comment]
Same issue. Rack hangs when attempting to open drop down menu in Host.

Operating system: Windows 10
Rack version: v1.0.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Intel HD Graphics 5500, Focusrite ASIO Driver for Scarlett Solo

**Comment by AndrewBelt** [comment]
In case anyone knows how to use GDB with MSYS2, could someone post a backtrace?

**Comment by lnikj** [comment]
Several users have reported this each stating that the problem occurs when clicking the 'Add VST' space. Occurs in 10.14.5 as well as Win 10 here.

**Comment by AndrewBelt** [comment]
@lnikj Is it before or after the dialog box appears?

**Comment by lnikj** [comment]
Before.

**Comment by AndrewBelt** [comment]
@lnikj Do you mean when clicking the "Add directory..." menu item?

**Comment by brickzone** [comment]
Same for me! Just when choosing a plugin it hangs a whole Rack, Windows 10, rack v1.0

**Comment by Coirt** [comment]
Same here windows 7 rack dev_f8813bff tried to BT but there is no error and no back trace available with gdb. It happens when right or left clicking the open plugin space. Right clicking the mapping spots opens that menu fine.

In dev version both Host and Host FX will hang rack but eventually will respond and the dropdown appears where you can add VST's. The only thing I can think of that might make rack crash is having VST 3 plugs in you steinberg/plugins folder.

I have a large collection of VST in that folder, some are 32bit vst2 some are 64bit and some are vst3. Is there a way to relocate the plugin folder for host? Will be able to test what is causing it to hang, I came across some common offenders with another DAW that might be to blame.

**Comment by AndrewBelt** [comment]
>It happens when right or left clicking the open plugin space.

Ohh, so it's not the "Add directory..." menu item but the `(no plugin)` button.

**Comment by stoermelder** [comment]
It is the `(no plugin)` button. A huge number of files or folders inside the vst folders slows it down. I've removed some folders incrementally and time between click and context menu showing got shorter with less items.

**Comment by Coirt** [comment]
Aye most probably a VST 3 problem. Just removed the offending folder with mixed VST versions and it responds on click. If there is no way to change folder locations outside rack via a settings file I'd recommend y'all temporarily rename your VST folders e.g. `_foldername_1` then add a custom location and add compatible plugins.

**Comment by stoermelder** [comment]
I don't have any VST3 in my folder and still Rack gets unresponsive for about 20 seconds when clicking on `(no plugin)`. But it's just a small collection of 10-20 VST.

**Comment by BoscoRemus** [comment]
I can open v0.6.2 Host and HostFX with No problem but in v.1 spinning beachball.. on OS 10.14.5 have both on system...

**Comment by BoscoRemus** [comment]
With nothing but Host in the Rack, it still crashes Rack..

**Comment by Coirt** [comment]
@stoermelder I'd remove one by one and see which is an offender. Iv'e added a good few (>40) and it responds on click

**Comment by stoermelder** [comment]
I have 1870 files in that folder, but just 10-20 dll. Everything else are auxillary files for these plugins.

**Comment by Coirt** [comment]
LOL

**Comment by Coirt** [comment]
32 bit plugs seem to cause a hang especially ones from Flux::

**Comment by Coirt** [comment]
For another issue, and thinking out loud.... I'm unsure if it hangs because of trying to scan the folder each time it is opened. I'm definitely seeing an increase in the time it takes to display the menu with more plugs being added. Wondering would having host show the folder hierarchy help with the time it takes to load, with drop down menu's to show each folder from the plugins folder on disc (also could help with workflow in rack). It seems to filter by extension anything named `.dll` is displayed in the menu.

**Comment by lnikj** [comment]
Confirm that it appears to be the scanning process. I thought Host was hanging Rack on clicking No plugin.

I have a lot of Vsts. Took Host over 10 minutes to scan them. This is a change to previous behaviour ?

**Comment by BoscoRemus** [comment]
My Eventide's seem to hang during scanning but they do load.

**Comment by BoscoRemus** [comment]
Rack takes forever to load if you have a Host with plugins loaded it seems to want to scan before loading... Close and reload patch takes forever to load scanning plugs everytime...

**Comment by delaudio** [comment]
Same for me. I'm on OSX 10.13.6 with a MacBook Pro (Retina, 15-inch, Mid 2014)

**Comment by delaudio** [comment]
After last update, I'm not experiencing this issue anymore. Thank you.

**Comment by AndrewBelt** [comment]
Thanks, closing.
