### ISSUE TITLE
Mac Core audio input not working

### ISSUE THREAD

**Issue by marcusbrutulus** [VCVRack/Rack#1373]
<--
To file a bug report, fill out the form below.
Use a descriptive title that best explains the bug in one sentence.
Attach screenshots if the bug is visual.
Attach your `<Rack user folder>/log.txt` file if something is crashing or not loading.
Surround terminal output with three tildes
```
like this.
```
-->

### Details

Operating system: MacOS 12.14.5
Rack version: v1.0.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Core audio
### Expected behavior
I can use two instances of core audio to use the built in microphones for one and the audio output for the other.
### Actual behavior
Not getting any microphone signal passing through. Screen shot attached
<img width="1680" alt="Screen Shot 2019-06-20 at 4 06 31 PM" src="https://user-images.githubusercontent.com/52051504/59878863-5f410a00-9377-11e9-9ad1-edfc973d8dbc.png">

**Comment by Torinbob** [comment]
Why are you using 2 audio modules here? A single audio module handles both ins and outs. 2 audio modules are not supported.

You seem to be using the same device in both modules so you could just hook the bottom 2 outputs in the first module to the top 2 inputs on the same module.

There could be another issue here which is that Rack needs to have permission to use the Microphone (in this scenario, Microphone means ALL audio inputs) otherwise you will get no audio input at all.

Go to System preferences > Security and Privacy.  Select the Privacy tab. In the left Column, select Microphone. Then in the right column, if rack is not checked, check it. If it is checked, uncheck it then check it again. Now quit rack and launch it again.

**Comment by rubyglow** [comment]
Probably related to this Apple screwup, which I ran into also. The fix is easy, create an aggregated audio device, problem solved: https://support.focusrite.com/hc/en-gb/articles/115000166845-Second-Generation-Scarlett-Solo-2i2-and-2i4-on-macOS-Sierra-10-12-2-or-higher-showing-as-separate-input-and-output-device-

**Comment by AndrewBelt** [comment]
Fixed in 8341623cf2f49983e0d63a69041e180e25a222f3

**Comment by marcusbrutulus** [comment]
So @AndrewBelt what do I do with the code from that link? Do I need to recompile this myself? Do I download the software again? Not sure where to go from here.
