### ISSUE TITLE
selecting Real-time priority crashes Rack

### ISSUE THREAD

**Issue by tank-trax** [VCVRack/Rack#1389]
### Details

Operating system: Debian Stretch 4.9.0-9-rt-amd64 SMP PREEMPT RT Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux 
Rack version: v1.0.0.0

### Summary

when selecting `Engine -> Threads -> Real-time priority`

Rack crashes

### Steps to reproduce

when running from the terminal 

```
$ ./Rack
Rack: src/system.cpp:132: void rack::system::setThreadRealTime(bool): Assertion `!err' failed.
Aborted
```

**Comment by neoh4x0r** [comment]
@tank-trax 
That's because by default rack doesn't have the necessary permissions to set real-time priority.

Only the root user has the ability to enable RT-priority.

To do this as a regular user you must run the following command:

**`sudo setcap cap_sys_nice=ep "/path/to/rack binary"`**

Any time the rack binary is updated, that command would have to be executed again.

PS: I had the same problem on v0.6 branch (the "thread-boost" module would indicate an error when ever RT-priority was chosen, and that command solved it)

**Comment by squinkylabs** [comment]
Nik added a note about that to his unofficial guide. Although we've discontinued "Thread Booster" (since it's unnecessary now), the manual is still worthwhile, and documents that stuff: https://github.com/squinkylabs/SquinkyVCV/blob/master/docs/thread-booster.md

**Comment by neoh4x0r** [comment]
@squinkylabs 
Even with "Thread booster" being discontinued ... that command is still necessary to prevent the OP's crash (since thread-booster's functionality is now built-in). 

That information should probably be added to the VCV Rack manual.

**Comment by squinkylabs** [comment]
@neoh4x0r oh, for sure. It's just that I'm too lazy to contribute to the VCV manual, but I do write ok manuals for my own plugins. I'm pretty sure Andrew accepts pull requests for the manual, should anyone care to do this.

**Comment by tank-trax** [comment]
thanks for the explanation, much appreciated 

and to confirm, executing that command permitted the selection of the real-time priority
