### ISSUE TITLE
Recovery behaviour when patch contains modules unavailable in User's Library

### ISSUE THREAD

**Issue by edwardenixon** [VCVRack/Rack#1391]
I think it would be an excellent feature if, when opening a patch, for example a download from someone's Patreon account, that the Library would take note of any modules absent from the user's collection and then provide that user with an opportunity to review, download, update or even purchase missing components.

Perhaps this review process could be completed prior to Rack's updating, closing and re-opening with the downloaded patch in working order.

All sorts of gottchas and exceptions and complications I should imagine. But a worthy and, to me, very classy feature for an already very classy piece of work.

**Comment by FunkybotsEvilTwin** [comment]
I'd also like to add to this... We should also be able to try to force a replacement for a module VCV can't find. Won't make sense in all instances but where it does is the example of a patch that used VultModulesFree, but I have the commercial VultModules. there should be a way to replace one with the other, assuming they're patch compatible like in that instance. I don't want to have duplicate modules installed from free and commercial packages just because one day I may hit a preset that looks for the free version.

**Comment by AndrewBelt** [comment]
Currently if Rack loads a patch with a plugin or module that is not available, it reports it in a dialog box. I believe that is enough for users to find the appropriate plugins/modules they need from the VCV Library.
