### ISSUE TITLE
Make the CPU meter bar for the Audio module green

### ISSUE THREAD

**Issue by RichieHindle** [VCVRack/Rack#1458]
Some new users mistake the big red bar on the Audio module as a measure of scary CPU usage, and interpret a tall bar as a bad thing.  The fact that it has opposite meanings for Audio vs. everything else is not clear.

If Audio's bar were green rather than red, it would:
- be less scary
- be visibly different from the other modules
- carry a positive rather than negative vibe.

**Comment by AndrewBelt** [comment]
I feel there could be a better UI for this than changing the meter green. Also, the only ABI-stable implementation I can think of is for Rack to manually check the model slug for the two VCV Audio plugins. What if a third-party module "wants" to be green too?

**Comment by RichieHindle** [comment]
Ah, I'd assumed that the Rack engine knew that the Audio module was special, and that its CPU usage was measured differently.  My mistake.

A new tag would be an ABI-stable way to indicate that a module was an Audio-style "time source" rather than "time sink" (I'm struggling come up with good terminology here!)

As for the UI, a VU-meter-style representation of overall CPU usage, going from green to yellow to red, would work, and would fit well into the Rack visual language.  But I'm not sure where you'd put it.  Horizontally in the MenuBar?  On a module in its own right?  Seems like overkill.

**Comment by freddyz** [comment]
I suggest that the usage bar and the CPU percentage reading be completely removed from the Audio module.  In its current form (displaying remaining CPU) it is indicating the opposite of what every other module displays.  This is understandably confusing for a new user, and I don't think changing the color would help.  If my proposal were implemented, the user could still easily see which modules are using the most CPU.

I realize that the current implementation makes sense technically, but I think that there will be a never-ending stream of "why is the Audio module using all my CPU!?!?" questions if it stays as-is.

**Comment by AndrewBelt** [comment]
@freddyz I tried that a year ago and got lots of whining and crying.

However, I've renamed "CPU meter" to "Module timer". Perhaps that clears up some confusion. Sometimes it's useful to see how much time VCV Audio-* is spending in its `::process()` function.

**Comment by freddyz** [comment]
@AndrewBelt Can't win huh... 

I really feel that no amount of labeling or color will prevent the confusion for a new user.  Some ideas: 

1a) Audio-* modules show their CPU meter in green, and a red bar fills up the remaining vertical space which effectively shows how much CPU is used by other modules.  This will not prevent "Audio module is using all my CPU even with NO MODULES!!!"

1b) Audio-* modules display their CPU time/percentage as:
`31% (69% remaining)`
`3.1μs (6.9μs remaining`)

2). A new property of Module: `hideCPUMeter` which is `"true"` for Audio-* modules and defaults to `false` otherwise.  I don't think this is very nice, but at least it would give the whiners & criers a solution.  Also, I don't think anybody wants random modules to be forever hiding their CPU meters so I suppose this would require a new option in every module's right-click menu.

I still vote for full removal but then again I'm not the one putting up with the complaints.  Best of luck - Rack has been, currently is, and continues to get more awesome and I think you're doing great!

**Comment by AndrewBelt** [comment]
Your (2) breaks ABI.

**Comment by RichieHindle** [comment]
A new tag would solve the ABI problem, but it's a hack.  Tags are supposed to help the user find modules, and this wouldn't be much use for that.

**Comment by freddyz** [comment]
@RichieHindle I think this actually would help the user find the right module.  If any "audio output"-type module behaved in the same way as Core Audio-* (ie consuming all remaining time until the next sample) then it **should always** show this alternative UI and thus **should** have the new tag.  It's definitely a hack of the tag feature but it makes sense.

**Comment by AndrewBelt** [comment]
Another problem I have with the dual-mode proposal is that green (or anything opposite of red) means "good", but these are just time measurements here, not good or evil measurements. It's not necessarily a good thing that an audio module is blocking for 95% * sampleTime. The meter doesn't distinguish between thread sleep time and thread run-time, so if I replaced the sample rate converter with a really slow one, you wouldn't see a change with the CPU meter. If you have two VCV Audio modules, this 95% will be arbitrarily divided between the two.

**Comment by AndrewBelt** [comment]
Scratch that idea. Writing a proper profiler involves thread interrupts, which I don't think is possible for a user-level application.

Instead, the solution is to measure thread ticks (using platform-dependent functions) rather than time of day (with `std::chrono`).

**Comment by AndrewBelt** [comment]
Fixed in 8a299b5
