### ISSUE TITLE
Possible out-of-bounds in Port.hpp?

### ISSUE THREAD

**Issue by ndrspcfd** [VCVRack/Rack#1524]
In Port.hpp (at 276c70a4abe609fc6109139f9ab892672314fbc5 ), we do:

````
              // Set higher channel voltages to 0
               for (int c = channels; c < this->channels; c++) {
                       voltages[c] = 0.f;
              }
````

With gcc 7, this bit of code was throwing `warning: array subscript is above array bounds `  for the assignment.

Upgrading to gcc-9 stopped the warning, but looking at the code, if channels happens to be equal to PORT_MAX_CHANNELS, the `for( int c = channels ...)` looks wrong.

So, maybe the following is preferable. OTOH, it is early in the morning and the original may be fine, so please feel free to ignore :)

````
diff --git a/include/engine/Port.hpp b/include/engine/Port.hpp
index 012a3ec..fb3e26b 100644
--- a/include/engine/Port.hpp
+++ b/include/engine/Port.hpp
@@ -133,9 +133,15 @@ struct alignas(32) Port {
                if (this->channels == 0) {
                        return;
                }
+               // Enforce channel limit
+               if (channels > PORT_MAX_CHANNELS) {
+                       channels = PORT_MAX_CHANNELS;
+               }
                // Set higher channel voltages to 0
-               for (int c = channels; c < this->channels; c++) {
-                       voltages[c] = 0.f;
+               if (channels < this->channels) {
+                       for (int c = channels; c < this->channels; c++) {
+                               voltages[c] = 0.f;
+                       }
                }
                // Don't allow caller to set port as disconnected
                if (channels == 0) {
````

**Comment by AndrewBelt** [comment]
I'm pretty sure that warning is a compiler bug.

If `channels` in that line is equal to `PORT_MAX_CHANNELS`, the loop's block will not execute, because `this->channels` is at most `PORT_MAX_CHANNELS`. That loop simply sets voltages to 0V in the range `channels` to `this->channels - 1`. If the range is empty, nothing happens.

I don't want bounds checking because this function is a hotspot.

Your line `if (channels < this->channels)` is unnecessary and would be optimized out anyway.
