### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#153]
Would need to implement a "transaction" system which supports
- moving knobs
- deleting, adding, cloning, initializing, randomizing modules
- creating, deleting cables

and their inverses.

Momentary buttons are weird because activating their function requires an on/off sequence which you can't really undo, so it won't be included in the first pass.

**Comment by olilarkin** [comment]
definitely need this

**Comment by msintros** [comment]
Absolutely need undo, at the very least for creation and deletion of modules / cables.  States of knobs and things like that are less important, but it's currently all too easy to accidentally delete the wrong module and have a hard time remembering how to recreate it with all of its connections.

**Comment by LKHSogpit** [comment]
Just remember holding backspace and moving the mouse can be the cause of those accidental deletes. Did that a few times before I realised backspace and mouse move is one action when you are not holding backspace will it only stop deleting.

**Comment by msintros** [comment]
So far that hasn't really been the problem for me, but thanks for the heads up - I will make sure I don't do that ;)  

I think for me the main problem is that there isn't really an indication of which module you have selected.  Sometimes I will think I have last clicked on a certain module, hit delete, and realize that I must have touched another one since then because that one disappears, and given the complexity of some set-ups it can be difficult to figure out exactly how to set it back to the way it was.  I could deal with having to figure out knob position, etc. but resurrecting patch cable connections with "undo" would be a big help.

**Comment by LKHSogpit** [comment]
The active module is the one under the mouse. Right click on a module to see the shortcuts any module you are hovering over will apply those shortcuts. If you want to delete a whole lot of modules you just hold backspace and move the mouse over those modules.

Obviously it has been a problem if you don't understand how it works Iv'e suggested the same undo feature also but more out of frustration of the mistake. Since I figured that out myself, holding backspace and moving the mouse will delete other modules, I have not made the same mistake. Just make sure to release backspace when you move the mouse if you have other devices surrounding.

An undo would still be handy.

**Comment by LKHSogpit** [comment]
You can't do it with a IRL hardware module so that is probably the thinking behind it. The lack of undo is not a deal breaker at all. After a while of using rack I find no undo better because it forces you to really think about changes. Guaranteed you will learn faster through making informed decisions and making those mistakes of changing a value.

**Comment by msintros** [comment]
I'm not sure the undo was deliberately left out, if that's what you're suggesting.  It's fairly clear from the original reply that the undo simply hasn't been implemented yet because there are so many things that it would have to have a record of in order to resurrect whatever you're undoing.  

I also don't really think that the absence of a feature is a benefit, regardless of how much it might "force you to really think about changes."  This is like not having a safety on a gun forces you to think about if you want to shoot someone or not.  That's an extreme analogy, but I think you get my point.  

Thanks for pointing out the way things get deleted though, I definitely didn't realize that.

**Comment by LKHSogpit** [comment]
Not suggesting that at all, simply saying one could argue that. The safety on the gun is so you don't shot yourself is it not!

**Comment by msintros** [comment]
Which would make it an even better analogy here ;)

**Comment by danballance** [comment]
Surely the point of Rack is that it's a software modular, with those advantages and disadvantages? Disadvantage - no real analogue filers or wave folding. Advantages - I can save my patches and reload later. Or should we maybe get rid of patch saving, to be closer to a hardware modular? ;-)

**Comment by AndrewBelt** [comment]
Please avoid posts equivalent to "+1" or "we need this" on the issue tracker. Instead use the thumbs-up on the first post. https://github.com/VCVRack/Rack#the-issue-tracker-is-the-official-developers-forum

**Comment by GeoSpark** [comment]
To get around the momentary switch problem, the undo stack needs to record states rather than events. If you had a momentary switch on a module that cycles between 8 things, you don't need to know how many times the switch was pressed, just which thing was selected before and after.

One way would be for modules (and core systems) to receive an event every time a change is made, and they package up whatever state variables they want (maybe a simple blob, or a more flexible KV structure) and send it to the the undo stack system. When undo or redo are activated by the user, each module gets sent its recorded state, and is responsible for getting itself ready for the next tick.

Enforcing idempotency and zero side-effects would be desirable, to ensure valid state is maintained across the system. Although this would have to be done by the developer. Of course, if VCRack was rewritten in Haskell, this wouldn't be a problem :)

**Comment by AndrewBelt** [comment]
No application I'm aware of saves state to an undo/redo stack. That would take absurd amounts of memory for all purposes and require serializing/unserializing the entire state, which would reset the state of poorly serialized modules.

Undo/redo in Rack will be implemented simply by creating invertible delta transactions on certain actions, like module creation, moving a knob, or patching a cable. `MomentarySwitch` would simply just not create one of these transactions.

**Comment by AndrewBelt** [comment]
Added a while ago.
