### ISSUE TITLE
Less flexibility with frameSwapInterval

### ISSUE THREAD

**Issue by diimdeep** [VCVRack/Rack#1565]
With previous `frameRateLimit` one could precisely set frame rate like 23,
but with `int frameSwapInterval` one is limited to predefined 20 or 30 that could be too little for someone taste or too much for given machine.

**Comment by AndrewBelt** [comment]
The previous behavior was follows, assuming that your screen refresh rate is 60 Hz:
- If `frameRateSync` was true, a `frameRateLimit` of 23 would have effectively given a `frameSwapInterval` of 3, resulting in an actual frame rate of 20 Hz.
- If false, a `frameRateLimit` of 23 would have effective alternated `frameSwapInterval` between 3 and 4, to give an *average* frame rate of 23.

Since I couldn't think of a reason to disable `frameRateSync`, it makes more sense to use the "frame divider" supplied by GLFW rather than my custom implementation of "sleeping the frame duration difference".
