### ISSUE TITLE
Rack stdio logger in (VSCode, Win) Internal Terminal

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#1588]
Operating system: Win 10 Pro, 64 Bit
Rack version: v1.1.5

### Summary

VSCode Internal Terminal (set to msys bash) need some "edits" in how Rack manage stdio.
Otherwise it prints nothing to the buffer.

### Steps to fix it

I've fix it doing two things:

1.  add `-mconsole` to enable the stdio to external application [here](https://github.com/VCVRack/Rack/blob/v1.1.4/Makefile#L40)
i.e. LDFLAGS += -Wl,--export-all-symbols,--out-implib,libRack.a -mwindows `-mconsole` \

2. after [this line](https://github.com/VCVRack/Rack/blob/v1.1.5/src/logger.cpp#L20), add this:
```
#if defined ARCH_WIN
		std::setvbuf(outputFile, NULL, _IOFBF, BUFSIZ);
#endif
```

And it works.
Would you like to add it?

**Comment by AndrewBelt** [comment]
Can you motivate this a bit more? What feature does this bring?

**Comment by Nowhk** [comment]
With this feature, I can intercept the stdout from Rack within VSCode Internal Terminal (i.e. bash).
Else, I won't never see this for example:

![image](https://user-images.githubusercontent.com/19835752/66823601-e168c600-ef46-11e9-94d3-0968d703e06d.png)
i.e. without this, VSCode is not able to intercept what Rack write :) (due to the buffer fix)

**Comment by AndrewBelt** [comment]
Why not use the Mingw64 shell?

**Comment by Nowhk** [comment]
@AndrewBelt I'm using `C:/msys64/usr/bin/bash.exe`, inside the VSCode integrated terminal:
`terminal.integrated.shell.windows": "C:/msys64/usr/bin/bash.exe"`

In this way, I've configured my custom tasks & launch settings, working globally inside the IDE (without compile here, execute there on the shell, and so on).

**Comment by AndrewBelt** [comment]
`-mconsole` changes the PE subsystem type of the executable. There's got to be side effects to that. I shouldn't risk it to fix a workflow I don't even support.

**Comment by Nowhk** [comment]
You can simple strip out the flag if you are not in debug mode... my god! 
Thanks for the support :)

**Comment by AndrewBelt** [comment]
There is no debug build of Rack.

**Comment by polyclash** [comment]
> There is no debug build of Rack.

Hi Andrew,
I too am forced to modify the sources and makefile to generate a debuggable version of racks, without the need to strip the debug information and with the ability to delete the optimization flag, so that it can be used when developing plugins, without always being able to understand what happens and how to optimize your code, so it would be nice to have the option in the makefile of a define that separates the building in debuggable mode.  
In addition, I also use VSCODE and I find it comfortable, and I had to correct some things to make it more Windows compliant, as in the case of the setting of the buffer of the stdio, otherwise incorrect for the windows system, and of course also to have the possibility of Redirect the stdio directly into the internal terminal of VSCODE, you have to add the flag -mconsole, so having a DEBUGGABLE version could make the whole thing much more professional.

**Comment by AndrewBelt** [comment]
The problem with "debug" builds is that the requirements change based on what you're debugging. However, this is off-topic so I'm locking this thread.
