### ISSUE TITLE
When loading a (saved) project, cables change color.

### ISSUE THREAD

**Issue by JoeSleaze** [VCVRack/Rack#159]
win 7 64
VCV 0.3.2

I would love it if the cables would keep the same colors after saving a project.

**Comment by jackokring** [comment]
CV + Gate + Audio is 3 colours. Cross mixes = 6 colours and white for unconnected? Dealer's choice? LED cable sheath? Plugin supplied animators?

**Comment by AndrewBelt** [comment]
@jackokring I never have any idea what you're saying. If English is not your first language, could you post in your native language?

**Comment by jackokring** [comment]
I think I passed English after maths. But it is my first "natural" language. It seems to me beginners would benefit from line level/cv/modulation colouring on the cables. because plugging a CV into a DC coupled amp can be painful on the ear. And so green for limited, red for CV 1v per octave (tune the blues) ...

Pros like to organise by colour on the track. The cables could technically flash, like led cables, but with the full length ...

**Comment by AndrewBelt** [comment]
Rack treats audio and CV the same. It's entirely dependent on the artist/user whether they want to use a signal for CV or audio, so Rack can't figure that out for you. For example, a SEQ3 might control the frequency of an oscillator, but if you clock it really fast, you can turn the sequencer it into a wavetable oscillator.

There are preliminary plans for a toggle setting in the toolbar that changes the color of cables and/or ports based on their voltage or RMS. It's too early to think about that though.

**Comment by AndrewBelt** [comment]
Fixed with 4a3bf84
