### ISSUE TITLE
Compiler Flags Helper Variables

### ISSUE THREAD

**Issue by polyclash** [VCVRack/Rack#1590]
### Summary
 This proposal could make the build process more developer-oriented for the framework, by adding these variables, you might have the ability to override flags assigned to the compiler by the plugin's makefile or make command.

for example you could use a similar command
`make EXTRA_CFLAGS='-O0' EXTRA_CXXFLAGS='-O0 -std=c++17' install`
to override some already set flags set by design or for compatibility reason.

### Proposed design
![image](https://user-images.githubusercontent.com/40276897/66916337-4d1c6300-f01b-11e9-9fcd-1140d7690225.png)

add this extra variables:
```make
$(EXTRA_CFLAGS)
$(EXTRA_CXXFLAGS)
```
to the compile.mk file here
https://github.com/VCVRack/Rack/blob/de76887320eeba2fc2d3b64adf2254aca72ec9d3/compile.mk#L40-L41
to this:
```make
CFLAGS += $(FLAGS) $(EXTRA_CFLAGS)
CXXFLAGS += $(FLAGS) $(EXTRA_CXXFLAGS)
```

**Comment by TronicLabs** [comment]
This seem an no brain solution for an big problem.
I want this.

**Comment by Flowstoner** [comment]
very useful

**Comment by Nowhk** [comment]
Awesome! This will resolve many "custom" issues delegated to developers who want to use debug tools. +1!!!

**Comment by AndrewBelt** [comment]
You can of course define `CFLAGS`, `CXXFLAGS`, `LDFLAGS`, etc and they will be prepended to the Makefile variables. Is your feature request to be able to append flags to redefine flags like `-std=c++11 -std=c++17`?

**Comment by AndrewBelt** [comment]
My first attempt was to *append* environment variables to Makefile variables, so that `CXXFLAGS=-std=c++17` would result in a final value of `-std=c++11 -std=c++17`, i.e. `flags defined in Makefile + environment variables`.

However, after finding no straightforward solution in the Make manual (although I do think it's possible with hacks like temporarily redefining the variables), I realized that users actually *do* expect their environment to be prepended to the final flags because this is the behavior everywhere else. It doesn't seem that `EXTRA_*` is precisely the de-facto standard, but at least it's common enough for me to see it elsewhere.

Added `EXTRA_FLAGS`, `EXTRA_CFLAGS`, `EXTRA_CXXFLAGS`, `EXTRA_LDFLAGS` in 043401c.
