### ISSUE TITLE
Feature request: Change three-position switch behavior so that switch positions activate pendulum fashion rather than cyclical 

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#1592]
### Summary

A mechanical switch with three positions passes through the middle position when it's toggled from either direction. Propose changing three-position switch action in Rack so it behaves the same way. In pendulum, rather than cyclical fashion.

### Proposed design

A three-position switch: A-B-C

- Default: position A (top)
- First click: position B (middle)
- Second click: position C (bottom)
- Third click: position B (middle)
- Fourth click: position A (top)

This adds an extra click to cycle through every position but it feels more natural to me.

**Comment by AndrewBelt** [comment]
This is definitely a matter of preference to the user but probably too fine-grained for a setting. I don't think it should be up to the developer, because the result would just be different modules behaving arbitrarily different.

My subjective opinion is that it's best the way it is, but there's a serious objective problem with pendulum mode. You can't look at a switch and determine which way it'll move when you click it before actually clicking it.

**Comment by jonheal** [comment]
> You can't look at a switch and determine which way it'll move when you click it before actually clicking it. For this reason, I'm rejecting this proposal.

Yes. I can see that point.
