### ISSUE TITLE
Option: global hide/unhide "midi mapping dots"

### ISSUE THREAD

**Issue by Eurikon** [VCVRack/Rack#1657]
### Summary
I recently sent a suggestion/request to a developer to allow the user to hide/unhide the yellow dots that appear after mapping knobs etc.
When mapping a lot of knobs on a particular module this module gets swamped by yellow dots, 
so i thought it would be usefull if we can hide and unhide them from a menu.

Should this be asked to developers to be done from their side, 
or is this something that can be achieved globally from VCV Rack if it was added.
Or does it need both?
 
### Proposed design

Would be very useful if it was an option in the view menu.

**Comment by stoermelder** [comment]
Hi Latif, 
the module which is responsible for the parameter mapping can change the color of the mapping indicator. Especially on my modules CV-MAP etc. I could easily add an option to draw it transparent.

If it is desired to hide all parameter indicators at once a new setting is needed for Rack because the drawing is done in `ParamWidget::draw`.

**Comment by Eurikon** [comment]
Hi Ben, thanks for getting involved. If that is no problem for you to add, then please yes :) 
How would that work then, would it be a global setting on the module that hides all the dots of the mappings initiated by that instance of the module?
Or would it be per mapping.

**Comment by Eurikon** [comment]
For anyone reading this, the "hide mapping indicators"feature has been added to the Stoermelder plugin pack midi mapping modules:
https://github.com/stoermelder/vcvrack-packone/commit/74f89d7f1e6f16062b0ba22d7a43ec52fef3a8b1

Thanks!
