### ISSUE TITLE
Big CPU increase at switch from 44100 to 88200 samplerate

### ISSUE THREAD

**Issue by Suitundo** [VCVRack/Rack#170]
OS (if applicable): Win 10, x64, build 1703
Version (or "dev" if compiling from source): 0.3.2
CPU: Intel Core i5 6600k.
Driver: ASIO
USB interface: Behringer UMC404HD

When I start a new project, and increase the samplerate from 44100 to 88200 I see the CPU increase by about 25-27%. This big jump in CPU usage doesn't happen from 44100 to 48000, or from starting point 88200 to the highest samplerates.

CPU at:
96000: 28-30%
176400: 28-30%
192000: 28-30%

**Comment by AndrewBelt** [comment]
You should expect CPU usage *on the audio thread* to be proportional to the sample rate, but at this time Rack consumes a lot of CPU to render graphics so this may be the bottleneck in your case, depending on whether your graphics card is able to do most of the work or not.

When you say "start a new project", are you actually initiazing the rack with a few modules, or just running it with no modules?

**Comment by jackokring** [comment]
Just learned some vector instructions slow cpu clock and have to be used
heavily for net gain.

On 3 Oct 2017 02:27, "Andrew Belt" <notifications@github.com> wrote:

You should expect CPU usage *on the audio thread* to be proportional to the
sample rate, but at this time Rack consumes a lot of CPU to render graphics
so this may be the bottleneck in your case, depending on whether your
graphics card is able to do most of the work or not.

When you say "start a new project", are you actually initiazing the rack
with a few modules, or just running it with no modules?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/VCVRack/Rack/issues/170#issuecomment-333712531>, or mute
the thread

**Comment by Suitundo** [comment]
@AndrewBelt : 

I have a fast gaming card, a custom Nvidia Geforce GTX980, in my desktop pc.

Am running VCVrack without any modules to check the CPU usage at different samplerates.
Do wonder why only changing the samplerate impact the CPU perforance so much from 44100 to 88200 ( 25% higher ), this big rise doesn't occur at the higher samplerates. I could provide a video to show what I mean.

**Comment by Suitundo** [comment]
@AndrewBelt : I'm now testing the CPU usage when there are some modules in the project ( audio device, VCO and Scope ), the difference in CPU usage between 44100Hz and 88200Hz is then only +/- 6%.

**Comment by AndrewBelt** [comment]
If you use 0 modules, the audio thread will essentially be sleeping 99.99% of the time, so the sample rate won't differ. You're probably just measuring random fluctuations of graphics CPU usage.

**Comment by Suitundo** [comment]
OK, yea probably.
Guess this can be closed then, thanks for commenting.
