### ISSUE TITLE
Use Hardware MIDI Controller to Change Patch Cables

### ISSUE THREAD

**Issue by playinmyblues** [VCVRack/Rack#1843]
Using a hardware MIDI controller would be great for changing patch cables. I realize there is no hardware controller that addresses this type of control.

However, being able to number patch patch points on modules and then using keys that correspond to those numbers might work. Press one key for the origin patch point (input or output) and a second key for the second patch point.

**Comment by nay-seven** [comment]
you can check this 👍 [https://www.youtube.com/watch?v=taQFeYINIXE&t=2s](Midilar patch bay)

**Comment by playinmyblues** [comment]
That is awesome. I will check that out to see if I can use it.

Thinking about it some more gave me an idea on how to do this with a MIDI keyboard. Take any MIDI keyboard and connect it to the MIDI patchbay module. Specify the split on the module. Keys to the left of and including the split key are inputs. Keys to the right of the split are outputs. Press any key, input or output then press the corresponding input or output you want to connect the patch cable.

The module itself would have to allow for inputs and outputs from the other modules in the overall patch of VC Rack.

**Comment by stoermelder** [comment]
I wrote the module used in the Midilar video and it should be capable of what you are describing. Unfortunately there is no manual at the moment how to configure it :-(

**Comment by schuster-rainer** [comment]
The usage is quite easy from my point of view. I just had a look at it yesterday.

If you have a look at the sample patch https://github.com/stoermelder/vcvrack-packtau/blob/v1/patches/t7-demo-gate.vcv#L218 you see what T7-CTRL is doing.

Copying the sample config from the right click menu gives you

```json
[
  {
    "events": [],
    "driverName": "MidiCcTwoMessageToggle"
  },
  {
    "events": [
      {
        "type": "cable",
        "midi": {
          "channel": 1,
          "cc": 1,
          "ccValue": 127
        },
        "target": {
          "moduleId": 3,
          "portType": "output",
          "portId": 0
        },
        "cableColor": "#ffff00",
        "comment": "Blabla"
      },
      {
        "type": "cable",
        "midi": {
          "channel": 1,
          "cc": 2,
          "ccValue": 127
        },
        "target": {
          "moduleId": 3,
          "portType": "output",
          "portId": 1
        },
        "cableColor": "#ffff00",
        "comment": ""
      },
      {
        "type": "cable",
        "midi": {
          "channel": 1,
          "cc": 3,
          "ccValue": 127
        },
        "target": {
          "moduleId": 3,
          "portType": "output",
          "portId": 2
        },
        "cableColor": "#ffff00",
        "comment": ""
      },
      {
        "type": "cable",
        "midi": {
          "channel": 1,
          "cc": 4,
          "ccValue": 127
        },
        "target": {
          "moduleId": 3,
          "portType": "output",
          "portId": 3
        },
        "cableColor": "#ffff00",
        "comment": ""
      },
      {
        "type": "cable",
        "midi": {
          "channel": 1,
          "cc": 5,
          "ccValue": 127
        },
        "target": {
          "moduleId": 31,
          "portType": "input",
          "portId": 1
        },
        "comment": ""
      }
    ],
    "driverName": "MidiCcTwoMessageGate"
  }
]
```

You need to put T7-MIDI on the right side (attach it) to T7-CTRL.

If you need to figure out the module name and the port number add the T7-Assistant to your patch. Now when you click a port on a module T7-Assistant displays the moduleId and portId.

Setup the midi channel and MIDI device (in my case it is a virtual one). Wirte the proper CC and channel values to the json for every input and output you want to address by duplicating an existing entry. 

In order to install the packtau moduels go to https://github.com/stoermelder/vcvrack-packtau/releases download the zip and copy it to your plugin folder of rack. On Windows and MacOs you can find it in your users home folder in Documents/Rack/plugins-v1

**Comment by AndrewBelt** [comment]
I'm rejecting this feature request for Rack because there's no single standard way to offer a cable manipulation protocol, and external integration features should only be added to Rack if they are standard and well-known, but feel free to continue using this thread for discussion of a third-party Rack plugin that uses the Rack API to manipulate cables, until such a plugin is developed.
