### ISSUE TITLE
rack::dsp::SampleRateConstrainer

### ISSUE THREAD

**Issue by Kautenja** [VCVRack/Rack#1849]
### Summary

I'm working on some modules that are PSG emulations that are hard locked at a sample rate of 32kHz. I'd like to extend the dsp library with a logic class for doing this form of hard-locked sample rate conversion. From the forum I've seen a few other examples of modules that are designed to run at a locked sample rate, but simply fall back on the engine sample rate at the moment.

### Proposed design

The implementation is pretty conceptually simple, I believe one just needs two instances of `SampleRateConverter`, – one to handle input conversion and one to handle output conversion, – and a clock that tracks the internal sample rate of the module. The converter would intercept the inputs and outputs such that the client module uses `inputs[...]` and `outputs[...]` with the assumption that data is flowing at the locked sample rate.

![data flow](https://user-images.githubusercontent.com/2184469/94562478-fe1b0e00-022a-11eb-8262-d0f1fdee7c91.png)

### Nota Bene

This feature could also be implemented through Rack host directly. A developer could specify the locked sample rate of a module in the `plugin.json` and the above logic could be handled by Rack instead of the module. IMO this would make it easier to get all the existing modules on the library that require locked sample rates up to date, but obviously is much more technically expensive to implement.

**Comment by AndrewBelt** [comment]
Converting signals should be done inside `Module::process()` by using whatever methods the plugin developer wishes to use.

It's not a good idea for Rack to perform any sample rate conversion of cables or ports, because typically not all signals need to be converted CV, and maybe some need to be converted to different sample rates. Rack's engine shouldn't do any DSP like sample rate conversion, only its plugins.
