### ISSUE TITLE
Help with development

### ISSUE THREAD

**Issue by bontric** [VCVRack/Rack#186]
Hey @AndrewBelt ,
I wanted to ask whether you'd like some help with development. 
I could implement the MIDI features as discussed in Issue https://github.com/VCVRack/Rack/issues/81. Since there is no guide for contributors yet, I wanted  to discuss this with you first to avoid redundant or unnecessary work.

**Comment by AndrewBelt** [comment]
For contributions to Rack itself, the requirement is that it has to reduce rather than increase my workload. The easiest ways to do this are to take on research-based projects rather than adding spurious features or arbitrary refactoring/restructing. Some particularly topics would be
- multi-threading the audio engine
- reducing GPU workload through framebuffer caching, better tessilation algorithms
- improvements to the [Portaudio](http://www.portaudio.com/) codebase, which helps many other projects as well
- C++-y stuff like an implementation of mixins

and finally, and most relevant to you
- MIDI Interface revamp #81, including switching to RtAudio if we decide that's best
- Audio Interface revamp #82 

If you think you can succesfully take on #81, I can pass the torch onto you. You'd probably be better than me, since I only have a few MIDI controllers in the studio and am not a heavy MIDI user.

**Comment by bontric** [comment]
That sounds good to me. Here is what I've planned so far:
1. Compare PortMidi and RTmidi, and fix https://github.com/VCVRack/Rack/issues/62.
2. Restructure the midi implementation  to support multiple interfaces on a single port (as proposed in https://github.com/VCVRack/Rack/issues/81).
3. Implement/improve the modules (Including a proper structure for shared functionality)

There is some time on the weekend so I'll start working on 1&2. I'll get back here or make a pull request if I have something done, so you won't have to do more than giving some feedback.
