### ISSUE TITLE
VCV 1.1.6 crash issue upon fresh OS and VCV install. Whenever I try to launch VCV it crashes.

### ISSUE THREAD

**Issue by sulbnyc** [VCVRack/Rack#1915]
--> Logs attached: logs.txt, report.txt, screenshot  and msinfo32

```
![crash](https://user-images.githubusercontent.com/83525900/116801461-de80f680-ab27-11eb-87ed-abe4cb9c4d11.PNG)
[log.txt](https://github.com/VCVRack/Rack/files/6410732/log.txt)
[Report.txt](https://github.com/VCVRack/Rack/files/6410733/Report.txt)
```

### Details
```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
Operating system and version: Windows 10 Pro Version 20H2
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): msinfo32 attached
[msinfo32.txt](https://github.com/VCVRack/Rack/files/6410741/msinfo32.txt)
```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

### Steps to reproduce

- Install Windows 10 Pro version 20H2
- Install VCV 1.1.6v
- Launch VCV

**Comment by sulbnyc** [comment]
Any assistance would be helpful

**Comment by sulbnyc** [comment]
Thanks, @MarcBoule  for a quick look. Let's hope I find a solution soon 👯

**Comment by MarcBoule** [comment]
If I had to guess, I would say it might be related to graphics drivers, since in the log, the next few lines should be something like this related to graphics (this is what the next lines are on my setup):

```
Window content scale: 1.000000
Renderer: Intel(R) HD Graphics 620
OpenGL: 4.4.0 - Build 21.20.16.4727

```

I think I saw also that your laptop has another graphics card (AMD Radeon 530), if correct, you should definitely try updating/installing any graphics drivers for that (perhaps more than just what Windows installs by default).

**Comment by sulbnyc** [comment]
I tried updating the drivers but no luck there

**Comment by gitterdude** [comment]
Maybe it's because of the switchable graphics.
Try to force Rack to use either the AMD card or the Intel one and see if one works.

Here's a Lenovo guide on how to do that.
https://support.lenovo.com/se/en/solutions/ht078706-how-to-configure-switchable-graphics-on-ideapad-laptops-windows

**Comment by sulbnyc** [comment]
I tried multiple things to update drivers from vendor and now stuck with this error
[log.txt](https://github.com/VCVRack/Rack/files/6517589/log.txt)

I think its windows update 20h2 which broke everything. even the native access broke.

**Comment by gitterdude** [comment]
It works for me on a ThinkPad running a fresh install of 20H2.
I don't have switchable graphics so that could be the reason it works.

Did you move any non-Fundamental plugins from your plugins-v1 folder?

Maybe you can turn off the switchable graphics in BIOS. At least just to test if that is the problem.

**Comment by sulbnyc** [comment]
Yes you did it. I disabled it from BIOS and we are back online baby...
thanks for help @gitterdude

**Comment by sulbnyc** [comment]
@MarcBoule thank you very much for your response to my post as well. You all stay safe and happy weekend.
