### ISSUE TITLE
Multithread the audio engine

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#195]
At this point, there may be lower hanging fruit (e.g. #194) to increase the number of possible modules a given computer, but multi-core speedups might be important later.

There is no way around putting a barrier at the end of `engineStep()` in engine.cpp. Note that operating system context switching is around 1 to 10us, so we might not even time to wait on locks. Spinning on atomics is faster but would kill the rest of the core and has many other caveats.

**Comment by jackokring** [comment]
Perhaps a specialist module say "a thread mixer" then threads are
muxed by user request, and a latency lock free buffer could be dialed
in with user knowledge.

On 07/10/2017, Andrew Belt <notifications@github.com> wrote:
> At this point, there may be lower hanging fruit (e.g. #194) to increase the
> number of possible modules a given computer, but multi-core speedups might
> be important later.
>
> There is no way around putting a barrier at the end of `engineStep()` in
> engine.cpp. Note that operating system context switching is around 1 to
> 10us, so we might not even time to wait on locks. Spinning on atomics is
> faster but would kill the rest of the core and has many other caveats.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/VCVRack/Rack/issues/195


-- 
http://www.kring.co.uk

**Comment by AndrewBelt** [comment]
I don't understand your idea. How does this relate to the engine loop in https://github.com/VCVRack/Rack/blob/master/src/engine.cpp#L68-L71? How does it handle inputs and outputs?

**Comment by martin-lueders** [comment]
As far as I can see it, all modules are writing only into their own outputs. This means that we should not have to expect any data races regarding the modules (wires are different). In principle, a simple OpenMP parallelised loop over the modules should work. I have to investigate whether the OpenMP overhead outweighs the benefits. I hope that threads can be kept open to avoid their creation and destruction in every call to engineStep().

I will try to give it a go next weekend.

**Comment by AndrewBelt** [comment]
^ You might reach the same conclusion I did. I tried keeping the threads open for very large buffer sizes (like 4096) for the experiment so that lauching them is out the picture. Then at the end of `engineStep()`, I put a `#pragma omp barrier` and found its overhead was too high. I then explored atomic spinlock barriers and considered timing each module to better partition the modules over threads. I then got bored and started working on something else.

It's good for another pair of eyes to look at it though!

**Comment by briansorahan** [comment]
Here is how they did it for jack2 http://www.grame.fr/ressources/publications/Jackdmp-ICMC2005.pdf
Not sure if the same techniques could be used in Rack.

**Comment by AndrewBelt** [comment]
That could be used, but Rack would need to sequentially step cycles. Statistically, what proportion of modules in patches are not involved in a cycle?

**Comment by briansorahan** [comment]
I think to emulate jack, Rack would have to

(1) Sort modules based on their connections.
(2) Step them in the order determined by (1).

Does Rack do this today? I took a look at the code in src/engine.cpp and it seems like the answer is no.

> That could be used, but Rack would need to sequentially step cycles.

Not exactly sure what you mean, but cycles definitely introduce complexity!

From the paper:

>  In the event of feedback loops, there is no ”correct” ordering of the graph, so Jack just picks one of the legal possibilities

I'm thinking that in the face of feedback loops, any legal ordering effectively removes edges from the graph to make it acyclic. But then the question is what do you do with those edges?

I don't know how jack handles this. Maybe the jack-devel list can shed some light.

**Comment by AndrewBelt** [comment]
Modules are stepped in an order not related to their graph structure. This is okay because order doesn't matter since each cable adds a one-sample delay.

Yes, you are correct. That paper only works with trees, so any cycles would need to be "reduced" into a tree of the graph's [strongly connected components](https://en.wikipedia.org/wiki/Strongly_connected_component). Then, the strongly connected components could be assigned a thread in a similar method to the JACK paper, which could be given a block of samples to evaluate and then fill some output buffers to be given to the next component.

A significant issue is that a really spaghettied patch will have only *one* strongly connected component, so the algorithm falls down to a serial one.

**Comment by lodsb** [comment]
Another idea is to to use a thread-stealing approach to scheduling the computation with the benefit of load-balancing and disregard for the graph structure (as it is currently implemented). As pointed out earlier, latency is the issue for dequeing/blocking/* maybe something like an efficient/lockfree reader/writer queue can help (e.g.` https://github.com/cameron314/concurrentqueue` ).  My guess is, that you need to add sufficient latency to compensate for the queue and thread overhead, but it may not be as large as 4096 samples. I've read on KVR (I think) that U-He plugins use more-or-less an adhoc approach for thread creation in real-time and buffer of 32 samples. I've not looked into the VCV rack code, yet (except for the engine-step method), but it may work to just push the (numModules+numWires)*numLatencySamples jobs into the queue as something like ````struct {bool moduleOrWire; union {Module* modptr; Wire* wirePtr;}}```` (in-order) and then have all threads, including the main thread, work until the queue is empty. Sounds too primitive?

**Comment by AndrewBelt** [comment]
@lodsb To be honest, I'm not clear what your proposed method is. Are you proposing a 32-sample (or so) buffer on each cable? If so, I'm opposed to making the cable buffer anything larger than 1. If not, how does it address the inevitable problem mentioned above about cycles in the graph?

**Comment by lodsb** [comment]
@AndrewBelt No, 32 samples per cable would be insufficient for feedback patches. I mean that you use a thread/work stealing technique. Let's say that in the engineStep method, computing one step for a module is a job and then (optionally) the buffer iteration/copy for a cable is another job. Then you create a queue of jobs, in the order you may want to have these jobs completed (e.g. first all modules, then all cables), you also need a pool of threads (e.g. fixed amount of threads). Then the iteration loop for each thread is something simple *like* ````run() { while(!queue.empty()){ auto job = queue.dequeue(); job->step();  }  } ````; of course you need a multi-consumer-multi/single-producer queue (like the concurrent queue by moody camel) that takes care of the implicit race conditions. 
This is the simplest work-stealing approach that I can currently think of, of course the devil is in the details. But the benefit of this approach, coupled with a thread-pool is that you don't need any special scheduling and get some work-balancing among the threads; I am not saying this is the most efficient way to do it, but it may be a non-invasive one that could pay off sufficiently. One optimisation could be to shuffle the queue of modules randomly so you get a near optimal load distribution on average; maybe measuring would be better, maybe the hot-loops in the modules' step method are not sufficiently long, so you waste too many cpu cycles as cache-misses due to the ad-hoc ordering of computation steps (module->step()).
Even for the highly efficient moody camel implementation of a concurrent queue, you have some overhead, so instead of doing one engineStep, it may be better to do 32/64 of them in a row (I think you are doing something comparable in your realtime audio thread already? (just had a quick glimpse on the code) ). That's why I said, you could instead fill the job queue several times with the same content (jobs) or you could loop over it, etc. It was just a quick thought. Anyway, I am not claiming that this works well in practice, it was just a quick thought that I had when quickly glimpsing over the code and thought it was worth sharing :-)

**Comment by AndrewBelt** [comment]
Okay, sure makes sense. You're focusing on the implementation of the stepping itself, which is fine, but the main issue is traversing through the dependency tree. What modules belong in a group of strongly connected components (SCC)? When should threads be assigned a SCC to work on? Rougly how do threads "solve" their given SCC task? Do we treat modules not belonging to a SCC (with more than one module) differently?

**Comment by AndrewBelt** [comment]
>if you want to get rid of the cable delay as well

No no, you assumed correctly at first. I will still maintain 1 sample delay, just like the single-threaded method. This is even a requirement for some patches to work. The SCC stuff is considered because it is separates the rack into the topologically finest sets of modules which can be crunched by a single thread without waiting on other sets for input values on every sample. SCCs only need to communicate with each other occassionally, say, every 32 samples.

>topological ordering

No topological ordering is needed, just treat the graph of SCCs with 32-sample buffers between them, as I do now with the original graphs with 1-sample buffers.

The SCC method is beautiful because a *linear* algorithm exists to convert a graph to a graph of its SCCs. (It is also the *only* method that will speed up arbitrary graphs in Rack, but that doesn't take away from its impressiveness.)

Now the issue with all of the above is that if you connect your master mixer (usually the last module in the chain) to the clock (usually the first), then boom, we get an SCC graph with one node and we have a serial algorithm, with additional overhead that we've just added.

**Comment by modlfo** [comment]
Going back to the strong connected components approach, I remember reading some algorithms that are used to get a small set of cuts to the graph in order to break the cycles. I don't remember the name of the paper, but I found something that looks close to that. In case someone is interested in keep researching here's one start https://link.springer.com/article/10.1007%2FBF00993315

**Comment by AndrewBelt** [comment]
What do you mean break the cycles? You can't modify the graph, so if there's a cycle, you have to deal with the cycle.

**Comment by modlfo** [comment]
@AndrewBelt I was thinking something in the lines of what Reaktor does. Having the graph of connected modules, the strong components is run to do the sorting and detecting cycles. Reaktor breaks the cycles by adding a single sample delay, that way the graph becomes a tree. Having the tree, something in the lines of what Jack does to parallelize can be done. When breaking the cycles is desirable that a minimal number of delays is inserted.

Maybe the current approach of having the one sample delay wires is the best for parallelizing. The only advantage of the approach I mention is that the total delay can be reduced, but I don't see it as a major problem right now.

**Comment by Rcomian** [comment]
I've been looking at multithreading the engine for my own purposes.
What I've got is good enough for me at the moment, but it busywaits, rather than breaks down the SCC's.
Choosing how many threads to use is down to the user.

Not sure if you're interested in looking at all. It's available if you want to glance over it.

[https://github.com/Rcomian/Rack/commits/features/multi-threaded-engine](https://github.com/Rcomian/Rack/commits/features/multi-threaded-engine)

**Comment by AndrewBelt** [comment]
Haven't looked at your code, but what happens when you change the busywaiting to thread yielding?

**Comment by Rcomian** [comment]
I'll try it, but any time I've had a thread sleep in the main loop it's caused problems. Maybe pure rescheduling will be faster.

I do sleep the threads during the audio module's wait time, that helps cpu usage somewhat. I need to find a way to measure the overhead in waking the threads, however.

**Comment by Rcomian** [comment]
Ok, with unscientific monitoring using `top`, calling `std::this_thread::yield()` in the busy loop makes absolutely no difference whatsoever. If anything the cpu usage might go up slightly.

I find this surprising.

My oversize patch has these characteristics when running with audio sleeps:

1 thread: 173% (can't keep up at all)
2 thread: 225% (perfect sound)
3 thread: 255%
4 thread: 280%

With the different waiting models, the 3 thread processing has the characteristics:

330% - no waits
330% - yield
255% - sleep
260% - sleep + yield (?)

**Comment by AndrewBelt** [comment]
>absolutely no difference whatsoever

compared to what?

**Comment by Rcomian** [comment]
compared to an empty loop.

330% - no waits (empty loop)
330% - yield

**Comment by ndrspcfd** [comment]
@modlfo : regards the "cuts" are you thinking of [this paper on 'the feedback arc set'?](https://pdfs.semanticscholar.org/c7ed/d9acce96ca357876540e19664eb9d976637f.pdf) or maybe the Berger/Shor one it mentions?

I guess these could be interesting from the point of view of optimising the processing order of modules, rather than "cutting" any cables (except that VCV Rack presents a more "interesting" problem in that the modules have a variable processing cost!)

**Comment by WouterSpekkink** [comment]
@AndrewBelt  @Rcomian I just wanted to mention that I just downloaded and tried Rcomian's build on Linux and it also seems to work well for me. I created a large patch that quickly went choppy with the normal build, but after setting the number of threads to 4 (out of 7 available) the choppiness disappears. Is there a preferred way in which I can do a more systematic comparison, and would that be helpful at all?

**Comment by Rcomian** [comment]
@WouterSpekkink thanks for checking it out. A bit more about this engine:

I wrote this as I use a large patch that doesn't fit in a single thread and this frees me up beautifully. I have tested it with artificial patches, things like many Plateverb's being reset with a fast LFO's and it does seem to help, but only to a point.

I'm not really sure how to measure the real benefits and costs. I have found at times that what I felt was an incremental increase needed 2 extra threads to prevent stuttering rather than the 1 extra thread I was expecting, so I'm assuming there is an overhead that's not getting the most out of the threads. Perhaps the wake-up time after an audio sleep where the data can be processed but threads are still waking up (this takes between 1 & 2 sample times at 44.1khz).

I have notice that going beyond the physical cores is useless - hyperthreading doesn't help at all. I've got an 8 core 16 thread cpu so I've been able to stretch the legs of this patch.

There are definite costs to using threads you don't need as audio-rate waiting is done by spinning the threads at 100% cpu usage. The whole engine does sleep when sync'ing with the audio hardware, so that helps reduce any overhead.

I did artificially limit how many audio threads this will spawn, as there is another thread in the application that needs some space and the os needs something to work with as well. That's why you got the limit of 7 instead of 8. Assuming you've got a 4 core hyperthreaded cpu, choosing 4 threads was wise.

**Comment by WouterSpekkink** [comment]
@Rcomian Yes, you are right about my CPU, and I assumed that one thread was being reserved for running OS stuff. I did actually try to see what happens if I select more threads. Selecting more than 4 seems to cause the same issues as with the vanilla VCV Rack. However, with 4 threads it works like a dream where it would first start stuttering on me with very large patches.

**Comment by Rcomian** [comment]
FYI, I've written up the things I've found when trying to multithread the rack engine: https://github.com/Rcomian/Rack/wiki/Multi-threading

**Comment by ludzeller** [comment]
I understand the basic complexities of multithread programming, but am not experienced in implementing solutions to them in the wild... Nonetheless, let me offer you an end user perspective on this that might offer a workaround until a full solution has been found:

I assume that it is much easier for traditional DAW software packages to offer multithread support, since they actually do it on a per channel basis. The plugins of each channel can therefore be calculated in parallel and summed together without worrying about tree structures, feedbacks, timing, etc. 

Couldn't this principle be transferred to VCV Rack by modifying the Fundamental/Audio plugin accordingly? Imagine you run four multi-thread enabled Fundamental/Audio plugins... the user/musician could then segment their patch to their own liking, as they see fit for their musical idea. In reality we (musicians) do this anyways, since we need structure in order to be able to understand and control what we do. 

Andrew was looking for ways to identify "strongly connected components (SCC)": could the strategy I described above be used to have these identified/created/designed/structured by the people who use VCV?

And I guess it doesn't have to be done in the Audio output plugin - if that adds further issues - but it could also be done in an according multi-thred mixer plugin. Maybe that is what jackokring was talking about on 10 Oct 2017.

**Comment by AndrewBelt** [comment]
@ludzeller No need to worry about SCCs anymore. If you read his above writeup, @Rcomian  demonstrated that thread barriers every sample could be done with busywaiting with very low overhead relative to the duration of a sample.

**Comment by mkruselj** [comment]
Sooo, multicore support officially coming to VCV soon-ish (v1.0)?

**Comment by AndrewBelt** [comment]
Haven't started working on it, but if @rcomian's research is valid, I'll implement it the way he suggests.

**Comment by mkruselj** [comment]
That is great news :)

**Comment by diimdeep** [comment]
Tried fork from @Rcomian https://github.com/Rcomian/Rack with multithreading.  
More then 1 thread worsen performance on my machine with 4 cores.  
From 50% cpu to 80%(2 threads) to glitches(3 threads)

macbook retina 2013  
macOS 10.14.2  

here is flamegraphs  
[Archive.zip](https://github.com/VCVRack/Rack/files/2793968/Archive.zip)

**Comment by Rcomian** [comment]
if a patch can run without glitches in a single thread, adding a thread just adds pure overhead.

do you have 4 actual cores or 2 cores with hyperthreading? hyperthreading works horribly with this multicore approach, even with big patches.

**Comment by AndrewBelt** [comment]
Looks like we'll just go with a simple OpenMP solution. Busylocks don't do any better than OpenMP's dispatching.

This is good because multithreading will be a ~3-line fix.

Hyperthreading is useless, so we should have a menu item that displays up to the number of physical cores on your machine. The trick is asking the operating system for this number, not the hyperthread number.

**Comment by mkruselj** [comment]
Just out of curiosity - why is HT useless? :(

**Comment by mkruselj** [comment]
Gotcha, thanks for the info :)

Man, looks like Ryzen and Threadripper users might get a pretty good kick from this feature.

**Comment by AndrewBelt** [comment]
I'm so glad my studio computer has 12 physical cores :) My dev laptop has 2 though, so I'm testing this on a large range of processors.

**Comment by AndrewBelt** [comment]
Try 557460b if you want, I'm going to lunch.

**Comment by AndrewBelt** [comment]
Well, I've done about all I can do here. If anyone wants to do further research, there may be some incremental improvements, but I doubt you can double the number of modules on an N-core machine now.
