### ISSUE TITLE
Errors creating a MIDI Module (Win only)

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#211]
OS (if applicable): Win 10
Version (or "dev" if compiling from source): dev

last night I created a MIDI Module on MAC (MIDI to Trigger), the code is correctly compiled and it worked quite well on Mac....
today I am trying to compile it on my PC, (Freshly cloned from repository and rebuilt everything with NO errors...) but I get errors...any hint???

> 
> $ make
> g++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -DVERSION_dev -MMD -        O3 -march=nocona -ffast-math -g -Wall -DARCH_WIN -D_USE_MATH_DEFINES -std=c++11         -c -o build/src/AutodafeMidiInterface.cpp.o src/AutodafeMidiInterface.cpp
> g++ -o plugin.dll build/src/AutodafeMidiInterface.cpp.o build/src/Autodafe.cpp.o         -shared -L../../ -lRack
> build/src/AutodafeMidiInterface.cpp.o: In function `RtMidiIn::getMessage(std::ve        ctor<unsigned char, std::allocator<unsigned char> >*)':
> C:\users\anton\desktop\vcv\rack\plugins\autodafe-MIDI/../../dep/include/rtmidi/R        tMidi.h:581: undefined reference to `MidiInApi::getMessage(std::vector<unsigned         char, std::allocator<unsigned char> >*)'
> C:\users\anton\desktop\vcv\rack\plugins\autodafe-MIDI/../../dep/include/rtmidi/R        tMidi.h:581: undefined reference to `MidiInApi::getMessage(std::vector<unsigned         char, std::allocator<unsigned char> >*)'
> build/src/AutodafeMidiInterface.cpp.o: In function `MidiIO::MidiIO(bool)':
> C:\users\anton\desktop\vcv\rack\plugins\autodafe-MIDI/src/AutodafeMidiInterface.        cpp:39: undefined reference to `RtMidiIn::RtMidiIn(RtMidi::Api, std::__cxx11::ba        sic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned         int)'
> collect2.exe: error: ld returned 1 exit status
> make: *** [../../compile.mk:38: plugin.dll] Error 1
> 
>

**Comment by AndrewBelt** [comment]
Hmm, did you do re-make the dependencies in dep/?

**Comment by antoniograzioli** [comment]
git submodule update --init --recursive in /dep ??? yes I have done that...
make dep gave no errors and displayed the "Successfully Built" messages...
The excat same code compiles 100% on mac...

**Comment by bontric** [comment]
Not a real solution to this, but I could add the module to the core midi modules, it's just a few lines of code.

**Comment by AndrewBelt** [comment]
Huh? I think this is a build issue.

Oh, I just realized you made your own MIDI module. The reason is doesn't work on PC is because of the fundamental differences between DLL loading and dylib/so loading. You essentially have a root node (Rack) and two leaf nodes (libRtMidi.so/dll/dylib and Autodafe.do/dll/dylib). On Linux/Mac, leaf nodes can link to each other because symbol linking is done at runtime. On Windows, they can't because DLLs must specify the address of the symbol, not the symbol name. There are two ways around this: Rack static links RtMidi.a, at least on Windows; or you build and supply your own copy of RtMidi.dll and (I think) put it in the same directory as your plugin.dll.

**Comment by antoniograzioli** [comment]
thanks, this is probably the cause. I'll see if I come up with a solution :-)

**Comment by AndrewBelt** [comment]
It's a nearly unavoidable problem (except linking your own MIDI library). What we could do is add a MIDI wrapper to the Rack API. Since I compile with `--export-all-symbols` on Windows, the functions of the API would be available to plugins guaranteed (and not optimized out). You then wouldn't use RtMidi directly but instead use our wrapper of RtMidi.

**Comment by AndrewBelt** [comment]
Actually wait, you might be able to compile your plugin with a library search path of `/dep/lib` (relative to your plugin's directory) and link to it.

So add this near the top of your Makefile.

	LDFLAGS += -L../../dep/lib -lrtmidi

Does it compile? Does it load during runtime?

**Comment by antoniograzioli** [comment]
no it doesn't compile....

**Comment by AndrewBelt** [comment]
What if you just use the direct library path?

    LDFLAGS += ../../dep/lib/librtmidi.dll.a

Make sure there's a file at that path. I could have mistyped it.

**Comment by antoniograzioli** [comment]
LDFLAGS += -L../../dep/lib -lrtmidi ----->cannot find -lrtmidi


LDFLAGS += ../../dep/lib/librtmidi.dll.a     -------> No such file or directory

the path seems correct...

**Comment by antoniograzioli** [comment]
sorry, my falu, I forgot a "slash"

LDFLAGS += ../../dep/lib/librtmidi.dll.a    -------> OK ! :-)

**Comment by AndrewBelt** [comment]
Does it run? I'm surprised that actually works...

**Comment by antoniograzioli** [comment]
yes perfectly :-) compiled and running

**Comment by AndrewBelt** [comment]
Great!

**Comment by AndrewBelt** [comment]
You might want to wrap

    include ../../arch.mk
    ifeq ($(ARCH), win)
        ...
    endif

around that.

**Comment by djpeterso23662** [comment]
@antoniograzioli did you release this MIDI module? I was thinking of something similar.

**Comment by AndrewBelt** [comment]
@djpeterso23662 Core MIDI-Trig exists, so why would @antoniograzioli's be needed?
