### ISSUE TITLE
Just updated from master repo, doesn't compile

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#223]
OS: Win7
Version (or "dev" if compiling from source): Dev

src/core/MidiInterface.cpp:4:10: fatal error: rtmidi/RtMidi.h: No such file or d   irectory
 #include "rtmidi/RtMidi.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [compile.mk:51: build/src/core/MidiInterface.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
Rebuild the dependencies. `cd dep; make`

**Comment by Strum** [comment]
sorry, still getting errors about rtmidi

cleaned and rebuilt deps and rack.

src/core/MidiInterface.cpp:21:2: error: 'RtMidi' does not name a type
  RtMidi *rtMidi = NULL;

**Comment by AndrewBelt** [comment]
Can

**Comment by AndrewBelt** [comment]
Can you confirm that `dep/include/rtmidi/RtMidi.h` exists?

**Comment by Strum** [comment]
I made a complete new copy and compiled it all again, compiles now, but crashed when i tried to have an instance of each of the 2 new midi input modules using the same port.

**Comment by Strum** [comment]
MidiInWinMM::openPort: error creating Windows MM MIDI input port.

terminate called after throwing an instance of 'RtMidiError'
  what():  MidiInWinMM::openPort: error creating Windows MM MIDI input port.
make: *** [Makefile:56: run] Error 3

**Comment by AndrewBelt** [comment]
Interesting, that's a new problem I haven't seen. Does it happen when creating the module or when selecting a MIDI device?

**Comment by Strum** [comment]
when selecting the device if another module is using that device already 
it seems reproduceable

**Comment by bontric** [comment]
I looked into this a bit @AndrewBelt  

This is a Windows 7 related Problem and was supposedly fixed in Windows 10. (The internal windows function `midiInOpen` called by rtMidi [here](https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L2197) changed in Windows 10 according to  [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/4af71e86-a093-40b9-9a43-06bf47f0e143/accessing-a-midi-input-streams-from-multiple-applications-simultaneously-midiinopen?forum=windowsgeneraldevelopmentissues))

So we have two options. Report this to the rtMidi people or implement a workaround. I'll check if I can find more on this later today.

**Comment by bontric** [comment]
I found an rtMidi issue related to this (See [here](https://github.com/thestk/rtmidi/issues/102)) 

This means, that this is not only related to Windoes 7, but also to Windows 10. (Windows 10 provides an API which would allow opening a single port multiple times, but rtMIDI does not implement this yet.)

@AndrewBelt I can fix this Issue by writing a wrapper for rtMidi which allows multiple modules to access a single instance of `rtMidiIn/Out` which then only "opens" a port once. I was hoping I could avoid that, but it's not a big deal. However, this has an important implication:

We need make sure, that developers programming midi capable modules, use the wrapper I described above rather than rtMidi (or any other midi library, since it this is an issue with the windows API).

I can start working on this wrapper over the weekend, but it suppose it will take me some time to implement and test it properly.

**Comment by bontric** [comment]
Oh, and @Strum you might be able to fix this temporarily by installing the official midi drivers for your device. (As far as I understand it, some midi drivers allow multiple instances to open a port. This was mentioned in the rtMidi issue and also [here](https://superuser.com/questions/1046548/how-can-i-use-a-single-midi-controller-in-multiple-applications-on-windows-7) )

**Comment by Strum** [comment]
Cheers @bontric, I might try that when i find time, i haven't done much with MIDI yet but will try plugging my controller keyboard at some point and see if it's driver supports multiple instances, I've only tried the audio interface's MIDI port so far.

**Comment by bontric** [comment]
@Strum could you do me a favor and test my branch (https://github.com/VCVRack/Rack/pull/231) on Windows? This should support multiple connections from a single device on Windows.

(Note: In principal this should work, but there might be some bugs, I'll finish the implementation tomorrow and would love some feedback)

**Comment by Strum** [comment]
@bontric, Sure, but how do I do that?

This is the first project I've been involved in on git and I'm still learning how to do things.

Do I have to make a complete new copy of the code with your modifications or is there a way to just test those modifications within the existing copy i have?

**Comment by bontric** [comment]
@Strum  Cool, thanks!

To avoid messing up your setup, I suggest you clone my repository into a separate folder and build from scratch:

```bash
git clone git@github.com:bontric/Rack-MIDICC-Fork.git
cd Rack-MIDICC-Fork/
git checkout 2017-10-bontric-midi-interface-revamp
git submodule update --init --recursive
make dep
make
```

**Comment by Strum** [comment]
cheers @bontric, i'll try it later on tonight and let you know how it goes.

**Comment by eres-j** [comment]
Hi!
Just tested @bontric branch and confirm it works (Windows 7).
Tested with one instance of MIDI to CV and one of MIDI CC to CV both with the same midi interface.
Great job.

**Comment by eres-j** [comment]
There is a less critical bug now.
When I save the project containing MIDI modules the open it everything is okay.
But when I launch Rack and it automatically reload the last project,  MIDI to CV module have the good interface selected, but I need to reselect it to let it works.

**Comment by Strum** [comment]
$ git clone git@github.com:bontric/Rack-MIDICC-Fork.git
Cloning into 'Rack-MIDICC-Fork'...
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by eres-j** [comment]
@Strum clone it with this command instead:
git clone https://github.com/bontric/Rack-MIDICC-Fork.git

**Comment by Strum** [comment]
Seems to work, doesn't crash when you have 2 modules on the one interface, don't have time for more thorough testing right now though.
