### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#263]
OS (if applicable): Windows 10 Professional 64bit
Version (or "dev" if compiling from source): 0.4.0

Problems I've found:
1. if the mail is longer than the input box, it goes on a new line
2. if I place Rack on "C:\Program Files\Rack", "Refresh plugin" won't update my folder. I've to do manually. And "Browse Directory" within the Add menu/Plugin name do nothing. I think because the way Windows 10 ask permission to edits any folder. Not sure if there's a workaround, but a message with "permission denied" would be nice.
3. double click on a ".vcv" project try to open the Rack within the folder where I've the project, creating "plugins" folder (empty) (as well with autosave.vcv and settings.json). Of course it won't find any plugins, and it open a black project.
4. Drag N Drop project on Rack do nothing

Thanks

**Comment by AndrewBelt** [comment]
1. I've created an issue at #264 
2. Thanks for confirming this. I thought it wouldn't work but now I know I can't be sure to have write access to Program Files. You might want to consider moving it back, because files like `autosave.vcv` and `settings.json` can't be written. In v0.5.0, the fixed directory `My Documents/Rack/` will be used instead for plugins and settings.
3. Thanks, related to 2.
4. Eh, if another person points this out I'll add it.

**Comment by Nowhk** [comment]
Thanks man! For your time and your big work!
