### ISSUE TITLE
Tutorial: Some plugin information that is not documented

### ISSUE THREAD

**Issue by mcclure** [VCVRack/Rack#279]
I am making a plugin from the tutorial. Looking at https://github.com/VCVRack/Tutorial (should I have filed this issue there?) there are two pieces of information I think I need to know, but do not find documented here or in the Tutorial README:

- What is the correct output "range" when controlling input/output (sound) plugs in VCV Rack? -1 to 1? 0 to 5? Something else? What about 1V/Oct, Gate or other "parameter" type plugs? The existing plugins appear to follow conventions but I'm not sure what. Some of this I can reverse engineer using the scope but I'm not quite sure I'm doing it right… for example the sample plugin is sound -5 to 5 in its code, whereas the default VCO-1 is -5.40 to 5.40 in the scope. If the values are based on some sort of standard voltage values from real world devices, it would be helpful to link to a table or standard if one exists.

- What size should the SVG file be? Does it matter / will it scale vertically to the correct size automatically? What size is the pixel rectangle that createScrew, createOutput plot their pixel values within? Is it based on the SVG file?

    I ask because the default MyModule.svg in the tutorial has some kind of complex scaling which causes its size in SVG coordinates to be something like 23x100, but createScrew, createOutput etc use some other pixel scale which isn't clear to me. Meanwhile whatever pixel scaling is in the default SVG unfortunately breaks the only two native macintosh editors very badly (Inkscape has problemz on macintosh) so it would be nice if I could create my own file, but I don't know what size to make it.

For now i am guessing / looking in a graphics editor but it would be nice to have precise specs.

**Comment by mcclure** [comment]
On a note related to the "ranges" question, putting in my plugin the line

    outputs[IO_OUTPUT].value   += inputs[IO_INPUT].value;

Appears to result in the value being passed through, but the value on the IO_OUTPUT output being about 5 to 10 times amplified what the plug going into the IO_INPUT value would have been had my plugin not been in the loop...

**Comment by AndrewBelt** [comment]
Everything follows the Eurorack "standard", where nothing is really standardized at all, so do whatever you want. Oscillators are usually +/-5V except when they're not, CV is 0V to 10V, or sometimes -10V to 10V. In reality, it can go up to 11.7 or 12V, but I'm straying from the standard a bit.
The scope displays 5.40V because bandlimiting the +/-5V signal produces the Gibbs phenomenon which increases the maximum voltage.

Yes, the size should be 380 pixels like the example file. It does not automatically stretch to fit 380 pixels. The 23x100 are in mm, and at 96 dpi and 25.4 mm/in, so you can divide that out. In Inkscape you can switch to pixel mode and see that the example SVG is pretty close to that. So in summary, if your editor can set in pixel values at 96 dpi (which is the standard for SVG 1.0), use exact pixel values.

**Comment by AndrewBelt** [comment]
I should add a page to the upcoming documentation website called "Conventions" under the Plugins chapter.

**Comment by AndrewBelt** [comment]
I've added https://vcvrack.com/manual/VoltageStandards.html to the Rack manual.

**Comment by milholen** [comment]
Tiny detail: missing bold text under the Audio and Modulation heading:

"**0 to 10V** (unipolar CV) or **±5V** (bipolar CV)"

In the doc, only 0 to 10V is bold so the ±5V is easy to miss if you're skimming.

**Comment by AndrewBelt** [comment]
Fixed. (Will upload later though.)
