### ISSUE TITLE
A proper way to deal with or ignore Sample Rate changes?

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#291]
I started fiddling around with samples, waveforms and so on...take as an example my Drums: https://github.com/antoniograzioli/Autodafe-Drums

Samples were recorded at 44.1KHz...If a user chooses a different SampleRate in Rack, pitch changes (of course). We should probably handle it "internally" in our custom modules, I know...but

I am asking if:

1) is there a way to simply "ignore" Sample Rate changes and force the plugin to always render samples at 44.1?

or

2) can anybody point me to the right way to handle it properly in code?

**Comment by AndrewBelt** [comment]
No, your module needs to step at the current samplerate, so you'll need to convert the samples yourself. Take a look at https://github.com/VCVRack/AudibleInstruments/blob/master/src/Braids.cpp#L161-L171
For a drum, for example, I'd recommend recalculating them and caching the converted samples when `onSampleRateChange()` is called because realtime sample rate conversion is VERY expensive.

**Comment by odahan** [comment]
I don't think it will be reasonable to implement a real time stretching algorithm is your drum generators. So using hires files and skipping some samples to deliver lower res seems to be the simplest solution.

When creating hires samples it will be interesting to normalize the latter because when using your drum modules I found there are some big level differences between instruments even within the same generator.
Perhaps adding a knob to adjust output level will be cool too (as some instruments are sounding louder in the same module). A pitch knob with a jack entry for modulation will be icing of the cake ! :-)

**Comment by antoniograzioli** [comment]
@odahan I had normalized all samples before creating the raw files. However I think I 'll have to rework them completely for next versions

**Comment by antoniograzioli** [comment]
@AndrewBelt  thanks, I'll have a look at the impememtation in Braids

**Comment by AndrewBelt** [comment]
Just use my second suggestion of resampling them when `onSampleRateChange()` is called.

**Comment by antoniograzioli** [comment]
Thanks @AndrewBelt, so far I have managed to solve the problem with some VCOs I am experimenting with...

**Comment by AndrewBelt** [comment]
Reopen if you have any questions still.
