### ISSUE TITLE
Question: Module MIDI CC to CV, save last values

### ISSUE THREAD

**Issue by StinglSa** [VCVRack/Rack#292]
OS: Windows 10
Version: 0.4.0 (current) 

At First, thank you for this awesome piece of software. I just tried it recently and its just great to play around with it. 
When using external midi knobs via the mentioned module it would be great to have the last values saved to the project. At the moment all values are just zero after reloading the project so the last sound setting is gone.

Thanks in advance, 
Sascha

**Comment by AndrewBelt** [comment]
Yup, looks like the values are not serialized.

**Comment by bontric** [comment]
Yeah, there is something though we might want to discuss if we add this:

Should we also "wait" for the knob to be at the stored position again? (Let's say you use your controller somewhere else and the knob position changed. You could then bring the knob back to the position easily if there is a little light or something similiar which indicates that controller and stored position are in sync)

Otherwise, if the knob position has changed externally, twisting the knob would lead to a "jump" from one value to another. (Like it now jumps from 0 to whatever your knob position is once you turn it)

**Comment by bontric** [comment]
@AndrewBelt I think I found a good solution : https://github.com/VCVRack/Rack/pull/293 (Also brings back the nice corner LED's which I think looked pretty nice)

So the way this works now is that the LED in the corner of each output will light up red if the Outputs value is not in Sync with the knob (So: when a patch is loaded and when the ccNumber for that output changed). Once the controller sends a midi cc+/-1 of the current output value the light will turn off. 

If we want to be super fancy we could dim the LED in relation to how close the value is. But I think that could also be a bit too much,

**Comment by StinglSa** [comment]
hi, in case of midi controllers that just send increment/ decrement values you wouldn't need special treatment. ideally there would be two modes , one for endless and one for fixed controllers.

**Comment by bontric** [comment]
Endless controllers are currently not supported anyway, since they require different handling. This will surely come somewhere in the future though.

**Comment by StinglSa** [comment]
Ah ok, I didn’t know that.  Anyway your solution looks great. Looking forward testing it.

**Comment by bontric** [comment]
Thanks, if you want to test it: 

(Best to copy your Rack folder and do this in the copy)
```bash
git pull https://github.com/bontric/Rack-MIDICC-Fork 2017-10-bontric-midi-interface-revamp
```

**Comment by StinglSa** [comment]
Nice! Thank you, works like a charm. I just need one tick to come back in sync with the pocket dial.

**Comment by StinglSa** [comment]
That was impressive fast feature @bontric

**Comment by StinglSa** [comment]
one comment: when i reload the project there is a little shift after sync (my control dials are rastered)
in steps:
before midi actions: sound is exactly as before reload
1. one tick left to come back in sync (sound still correct (oscillation), red light is gone)
2. one tick left (the expected sound (no oscillation))
_3. one tick right (**not** the expected sound (no oscillation))_ 
4. one tick right (the sound i expected one tick before)
i was able to reproduce this after reload. After coming back to the initial sound the behaviour is gone.

**Comment by bontric** [comment]
Yeah, i think I can do this a bit differently to fix the problem:

* Instead of assuming the knob is in the wrong position we assume it's in the right position (So the light is off by default) 

* If the knob is turned it will turn red if the first value it receives is not the value on the output +/-1

* The knob will turn off If the received value is the value which is on the output.

**Comment by bontric** [comment]
@StinglSa You can take another look if you find the time, but should work now.

**Comment by StinglSa** [comment]
@bontric Yeah, it works better now. When i have not changed the values on my controller it`s in sync from start now. In my opinion it`s still hard to get in sync when there is a large gap, because there is no reference in which direction i need to turn the knob or how large the gap is to get in sync. Maybe it would be good to provide the difference between both values like -32 or +32 beside the knob while searching and not in sync. The minus would stand for turn left and vice versa.
Anyway i'm happy using this version now )

**Comment by bontric** [comment]
Glad to hear that it's already making things better for you and appreciate your feedback!

I'm a bit unsure as to how exactly implement an indication for how close you are to the correct position.
1) Numbers as you describe it 
2) Dim the red light according to closeness
3) Leave it as it is (Note: you can actually "guess" the correct position by looking at the output light) 

1 & 2 are nice but also make the UI more complex (which is not necessarily bad but I would leave that open to discussion). I think though that implementing 2) will take just a few minutes. I'll give it a shot and maybe you can tell me what you think.

Another side note: midi controllers often "skip" messages when a knob is turned quickly. This makes  it important to turn slowly when syncing the values, because we want the knob to be exactly in sync. (Otherwise we'd have value jumps).

**Comment by bontric** [comment]
@StinglSa Added the light dimming.

**Comment by StinglSa** [comment]
make run  isn't working since last commit 
make: *** [Makefile:56: run] Fehler 127

**Comment by bontric** [comment]
Is there any other output? It works for me and I didn't change anything substantially so there shouldn't be any "new" build errors.. I assume you are using windows so [this](https://github.com/VCVRack/Rack/issues/303) might be related. Try

```bash
make debug
```
and type `bt` and  `where` in the gdb shell. This might be related to an incompatibility with plugins.

**Comment by StinglSa** [comment]
thanks, i tested it now with a fresh build and fundamentals only. 
I like this solution as its clean and gives you fast feedback when searching in the wrong direction. Its somewhat a fiddle to get the final sync point as the last 10 ticks are nearly black. If the last recognizable red before sync would be around 5 ticks I think as a user I would quick find this color-state and then slowly iterate to the sync point.
