### ISSUE TITLE
Drag and drop files into Rack window.

### ISSUE THREAD

**Issue by matthewfriedrichs** [VCVRack/Rack#345]
Add support for dragging and dropping of files into rack to complement current osdialog library use.
This could be used for a few things, but foremost is loading the directory of sample data.

Another fun potential use would be dragging and dropping different SVG knobs and backgrounds over current ones on the panel. This would let users further customize their patch or let those with visual impairment make an easier to see and read panel.

**Comment by AndrewBelt** [comment]
I'll add an event `Widget::onPathDrop()`. Should its arguments be `(Vec mousePos, std::string path)` or `(Vec mousePos, const std::vector<std::string> &paths)`? The first would be called multiple times for each path if a selection is dropped, and the second calls it all at once. Any reason for the second one? Otherwise I'll use the first.

**Comment by AndrewBelt** [comment]
Fixed with 093fa99, although I'm about to refactor the event framework.
