### ISSUE TITLE
MIDI-to-CV Module Only Working In Precompiled VCVRack Version

### ISSUE THREAD

**Issue by fracturedface** [VCVRack/Rack#352]
OS (if applicable): MacOS 10.12.6 (Sierra)
Version (or "dev" if compiling from source): dev

Using the same MIDI Configuration, the precompiled Rack.app from vcvrack.com works fine, yet compiling from source doesn't work. All of the Midi-To-x modules do not show my MIDI controller (USB2.0 to actual midi ports) or any other controller for that matter.

**Comment by AndrewBelt** [comment]
Will try to reproduce tonight

**Comment by bontric** [comment]
This is due to the new event handling @AndrewBelt . The menu doesn't show
up since on Master they still use the old "OnAction()" and "OnMose*Opaque"
handlers.

On Nov 4, 2017 5:59 PM, "Andrew Belt" <notifications@github.com> wrote:

Will try to reproduce tonight

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/VCVRack/Rack/issues/352#issuecomment-341912655>, or mute
the thread

**Comment by bontric** [comment]
@fracturedface 
If you want this to work now, you can pull my midi modules branch:
```bash
git pull https://github.com/bontric/Rack-MIDI.git 2017-10-bontric-midiCC-fix
```

This also includes some fixes and module updates

**Comment by AndrewBelt** [comment]
Oh, I pulled and fixed this this morning.

**Comment by fracturedface** [comment]
@bontric your fix seems to work. I will test when I get home tonight. Thanks!
