### ISSUE TITLE
Module compiled from last source compatible with 0.5.0?

### ISSUE THREAD

**Issue by HoRaMusic** [VCVRack/Rack#359]
All is in the title, I wonder if modules compiled from the last sources will be compatible with 0.5.0 or if there will be some API updates before the release?

Thanks

**Comment by AndrewBelt** [comment]
Probably not, don't bet on it. If you take a look at the v0.5 milestone, some of those issues may mean API changes.

**Comment by antoniograzioli** [comment]
DO you mean "3rd Party Modules"? 
3rd Party Modules need quite some work to be ported from v.040 to v.050 
Many developers (me included, but not in the github Sources) have already updated their modules and will probably release new versions after Rack 0.5 becomes available...

**Comment by Strum** [comment]
@antoniograzioli , i tried building your modules yesterday and they hadn't been updated for the new api changes

**Comment by antoniograzioli** [comment]
^^ That's exactly what I said...I'll reword it: OI have already updated but not yet published on my gitHub repo

However I just realized that @rafzael was probably asking if between now and the release of 050 ther'll be other API Changes...

**Comment by Strum** [comment]
@antoniograzioli oh ok, are you going to push the changes soon?

I updated mine yesterday.

**Comment by antoniograzioli** [comment]
@Strum : I 'm not sure, because some new modules use other libraries, samples, and it' quite a mess at the moment to keep different versions aligned (dev + current), different libraries updated at the same time.

To be honest publishing sources takes a lot of time that I need to sacrifice from developing new stuff, so I will focus more on development and less on updating sources. Most of my sources can work with little effort on other peoples part and are already examples of what can be done in Rack if somebody wants to hack on them.

**Comment by Strum** [comment]
@antoniograzioli My strategy is going to be as follows : binary releases to run with current release, code to keep pace with dev version and i'll keep backup copies of the code used to build the release versions so people can make other builds if need be.

**Comment by modlfo** [comment]
I'm closing this issue since it seems outdated.
