### ISSUE TITLE
MPE to CV interface

### ISSUE THREAD

**Issue by kevinloustau** [VCVRack/Rack#380]
Would be great to have MPE to CV interface.

**Comment by Ahornberg** [comment]
taken from https://support.roli.com/article/what-is-mpe/
[cite]
When a device is transmitting MIDI according to MPE, it will use a range of channels:

The lowest channel (usually Channel 1) is used for global messages – data such as preset changes and pedal positions are transmitted on this channel to apply to all notes equally.

The remaining channels (usually Channels 2–16) are used to transmit notes and expressive data on a note-per-channel basis – this data will only apply to the note which is on the same channel.
[/cite]
So the best workaround is to use the number of MIDI to CV modules +1 that matches the polyphony in your patch and set each one to ascending MIDI channels. Personally I think that there's not really a need for a special MPE to CV module.

**Comment by AndrewBelt** [comment]
Same, I don't see the need for this in Rack over the normal MIDI interfaces. Comment if you have an argument against.

**Comment by bafonso** [comment]
There are several reasons why an MPE to CV would be useful:

1) MPE devices like the continuum use channel pressure instead of note aftertouch
2) They don't use Mod/Pitch wheel but instead a variable amount assigned to a "pitch wheel signal". i.e, you can set their range to anywhere from 1 to 96 semitones. 
3) You normally need use also the Y axis to send another CC (typically 74). 

I was planning on adapting first the MIDI to CV module to take this into account but let me know if you'd like to do it yourself.

**Comment by AndrewBelt** [comment]
Will consider it, but I don't (think I) have a device which supports this on hand, so it might be years from now.

**Comment by bafonso** [comment]
I understand that Andrew, not many MPE controllers out there yet! Since I have a continuum I am selfishly interested in this ;-) I will try to adapt your MIDI to CV to create an MPE to CV module. Let me know if there's any recommendations you'd like me to follow. I've only looked at VCV code once a few days after you went public with it :)

**Comment by AndrewBelt** [comment]
Keep in mind that I only release code which I can test.

**Comment by bafonso** [comment]
Hi Andrew, I'll be happy using it for myself and whoever wants to. We MPE people are used to being marginalized ;)

I have a preliminary plugin module that automatically parses the pitchbend and incorporates it into the V/oct (it will be a option/toggle eventually) and immediately noticed some stepping while transversing the scale on the continuum. After some research I realized that the current code only registers the coarse level of the pitch bend thus giving you a low resolution of the pitch bend signal. I will fix this, it's a minor change you can integrate into your code straightforwardly. I also disabled the smoothing, the constants are off if you want to use vibrato for example. Why did the smoothing get implemented, I've not come across it in other programs... Was it because you heard the stepping due to the low resolution parsing ?

I thought I'd also ask if there are any plans to give modules access to the midi IO code in core. I had to copy the MidiIO.xxx in order to use it in my plugin which I believe will "pollute" the namespace; I couldn't add a new menu dropdown for example because it wouldn't find the symbol. I hope this makes sense, I'm no C++ expert.

Thanks for creating VCVRack, it's grown quite nicely. There's some unique about the interface that is nicer than other similar software!

**Comment by Ahornberg** [comment]
I agree, smoothing MIDI values by default is not a goo idea. If someone wants a smoothed PitchBend there are already modules for doing that. And PitchBend should be provided in full 14 bits range. Not only MPE users rely on that, microtonalists do too.

**Comment by bafonso** [comment]
Hi @AndrewBelt , I switched to master branch so that my module would be future compatible and I see that only MidiToCV module shows up (others have been commented out). I guess this is because you are in the middle of making some changes. I could not get any signal out of the module even though console debug shows the midi. Let me know if you'd like any help on these modules.

**Comment by dllmusic** [comment]
I have an MIDI MPE module planned.. will make it after 0.6 is out. I have a Continuum so I can test it.

**Comment by danpetry** [comment]
Hi there, just found this thread. As it happens, I'm doing a module for the Roli Seaboards. I'm going to adapt the Quad MIDI to CV to add a) more notes and b) the extra signals that are sent from the Seaboard, compared to the QM2CV. My repo's [here](https://github.com/danpetry/Roli), would be good to compare notes!

**Comment by AndrewBelt** [comment]
Added in https://github.com/VCVRack/Rack/commit/65a93ae5862e7d429d1276ad5b31662aa397557c
