### ISSUE TITLE
Core/Fundamental Modules have missing/incomplete "Description" metadata

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/Rack#445]
<img width="1552" alt="screen shot 2017-11-24 at 10 13 13 am" src="https://user-images.githubusercontent.com/139987/33216118-8ae1cc52-d100-11e7-8b23-9074b2ef25f4.png">
In .5, there's a new interfacing for adding modules to the active Rack. In this new UI element, there is a 'metadata' area for showing information about what the module is. Unfortunately, it seems like this area is incomplete for most (all?) of the default/fundamental modules.

For instance, hovering over LFO-1 and LFO-2 both have the title of `LFO`, and there is no information about what the module is, or how LFO-1 and LFO-2 are different.

Since we have this new UI area to use, it'd really handy if we could provide the user with a useful description of the selected module in this area.

**Comment by AndrewBelt** [comment]
That's where the tags are listed. "LFO" is the tag of the module "Fundamental LFO-1".

**Comment by Miserlou** [comment]
Okay,  but stilil - why not have some description information?

I would suggest that every module have something like a `manifest.json` with name, description, authorship, link, compatible versions, compatible OSes, etc. Then we can display descriptions on hover here in addition to the tags. Currently it's all a mystery.

**Comment by AndrewBelt** [comment]
This is a design issue and will be handled by me and my graphic designer once we make sweeping changes to the UI in a later version.

>manifest.json
No, everything should be compiled into the `plugin.so/dylib/dll` file. See https://github.com/VCVRack/Rack/blob/master/include/plugin.hpp

**Comment by Miserlou** [comment]
Ah, there it is. Still, it doesn't look like the `plugin.hpp` allows for a detailed description field?

**Comment by AndrewBelt** [comment]
That could be a possible feature. But it's hard enough getting plugin developers to write documentation, so only a few will actually fill that out and it'll look out of place on the ones that do. So I'm opting for minimal metadata just to cover enough to search and create categories of tags.

**Comment by Miserlou** [comment]
I don't think it's bad to have some be more usefully descriptive on some because others will look "out of place". This stuff is still pretty obtuse for new users so I think doing anything that helps usability would be a win.

And, while I'm at it, I do want to make a plea for _non-compiled_ package metadata. The whole point of metadata is to see what's _inside_ a package. For example, if you have a module which depends on a specific Rack version, the only way to know which version it is compiled for is to load it, which could cause unexpected behavior, which is potentially dangerous to the state/system. The same goes for architecture information. 

Similarly, it's also more complicated for package management systems to deal with compiled information, which then creates an external dependency for the meta information, (likely in a database on a private web service, which is obviously non-optimal). 

So, I'd strongly suggest moving away from compiled package metadata sooner rather than later. I'm trying to think of any package management systems which use compiled metadata and I can't think of anything, so I think this is probably why. Just my two cents, but since this is a modular ecosystem with multiple versions and architectures, I think it makes sense to use non-compiled metadata.

**Comment by AndrewBelt** [comment]
Since the package manager will be built into Rack, it is easiest to use self-contained metadata. It's simply a matter of

```cpp
Plugin *plugin = new Plugin();
initCallback(plugin);
debug("%s", plugin->description);
etc```

to extract metadata from plugins. Any plugins that fail to load because of ABI compatibility are considered "ABI incompatible" by the plugin loader and are then updated.

**Comment by AndrewBelt** [comment]
Okay, you brought up an important issue, which I *think* will be okay, but I just want to put it in words because I want to make sure the future of plugins have no fundamental problems.

I want to avoid an external file for metadata, so I think everything should go in the plugin.dll/dylib/so files. If a user clicks "Refresh Plugins" in Rack, it asks the server for a list of plugins. If a plugin is present in the list but not loaded into Rack, it will download the plugin from the server given its name. Simple as that.

I need to rewrite the API client code to support plugin versions. If the server says the latest version of a plugin is not equal to the version string in `plugin->version`, it will download and unzip the new plugin. It will not unload the old plugin library from memory since doing that is a nasty problem---it will simply recommend the user to restart Rack.

I don't wish to support old versions of Rack at all. My support ends the minute I release a new version. Instead of making a service to support old versions of Rack, I will make a service to provide the best backwards compatibility of patches as possible for new Rack versions.

Any thoughts or issues you see with this? I think this update process is mostly flawless but very simple.
