### ISSUE TITLE
Fonts and SVG rendering: current state and possible improvements

### ISSUE THREAD

**Issue by LOGUNIVPM** [VCVRack/Rack#472]
At the moment it seems to me (please correct me if I'm wrong) that the SVG rendering in Rack does not allow for:
- fonts (they must be casted to paths)
- blurs
- filters and effects (e.g. in the fill of a square shape)
- rasters

Is that correct? If so I'd be glad to ask for a feature request, especially for the fonts.

**Comment by AndrewBelt** [comment]
- Font filenames and font names need to be defined and stored somewhere. As far as nanovg is concerned, filenames and names are unrelated. Would need to be added to nanosvg, which is about 10x more work than I personally value this feature.
- nanovg doesn't support these, so you'd need to contribute a shader to the project. But actually, since Rack uses OpenGL 2, I don't think you can do this at all.
- Be more specific? Remember, OpenGL 2 doesn't support shaders, so even with a nanovg modification, that wouldn't work in Rack. If you mean an `nvgImagePattern` or `nvg*Gradient`, that can be supported, but there needs to be a natural mapping from the SVG format to those fill/stroke styles.
- Loading an image would also need to be defined somehow. Would require a nanosvg modification.

**Comment by Dewb** [comment]
Rasters in SVGs are probably an undesirable feature for high-DPI displays. The SVG modules look so much better than the image-based ones on Retina or high-DPI Windows machines.

Also it's always easier to do things once during development (like converting fonts to paths, or rasters to vectors) than doing them at runtime on user machines!

**Comment by AndrewBelt** [comment]
Rack's SVG renderer will never support the features proposed in this issue, closing.
