### ISSUE TITLE
MIDI CC in via IAC not working

### ISSUE THREAD

**Issue by pure-github** [VCVRack/Rack#480]
OS: OSX 10.8.5; Rack 0.5
module: "MIDI CC to CV": when using an IAC Port to receive cc's the module shows that it receives the data (through the red LED) but it doesn't output anything. Tested with Ableton Live and Max.
Using the Modulation wheel (CC1) on a MIDI keyboard connected via usb works.

**Comment by bontric** [comment]
The red LED shows that your controller is out of sync with the Modules output value. You can read the instructions for the Midi Modules here:

https://github.com/VCVRack/Rack/wiki/MIDI-Modules

**Comment by pure-github** [comment]
Thanks. So turning the knob to "re-sync" Rack is what is also known as "pick-up mode" - the value coming from outside must meet the value stored once to re-connect? 
If so I can picture one problem with this situation: Say the internally stored value is 100. The cc-values are coming from an automation from any DAW and lie between 0 and 99. Rack can never reconnect. Each automation (envelope) would have to be changed manually to the value stored in Rack so it can reconnect and would listen to the MIDI automation. This would mess severely with carefully built automations.

**Comment by bontric** [comment]
>  So turning the knob to "re-sync" Rack is what is also known as "pick-up mode" - the value coming from outside must meet the value stored once to re-connect?

Yes exactly

> If so I can picture one problem with this situation: Say the internally stored value is 100. The cc-values are coming from an automation from any DAW and lie between 0 and 99. Rack can never reconnect. Each automation (envelope) would have to be changed manually to the value stored in Rack so it can reconnect and would listen to the MIDI automation. This would mess severely with carefully built automations.

You are right, there should be an option to force the outputs "in-sync" (So that the incoming value overrides whatever the current value is). While there is no explicit option to do this, there is "workaround" which might work for you now. If you initalise the module (right click on module -> initialize) , all values are set to 0. However, you'll still need to send a 0 value first to get them back in sync.

In the future, I'd suggest we add a menu item which allows you to force overwrite the value (So no matter what the output value is, the midi input value is preferred). This is only a few lines of code, so I'd rather include that with another midi related PR I have planned for the future. (There are sill some minor bugs/ misbehavior which need fixing and I'll have to see when I have time to approach those )

**Comment by Triscus** [comment]
Did the behavior changed in 0.6? For my setup it would be very useful to have a 'pick-up-mode'.

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
