### ISSUE TITLE
Suggestion: View modules by type.

### ISSUE THREAD

**Issue by Chaircrusher** [VCVRack/Rack#482]
OS (if applicable): all
Version (or "dev" if compiling from source): 0.50

New user of VCV -- don't know how I missed it: Long time Reaktor Hacker, Max/MSP dabbler.

The biggest obstacle I have at this point is that I don't know all the module collections well.

What would help me would be an alternate view in the insert plugin dialog:

Instead of the top level category being by Developer (i.e. per-plugin DLL/SO/DYLIB), make the top level category be plugin type.  The plugins all have a type that shows when you click on it in the dialog -- why not have all of the types show up on the left hand side of the dialog?

That way if you're looking for a Sequencer, or an LFO, or an oscillator, you click a category,  the middle column of the dialog is the manufacter, the rightmost column is all the modules in that category.

You learn over time what different modules are good for but for basic patch building you know you want an LFO, you know you want an oscillator, you know you want a waveshaper, etc.

**Comment by heavydetail** [comment]
I replied on FB too. You can enter OSC or LFO etc and it will show you those that have those tags, but you still have to go through the manufacturers.

I also think the module picker is not optimal, I'd prefer a searchable sidebar (that can be open or hidden) with favorites and groups switchable to a list of all tags and associated modules instead of this dialog. I have limited experience with blendish etc but might be able to implement this once I have everything set up.

**Comment by Dultzo** [comment]
+1

**Comment by AndrewBelt** [comment]
Fixed a while ago with the Module Browser in Rack 0.6.
