### ISSUE TITLE
Rotary encoders

### ISSUE THREAD

**Issue by jhoar** [VCVRack/Rack#522]
It would be useful to have rotary encoders in VCVRack; the output being the value for one complete clockwise rotation, negated (i.e. symmetrical) for anti-clockwise rotation.

createParam<Encoder>(Vec(x, y), module, PARAM, 10.0); 
params[PARAM].value; // return angular rotation in one step, scaled according to Encoder definition

i.e. 1 full rotation in 1 step returns 10.0

**Comment by AndrewBelt** [comment]
I've thought about this too. Perhaps the best method is to simply allow a knob min/max of -inf to inf and just use delta values in the audio engine. Their `toJson` and `fromJson` function would just set/get 0.0 as their value.

**Comment by AndrewBelt** [comment]
Added some level of support in 3e5890b.
To create a continuous encoder, set the min/max values to INFINITY.
To read a change of value, simply compare it with the last value to get the delta value.
The absolute value is serialized with `toJson()`, so make sure you have a sane initial state in your `step()` code so you don't get a thousand-value jump in the second call to `step()`.
The user can scroll several million times before the knob value loses too much precision. By this point, it would have already beaten hard pots, since they are only rated for a few hundred thousand cycles.

**Comment by MarcBoule** [comment]
I am trying to create a continuous encoder with the -INFINITY, +INFINITY technique described above, and with the delta method and the other tips (absolute value), I belive I will get it to work. Two questions:
1) Is this still the method that is recommended, or has something else been added to support continuous encoders since then? (Github search didn't reveal anything)
2) When using the technique in question, the knob doesn't turn, so the feel is not genuine. Is there a trick here that can be used to make the knobs turn?
Thanks for any info on this!

**Comment by MarcBoule** [comment]
All good; tested and it works perfectly. Thanks for the update!
