### ISSUE TITLE
JACK fail in Rack-master

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Rack#601]
Linux Fedora 23
dev (master branch)

Hi Andrew ! Building the master branch, hit this familiar error : 

Failed to open audio stream: RtApiJack::probeDeviceOpen: the requested sample rate (44100) is different than the JACK server rate (48000).

Here's what it looks like in Rack. I can select Jack and the block size, but I can't select the device (it stays stuck on No Device) nor is there a sample rate to choose from. 
![jack-fail-rack-master](https://user-images.githubusercontent.com/7815938/34650856-b48af9cc-f395-11e7-8d76-5300c7bfbabe.png)

**Comment by ndrspcfd** [comment]
Same here with a fresh checkout of Rack master and the rtaudio/jack procedure as per the wiki page.

The issue seems to be that the open stream request for jack devices should specify the jack service's sample rate, but the code hasn't determined that by the time it calls `stream->openStream()`.

Before the move to audio.cpp, `deviceInfo.sampleRates` was used to find a sample rate for the `openStream()` call, but that code has been removed.

The following diff puts it back, and with it I'm able to hear sounds via my 48k jackd (no more tested than that!) however on quitting with ctl-Q Rack hangs after `[debug] Stopping audio stream 0` and needs a ctl-c from the shell to actually go away (running with `LD_LIBRARY_PATH=dep/lib ./Rack`)

It's almost certainly not the right fix, but may be a workable stopgap if you need to run master with jack..

```
diff --git a/src/audio.cpp b/src/audio.cpp
index 10c3c8d..90844d7 100644
--- a/src/audio.cpp
+++ b/src/audio.cpp
@@ -129,13 +129,19 @@ void AudioIO::openStream() {
 
                RtAudio::StreamOptions options;
                // options.flags |= RTAUDIO_SCHEDULE_REALTIME;
+               unsigned int closestSampleRate = 0;
+               for (unsigned int sr : deviceInfo.sampleRates) {
+                       if (fabsf(sr - sampleRate) < fabsf(closestSampleRate - sampleRate)) {
+                               closestSampleRate = sr;
+                       }
+               }
 
                try {
-                       debug("Opening audio stream %d", device);
+                       debug("Opening audio stream %d, samplerate %u", device, closestSampleRate);
                        stream->openStream(
                                numOutputs == 0 ? NULL : &outParameters,
                                numInputs == 0 ? NULL : &inParameters,
-                               RTAUDIO_FLOAT32, sampleRate, (unsigned int*) &blockSize, &rtCallback, this, &options, NULL);
+                               RTAUDIO_FLOAT32, closestSampleRate, (unsigned int*) &blockSize, &rtCallback, this, &options, NULL);
                }
                catch (RtAudioError &e) {
                        warn("Failed to open audio stream: %s", e.what());
```

**Comment by davephillips** [comment]
Thank you, I have audio from Rack-master. As you say, it requires Ctrl-C to actually quit but I can bear that until Andrew provides an official fix. Again, thanks for this. :)

**Comment by ndrspcfd** [comment]
You're welcome of course :) I see the latest commit to master fixes in the same way. The quitting-by-ctrl-C issue can be fixed by reverting the other part of https://github.com/VCVRack/Rack/commit/144de3943c96f617ad7e70d8ba0a9936cd0d1f52 if it becomes a problem, I have found.

Thanks are especially due to our gracious host in view of [not officially supporting jack](https://github.com/VCVRack/Rack/issues/82#issuecomment-345920323) right now :) And having read that thread, the reasoning seems clear even if the consequences are unfortunate.

I sort of wonder if the "simplest" solution to the underlying problem might be to provide linux users with both a with-jack and a without-jack build in some form and have them choose between them either at download or run-time. It seems on the money that avoiding automating this choice for a single-build download is a big win in the struggle against code complexity!

I do admit I'm kind of surprised at the idea that there are linux vcvrack users who wouldn't want jack installed (I've had too much fun with patches that pipe in audio from the browser running youtube videos on autoplay, via pulse sink and the carla patchbay, for just one example!) but there's no debating tastes..

**Comment by AndrewBelt** [comment]
Closing as possibly obsolete.
