### ISSUE TITLE
Feature Request: Show modulated parameter values

### ISSUE THREAD

**Issue by simonlast** [VCVRack/Rack#603]
It would be really helpful to show the value of a modulated parameter, sort of like Reaktor (LP and RES being modulated):
![image](https://user-images.githubusercontent.com/1704018/34655337-97f9f00c-f3bc-11e7-8d43-7fc9b28c7d6d.png)

**Comment by AndrewBelt** [comment]
There's no reason a plugin developer can't do this right now. They'd just need to make a Widget subclass which draws an indicator based on an internal value.

It doesn't make sense to automatically do this, because CV inputs don't modify parameters---they are just inputs. Each module `step()` function is in charge of adding of multiplying these inputs to the parameter value, and it might not correspond to a possible position of a knob.
