### ISSUE TITLE
Midi Clock Input Query

### ISSUE THREAD

**Issue by LazyPike** [VCVRack/Rack#61]
Hi there,

Firstly, may I just say that I Love the Rack - it's the perfect introduction to Modular Synthesis...a real gateway drug ; )

Anyway, I've been trying to receive a midi clock message via my hardware and have been failing. I know the midi clock message is being sent as I have checked it using Reason.

I'm obviously new to modular synthesis so it's highly likely that I'm doing something wrong.

My Rack is set-up like this to receive the midi message:

MIDI Device (Core Midi: MIDISPORT Input A) > SEQ-3 (EXT CLK)

= no indication that a timecode is being received.

Any advice?

FYI - I'm running Rack on Mac OS X 10.11.6

Cheers

**Comment by oblivionratula** [comment]
I think you may be confusing MIDI Clock w/ CV/modular 'clocking.'  

- The SEQ-3 (EXT CLK) is expecting a gate (or trigger?) signal in order to step the sequencer. 
- MIDI Clock is a signal (MIDI message, not the same as a gate) 24 pulses per quarter note. 
- To use MIDI Clock to drive the seq, the MIDI Device would need to convert MIDI Clock to x number of gates per quarter note.  It does not currently do this. 
- If, instead of expecting to use clock, you send, say, a repeating quarter note (or drum hit, or whatever) to you MIDISPORT, and connect the MIDI Device Gate output to the SEQ-3 EXT CLK, then it should drive the sequencer (assuming MIDI Device is set to the proper, or "Any," channel). 

HTH, someone please correct any mistakes.

**Comment by LazyPike** [comment]
You sir, are a don.

I've taken a midi signal from my shitty Rhythm Wolf and i'm now getting the desired outcome.

Thank you kindly for your direction.

**Comment by synthi** [comment]
Anyway would be great having a MIDIclock input module with subdivisions on different outputs for firing envs, seq, ....

**Comment by oblivionratula** [comment]
synthi, I agree, though I believe that's a different "Issue."

**Comment by bontric** [comment]
Midi clock is now available on the master branch and will be available with the next release :wink:

**Comment by AndrewBelt** [comment]
Since Rack v0.5 or v0.6 or so, MIDI-CV can convert MIDI clock messages to clock gates.
