### ISSUE TITLE
Rack Does Not Open On OS X 10.7.5

### ISSUE THREAD

**Issue by ghost** [VCVRack/Rack#627]
OS (if applicable): OS X 10.7.5
Version (or "dev" if compiling from source): 0.5.1

Greetings!

This is my first post on GitHub.

Just learned about Rack and got excited! I downloaded it to my computer and does not open at all.

When I click Rack to open it a pop-up window appears saying me that Rack needs OpenGL 2 and should update my GPU's drivers. 

My graphic card supports OpenGL 1.4.

Is there a way to open Rack on OS X 10.7.5 with Intel GMA 950 64MB GPU?

Thanks in advance!

Theodore.

**Comment by AndrewBelt** [comment]
No, you need OpenGL 2 support as the message said.

**Comment by GiveMeAnthony** [comment]
OpenGL 1.x used a fixed function pipeline to render graphics. Beginning with OpenGL 2, shaders were introduced so that the graphics pipeline was more programmable. The fixed function pipeline, know known as Legacy OpenGL, was deprecated with OpenGL 3. New software pretty much always uses the programmable pipeline now because of its flexibility. Anyways, the earliest Macbook to support OpenGL 2 was the Late 2007 (Santa Rosa) Macbook 3,1 which featured an Intel GMA X3100.

**Comment by TheodoreKontonis** [comment]
Hi guys!

Thank you very much for your replies!
