### ISSUE TITLE
Module screenshot preview

### ISSUE THREAD

**Issue by jaffasplaffa** [VCVRack/Rack#642]
Hello Andrew!

When looking for objects in the ever growing library it can be a bit hard to find what one is looking for. 

But I think it would make it a bit easier for the end user to find his way around the library i there was pictures included in the module browser. 

So my suggestion is: 
- Add pictures of each module to the module browser.

**Comment by AndrewBelt** [comment]
There are two ways of doing this, and both of them aren't satisfactory, so I believe this feature is not worth it.

### PNG in `res/`
- "Why does this module have a screenshot and this one doesn't?" Because it requires additional developer work, which some developers skip.
- "Why does the module look different?" Because the screenshot is out of date.
- "Why does the screenshot look blurry?" Because your DPI is higher than the plugin developers' when the screenshot was taken.

### Dynamically draw module
- Requires to instantiate the `ModuleWidget` but not the `Module`.
- ModuleWidget children might require the Module to be active to be able to draw. For example, the state of an LED screen might rely on the Module, like Audible Instruments Braids. (Not too much of a problem. The screen could be blank, so the screenshot would show the powered off state essentially.)
- It might be slow since it needs to load all graphics from the disk to show the preview.

**Comment by jaffasplaffa** [comment]
Hey Andrew!

Thank you for the rapport. I fully understand. I just thought that if it was easy to implement and would not cause any strain on load times, it could have been nice to see the modules before loading them.

Jakob

**Comment by grinsted** [comment]
In reason 9+ they have a button for taking a screenshot of vst plugins. Something similar could be added to the context menu in VCV rack. That would not require extra work from plugin devs.

**Comment by AndrewBelt** [comment]
@grinsted How would that be easier to developers than using their native OS screenshot function?

**Comment by grinsted** [comment]
Because it is the user who takes the screenshot, not the developer. :-) 

Here's a promo video from propellerheads showing how it works in reason 9. https://youtu.be/2Zy3RipH5u0?t=1m32s

**Comment by AndrewBelt** [comment]
Oh, I see what you mean.

Overall, raster images are a horrible method. Because of the separation of `ModuleWidget` and `Module`, it may be possible in the future, but I won't start thinking about it until post 1.0.

**Comment by modlfo** [comment]
Closing this issue since it will be available in Rack v1.
