### ISSUE TITLE
Suggestiopn: _TAG

### ISSUE THREAD

**Issue by LKHSogpit** [VCVRack/Rack#653]
OS (if applicable):win 7
Version (or "dev" if compiling from source): dev

Commented on FB about tags and saw the tags are in the plugin.cpp is it possible to add your own tags for your .dll or do they have to be added to the master.

Searching by HP# might be a nice tag especially for blanks. From a development point if you want to see what other modules of the same pixel size look like it be a nice tag. Also if you have multiple blanks from 1-10 you can quickly count the holes in the rail and select which blank would fit there instead of moving all modules to fit the blank. 

I plan on making all sized blanks or a few different ones anyway to see what the GUI of an .svg will look like in rack when working on a module. It is quicker to paste or save the .svg changes to /res and open v0.5.1 instead of make run. Can change save and open for each change to the svg. Unless there is a way to reload /res in the dev build without doing make run again.

**Comment by AndrewBelt** [comment]
No to custom tags, that would get messy. You can suggest specific tags for the v0.6 release though, but the current tags are mostly stable as it is.

Sorting by HP size seems really niche. Since Core Blank is resizable, it wouldn't be useful. Using non-Core blanks is strictly for appearance and shouldn't be focused on at any point.
