### ISSUE TITLE
[Feature Request] Collapsible rows

### ISSUE THREAD

**Issue by markireland** [VCVRack/Rack#660]
Collapsible rows: a simple triangle graphic that points down when a row is collapsed and points to the right when the row is not collapsed

**Comment by AndrewBelt** [comment]
Interesting.

**Comment by bafonso** [comment]
How do you envision dealing with the cables @markireland  ?

**Comment by gbrandt1** [comment]
for real racks cut out 1HU panels (also with brush strips) exist to feed cables to the back - could use an image of one of those

**Comment by LKHSogpit** [comment]
The way Reason implements collapsing devices is very nice. GW-Modules implement the stretch feature, could come into play with a collapsible arrow would be a nice feature.

I submitted a feature request a while ago which is still open so I assume it is open for discussion. The idea is kind of borrowed from Reason having a rack inside rack #579. Like the combinator device. That has a cut out for cables when collapsed. If I recall correctly the combinator in reason is based off an IRL device can't for the life of me remember what it is based off. Linking the two because of the collapsible arrow in Reason.

Just to revise that idea:
You can have an seemingly infinite amount of space in VCV so what if instead of a rack in rack have a patchbay style device with parameters which is more or less the same thing as what a combinator does. A patch bay device could link parameters and you could hard wire the device or not. Turn a rotary on the patchbay the knob on the patched device turns, link another device to the same knob on the PB that turns, scale that other knob so it only turns to 0.45° or 50% whatever now you control 2 devices. Think its json that makes a devices turn with midi cc. Would there be need to make the master knob turn with the slave knob? If it is off screen probably not but it would be handy to see where to scale to. Having control on devices way down the rack would be fairly handy. Currently the device needs have a mod input in order to control the param with midi cc. If there was a patchbay style device with rotaries you could link the params that do not have a mod IN to the patchbay and control that knob with midi cc. Would be a great workflow enhancement. Would it need ins and outs for that matter if you are just linking params to one knob you set and forget about the master device. More space less time. Maybe if it had ins out you could use it as an aux bus also... Just thinking out loud.

**Comment by markireland** [comment]
Keep it simple I think. The collapsed row shows a coloured circle for each cable. I suppose the title of each module might be visible?

**Comment by AndrewBelt** [comment]
Decided against this. Too unnatural/weird/pointless to be worth the 4 hours of time.
