### ISSUE TITLE
Stuttering sound after switching between applications on Ubuntu 16.04

### ISSUE THREAD

**Issue by lysigk** [VCVRack/Rack#667]
OS (if applicable): Ubuntu 16.04 64bit
Version (or "dev" if compiling from source): 0.5.1 - build & dev (with JACK-support)

When switching between Rack and another application (for example Google Chrome), the sound starts stuttering after a few seconds.

Most of the times there seem to be small gaps between chunks of audio, making it sound like slowing down the whole playback in a very choppy way. The terminal from which Rack was started shows the following error message:

`Jack: JackClient::ClientNotify ref = 7 name = RtApiJack notify = 3
Jack: JackClient::kXRunCallback`

QjackCtl is printing the following message:

`Thu Feb  1 15:14:39 2018: Jack: Process: graph not finished!
Thu Feb  1 15:14:39 2018: Jack: Process: waiting to switch delta = 23003
Thu Feb  1 15:14:39 2018: ERROR: JackEngine::XRun: client = RtApiJack was not finished, state = Running
Thu Feb  1 15:14:39 2018: ERROR: JackAudioDriver::ProcessGraphAsyncMaster: Process error
Thu Feb  1 15:14:39 2018: Jack: JackSocketServerChannel::Execute : fPollTable i = 1 fd = 10
Thu Feb  1 15:14:39 2018: Jack: JackRequest::Notification
Thu Feb  1 15:14:39 2018: Jack: JackEngine::ClientNotify: no callback for notification = 3
Thu Feb  1 15:14:39 2018: Jack: JackEngine::ClientNotify: no callback for notification = 3
Thu Feb  1 15:14:39 2018: Jack: JackClient::ClientNotify ref = 2 name = dbusapi notify = 3
Thu Feb  1 15:14:39 2018: Jack: JackClient::kXRunCallback
Thu Feb  1 15:14:39 2018: Jack: JackEngine::ClientNotify: no callback for notification = 3
Thu Feb  1 15:14:39 2018: Jack: JackEngine::ClientNotify: no callback for notification = 3
Thu Feb  1 15:14:39 2018: Jack: JackExternalClient::ClientNotify ref = 5 client = qjackctl name = qjackctl notify = 3
Thu Feb  1 15:14:39 2018: Jack: JackEngine::ClientNotify: no callback for notification = 3
Thu Feb  1 15:14:39 2018: Jack: JackExternalClient::ClientNotify ref = 7 client = RtApiJack name = RtApiJack notify = 3
Thu Feb  1 15:14:39 2018: Jack: JackSocketServerChannel::Execute : fPollTable i = 2 fd = 11
Thu Feb  1 15:14:39 2018: Jack: JackSocketServerChannel::Execute : fPollTable i = 3 fd = 13
Thu Feb  1 15:14:39 2018: Jack: JackSocketServerChannel::Execute : fPollTable i = 4 fd = 15
Thu Feb  1 15:14:39 2018: Jack: JackSocketServerChannel::Execute : fPollTable i = 5 fd = 17
Thu Feb  1 15:14:39 2018: Jack: JackSocketServerChannel::Execute : fPollTable i = 6 fd = 19`

Sometimes the sound seems to speed up instead, so the next "sound chunk" seems to get played back before the preceding one has finished. In those cases, the terminal output is:

`Jack: JackActivationCount::Signal value = 0 ref = 7`

Usually pausing and resuming the audio engine solves the issue, but sometimes JACK has to be restarted and now and then even a complete system reboot is necessary.

The problem ocurrs when using the downloaded build version with ALSA as well when using the dev version built with JACK support.

**Comment by danballance** [comment]
I'm experiencing this at times as well. Currently I think it's just the CPU getting stressed and causing overruns. Increasing latency will probably help I would imagine.

For me I am running Bitwig and Rack via Jack on Linux. As a test I stopped the audio being piped into Bitwig and switched browsers tabs in Chrome. I got the same pops and crackles. So this leads me to conclude there's nothing going wrong with the audio in Rack. If Rack is at fault at all then perhaps it's because it is quite resource hungry. I had quite a complex 4 x VCO patch running and I'm only on a 4 core / 12GB laptop.

Not sure if this is realistic or not, but I'm hoping when the VST Bridge becomes available that I can go back to just running ALSA in Bitwig and perhaps see some performance improvements like that.

**Comment by danballance** [comment]
Oh and BTW do be sure you are running your CPU in "performance" mode. That helps a lot too.

**Comment by lysigk** [comment]
Yes, I've done some more testing and I'm also quite sure now, that it's a performance issue.

However, it seems to be a Linux (maybe Ubuntu only?) specific problem, since Rack runs smoothly under Windows 10 on the same machine, even with more complex patches.

The stuttering sound also ocurrs when switching between applications under Windows, but the sound engine quickly "recovers" after a few seconds, while on Linux it just get's stuck.

**Comment by danballance** [comment]
This is pure guess work on my part but I wonder if the weak point is Jack? I've been getting excellent performance running Bitwig with ALSA. I've had to start using Jack in order to send audio and midi between Rack and Bitwig. Since doing that I'm starting to get some audio issues, just like yours, that seem to be performance related. My hope is that when the VST Bridge is ready (and stable) that things will improve.

**Comment by lysigk** [comment]
I'm getting these problems with both ALSA and Jack. Actually Jack seems to run a little better but not really stable enough to work with.

Maybe I'll try to get my hands on an external USB audio interface to check out if this could maybe help improving performance.

Oh, and as stated in [the official FAQ](https://vcvrack.com/manual/FAQ.html), stability and performance are some of the main points to be worked on until v1.0.

**Comment by modlfo** [comment]
Closing this issue. Audio related problems in Linux will be covered in #1317
