### ISSUE TITLE
Draw order of plugs and wires

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#680]
Would it be feasible to render all the plugs first, and then all the wires, when drawing the rack? As it is now, this kind of behavior can show up:
![image](https://user-images.githubusercontent.com/33604154/35771521-f1ebea62-08fb-11e8-9e9e-c03647c76b4e.png)
where the wires seem to pass beneath the plugs. Perhaps it was intentional in order to see the plug lights correctly, and if so, no problem. Trade offs are always part of the game :-)
(Apologies if this was raised before)

**Comment by AndrewBelt** [comment]
Actually if you look closely, the plugs have to be drawn over the wires so that the wires slip nicely under the plugs. Otherwise you have a hard edge in the center of the plug. That's why it hasn't been fixed, because I can't think of a way to do it.

**Comment by MarcBoule** [comment]
True, I hadn't considered that point. Interesting problem...

**Comment by cschol** [comment]
You could define the plug itself to be a "no cable zone" and try to draw around it, but I am not sure what other problems could arise from that. In the example above, the problem could be resolved in both cases with adjustment of individual cable length until the cable is not overlapping the plug anymore. In other cases though that might not be that easy.

**Comment by AndrewBelt** [comment]
That's "problem-solving by flailing".

**Comment by cschol** [comment]
I call it "ideation".

**Comment by AndrewBelt** [comment]
Not quite what you were talking about, but I can define rectangle "scissors" with NanoVG which restricts drawing to that area, but I don't think that helps in this case, since nothing can be restricted to just rectangles.

**Comment by cschol** [comment]
OK, I looked at the Rack and nanovg source and my idea does not seem as straight forward as I imagined.

I think the pros of the current implementation are that it is simple (in `Rack` and `nanovg`) while pretty robust and still 100% functional from a user perspective. It just potentially looks a little funny, as in physically impossible, depending on my module setup

I can adjust the cable tension for all cables and for simple setups fix it mostly that way. For more complex setups I could make it look nicer if I was able to adjust the cable tension individually, e.g. by dragging the cable itself.

I assume dragging the cable itself is not easy since I don't have "access" to the cable after it has been drawn. I do have access to the locations of input/output ports. Now, `SHIFT` plus `Left Mouse Click+Hold` and `Mouse up/down` could adjust the tension of the cable attached to that port. Individual cable tension could be an offset to global cable tension and stored in the patch file.

Just an idea. I am not convinced that it is worth it.

**Comment by AndrewBelt** [comment]
Let's focus on the problem at hand, not adding features here and there.

If we do some math on the bezier curves, you can split wires into three sections: the two wire ends, and the center ~90% of the wire. Although, even if the math is correct, there may be some pixel dirtiness at the points where they connect.

**Comment by cschol** [comment]
Interesting, the three segments.

Just for clarification, is this what you envision it to look like? (purple lines, a little sloppy)

![35771521-f1ebea62-08fb-11e8-9e9e-c03647c76b4e](https://user-images.githubusercontent.com/624427/35787871-9cdb72c4-09ee-11e8-8ca6-6477c1de8185.png)

Although, for the middle, yellow plug, the wire could also pass *above*, right?

What would the three section wire look like in this example?

**Comment by LKHSogpit** [comment]
To be honest I never noticed this until pointed out. Have been too busy listening to how it sounds to care! I'm okay with how it is, anyway there is only so much realism one needs.

**Comment by MarcBoule** [comment]
For the record, I've been playing around in Rack since october, and I also was surprised I hadn't noticed it before! A good sign I guess :-)

**Comment by MarcBoule** [comment]
Fixed in v1 (2cd29d62f065e8af52c4a205e01577d299a532b3), closing.
