### ISSUE TITLE
Is it considered bad form to "borrow" the look and feel of other modules?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#681]
I'd like my module to "fit in", so I'm tempted to "borrow" the Audible Illusions L&F. But that seem like theft of intellectual property, or something close to that that. On the other hand, these are the "Rogan" knobs from the ComponentLibrary, so clearly the intention is that developers re-use that part.

Guidance?

**Comment by AndrewBelt** [comment]
The Component Library are explicitly licensed as CC BY-NC 4.0 [(see license)](https://github.com/VCVRack/Rack#license), so you can use them in noncommercial plugins (ask us for commercial licenses).

The Audible Instruments panels are owned by Mutable Instruments, so derivations are likely not allowed without permission.

**Comment by LKHSogpit** [comment]
Have been meaning to start a discussion on this kind of thing. Cloning devices could spell disaster for Rack if using inspiration for devices without permission. How far is too far for making components and panels that are like hardware versions. It is one thing to get inspired by modules but entirely another ripping a module off. From a design point I was thinking of making a load of components that would not be like any devices, from screws to knobs and panels etc. Obviously the design of a screw is far game to an extent if the screw is a universal looking screw like what would be in a door hinge, can say nobody would probably get upset, but for example if you use a bafaco screw and change the colour or something then you are still using the design which is a unique screw befaco designed iirc. Using that as an example it is covered in the license, but if you designed a component outside the license to take on the look of a IRL device it could be trouble at worst but a waste of time for the designer a best.

What would be the procedure if a device clone slipped through. Obviously you would have to pull the device Andrew or request that the author of the module do so if requested that all references to their device be ceased. But just so everyone is on the same page it should be in the readme clearly so nobody has any grievances with the design of panels and components.

The component library is fine if you want that simplistic look of rack, but I know myself I'd like to have devices stand out and not blend in terms of design. Don't get me wrong the components work for rack and I'm neutral with how they look. Just so everyone does not get the headache of having to redesign a module because they did not get permission to use a design. There needs to be a clearer statement for that or it could be a can of worms for rack.

**Comment by AndrewBelt** [comment]
I've been very clear about the licenses of all IP that Grayscale and I create. If the license of a particular work allows derivations of a certain form, you can use it if you follow its guidelines. If not, then you need to find another way to obtain your resources.

For IP not owned by me or Grayscale, I'm not going to try to be anyone's lawyers or moral conscience, so that is for you to decide.

For modules on the Plugin Manager, it is very clear to me when a developer oversteps permission, and I will remove their listing in that case.

**Comment by LKHSogpit** [comment]
I was not asking that. I'm not your Lawyer either btw. What I talking about is using your own designed components, knobs and panels that may look like IRL components knobs and panels.

Scenario someone complains about the look of a panel. You request the panel be changed it is not changed. Being 3rd party all you can do is pull all .dll's  from the site. The owner of the panel design asks for the maker of a clone to change the design, It is not changed. Owner of the panel design can't get in touch with the person who designed the clone. The person who designed it is making money off it. Who do you think the owner of the design will turn to be compensated?

It is unlikely to happen exactly like that but it is not entirely improbable either.

**Comment by AndrewBelt** [comment]
>What I talking about is using your own designed components, knobs and panels that may look like IRL components knobs and panels.

Again, if you have the need to ask this question, you will need to answer it yourself, or seek legal advice.

>Who do you think the owner of the design will turn to be compensated?

The developer of the infringing plugin, obviously? I don't see your point.

**Comment by LKHSogpit** [comment]
Well actually you are completely misunderstanding my intentions. I am asking not for myself but for the rest of the community.

Whatever dude read what you want! I'm clean.

**Comment by AndrewBelt** [comment]
I understand your intentions and questions exactly. You are asking questions which either 1) have a clear legal answer, or 2) cannot be answered by me, since every IP holder has their own opinions about what is acceptable use.

> I'm clean.

Of course, I'm not accusing you specifically of anything. These are the same responses I'd give to anyone in the community.

**Comment by LKHSogpit** [comment]
I meant my conscious in clean. What I'm saying is if everyone knows what is or is not acceptable there won't be any need to pay someone, a lawyer to tell you what you already know. It is common sense but as you said others do have their own opinions of what is acceptable, if the guidelines were there it might sway their opinion of what would be overstepping the mark.

**Comment by AndrewBelt** [comment]
If you want a silver-bullet guideline, here it is: Ask permission before using others' intellectual property.

Closing.

**Comment by LKHSogpit** [comment]
Again I already now this. Others do not!
