### ISSUE TITLE
VCV freezes on launch after accidentally adding 2 audio interfaces (Windows)

### ISSUE THREAD

**Issue by zachThePerson** [VCVRack/Rack#697]
Windows
Version 0.5.1

I accidentally clicked and added a second audio interface, causing the software to freeze. I managed to hit the "delete" key and delete the second audio interface before the program _completely_ froze, but it didn't help.

I tried re-launching the program but it wants to re-open the same broken project and I have no idea how to tell it not to causing it to freeze the second it launches. 

**Fixed:** I went to the Rack folder in my documents and deleted the "autosave.vcv" files.

**Comment by Coirt** [comment]
This happened to me a few times also. It happens especially with WASAPI. My whole computer locked up when I tried to reproduce it. A couple of times task manager would not open either. It also happens when choosing ASIO and your soundcard and WASAPI and the driver for your soundcard together in the same rack.

I was looking to record an input in the dev version 0.5 when VCV froze. Using the same interface module is impossible with WASAPI as the ins/out are different devices. WASAPI or Direct are the only one's available for recording in OBS. Freeze happens in dev 0.5.0 and v0.5.1.

Using a focusrite 2i4 interface.
