### ISSUE TITLE
Hard coded macOS path

### ISSUE THREAD

**Issue by jsumners** [VCVRack/Rack#71]
https://github.com/VCVRack/Rack/blob/master/src/main.cpp#L79

I don't keep my downloaded, other than App Store (and really annoying ones), applications in `/Applications`. I keep them in `~/Applications` (yes, macOS recognizes this). I also organize my things. In particular, I installed Rack to `~/Applications/Music/VCV Rack`.

The application shouldn't care where it resides.

**Comment by AndrewBelt** [comment]
Because of App Translocation, I have to set its cwd as an absolute directory because there is no reliable way to get the path of the folder containing an app bundle. It can be set to Rack.app/Contents/Resources, but where do the autosave files and downloaded plugins go? The corrent answer is something like `~/Library/Application Support/VCV/`, but then I would have to change the way paths are loaded by making an `asset.hpp` file. So really, the solution of this Issue is to create `asset.hpp` with global functions `getRackPath("whatever.svg")`, `getPluginPath(plugin, "whatever.svg")`, and `getUserPath("settings.json")` or something.

**Comment by AndrewBelt** [comment]
#113 is a generalization of this issue, so closing this one.
