### ISSUE TITLE
error: call to 'abs' is ambiguous

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#713]
Some of my plugins use external libraries.
one of this library (Maximilian) makes use of a **abs** function
when trying to compile against the latest sources i get a "error: call to 'abs' is ambiguous"
probably because there's another abs function nwo defined here: https://github.com/VCVRack/Rack/blob/master/include/util/math.hpp#L274-L291

What can I do to avoid ambiguity? Shuold I refer calls to **abs** with its namespace or prefix it with ...what ???

**Comment by Coirt** [comment]
You have to include dependences in the source right? Would it be a solution to rename `abs` to `abs.d` in the dependency if its just a couple of lines to edit in the dependency this is probably what I would do.

Was wondering what abs stood for thanks for the post.

**Comment by AndrewBelt** [comment]
@antoniograzioli I'd suggest including your dependency before including Rack headers.

Should I rename `abs` to `absolute` in math.hpp?

**Comment by Coirt** [comment]
abso-lutly up to yourself.

**Comment by antoniograzioli** [comment]
@AndrewBelt , no, I could rename it in the library that includes it and rename all its occurences.
I have two functions with the same exact name that probably do exactly the same thing (probably slightly different signature)...
But if I could refer to them using something like "Myclass:abs", or even "Rack:abs" it would be perfect...

**Comment by AndrewBelt** [comment]
It depends on whether you want to call `int abs(int)` or `float abs(float)`, etc.

If `int` and you have control over the library, you can call `::abs(x)` or `std::abs(x)` (recommended).
If `float`, you can call `std::abs(x)` or `rack::abs(x)` although I believe I should remove this function now, because of these kinds of issues.
If you don't have control over the library (or if you do but don't want to change it), I don't see why my earlier suggestion doesn't work.

**Comment by antoniograzioli** [comment]
@AndrewBelt thanks, I moved the **#include "Maximilian/maximilian.cpp"** before anything else and that fixed the "ambigous" reference
