### ISSUE TITLE
0.6.0 conversion, custom context menu: GUI_MOD_KEY_NAME ?

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/Rack#737]
OS (if applicable): Windows
Version (or "dev" if compiling from source): 0.6.0dev

Hi,

I have a compile problem about "constant" (I suppose), existing in 0.5.1 API, but not in 0.6.0 (maybe renamed), concerning "createMenu" (for context-menu), the value indicated in bold isn't accepted:

cloneItem->rightText = **GUI_MOD_KEY_NAME** "+D";

This example concerns "Duplicate" context-menu entry, shortcut indicated/right aligned in menu entry.
But I can't find the equivalent in 0.6.0 API.

Thanks in advance for help.

**Comment by DomiKamu** [comment]
> oble

**Comment by AndrewBelt** [comment]
It's now called `WINDOW_MOD_KEY_NAME`. Why are you using that constant in your plugin though?

**Comment by DomiKamu** [comment]
Thanks for this immediate reply.

Because my modules have "limited" context-menus, eg blank plates need "Duplicate" and "Delete" only. Splitter also uses "Disconnect Cables". But others such Disconnect Cable for blank module is a nonsense IMO. This tip is working fine in all of my Ohmer Modules for v0.5.1.

**Comment by AndrewBelt** [comment]
I would strongly not recommend removing the default context menu entries.
You should append custom entries to this menu, not remove entries.

This may prompt me to make it harder to do this by making the `createContextMenu()` method `final` and adding another method which allows appending of an already-prepared menu. However, I have been against "protecting" developers from such hacking in the past.

**Comment by DomiKamu** [comment]
![limited context-menu](https://user-images.githubusercontent.com/24851960/36420507-98ba109e-1635-11e8-9b35-47638e4f3b14.png)

You want to limit more, why?

**Comment by AndrewBelt** [comment]
Users expect a level of consistency, this is basic UI design.
More importantly, if I change the default menu options, your plugin will no longer have a correct context menu.

**Comment by DomiKamu** [comment]
I'm C++ begineer (DSP environment too) I've hate C/C++ during many years (I'm Delphi developer since 22 years, however), now VCV Rack is a really a motivation to develop, but by reading this I'm discouraged, why, because you want to add code protection "anywhere" (here, about a simple context-menu). Ok assuming if you change something my menu will don't work, in this case I'll remove all-related context-menu code, easy aren't?

**Comment by DomiKamu** [comment]
...and  I presume users don't use Randomize or Disconnect Cable from a blank module, or Randomize on a simple multi. I agree about level consistency, and quality too, it's my goal.

**Comment by DomiKamu** [comment]
Sorry I forget to **thanks**, WINDOW_MOD_KEY_NAME works fine.

**Comment by AndrewBelt** [comment]
>but by reading this I'm discouraged, why, because you want to add code protection "anywhere" 

I am discouraged as well, because I have expected developers to follow best practices when designing plugins, so I have built an API that prefers flexibility and hackability over safe-gaurding. If developers make plugins which start modifying Rack behavior in weird ways, I'll be forced to add safegaurds, and API changes make it harder for everyone involved with this project.

I have added `void ModuleWidget::appendContextMenu(Menu *)` in my local branch (will push later) and am soft-deprecating `createContextMenu`. It will be removed in Rack 1.0.

**Comment by DomiKamu** [comment]
Don't worry, Andrew, I've understood since long time the discussion seems impossible with you when you can't admit you've wrong, Also I precise it's not the first time, simply remember about issue concerning Audible Instruments' modal synthesizer tagged as "Reverb" only: at your first thought, you've replied and stay on your position (but you've confirmed this at second, thought) and effect... Okay, be sure I don't complaint about VCV Rack because it's a free software, I precise I've removed all context-menus from my sources and the story ends.

However, I've opened, ten days ago, an another issue concerning... both Pulse Matrix 8 / 16 modules (issue #698), but strangely they're no news from you concerning this (paid) plugin.

About "best practices when designing plugins", I'm looking for a **detailled** API reference for VCV Rack, (don't tell about our "Tempate", is a joke), Be sure I'm sorry for my "rude" langage used here, I'm not an angry guy, but about best pratices I can assume I'm working like a professional (it's in my spirit), but you (always) think you've right (I can understand VCV Rack is your baby), but I think I'm right too in this case! QED.

**Comment by Dewb** [comment]
I fully support creating safeguards in the API so plugin developers can't get in trouble.

But I've also removed Randomize and Initialize from modules (e.g. the virtual monome grid) when there is no possible sensible implementation for those commands, and it seemed more user-friendly to not show them rather than let the user click them and then wonder what the point was. It might be a good idea to let modules set flags for whether some of these optional commands are not going to be implemented, so they could be grayed out or hidden.

**Comment by DomiKamu** [comment]
Hi Dewb, of course, a graying menu entry feature (handled by kind of bool flag) - to keep the same menu structure, but with (visible) disabled entry, of course this will be an excellent alternative, IMHO, I totally agree with this!

**Comment by AndrewBelt** [comment]
Yes, it may be a useful feature, but this issue should have gone "Could you add this feature to Rack?". Instead, now I have to convince all plugin developers to not attempt to extend the menu so that I might implement custom behavior in the first place, since I was not aware they were doing that.

>detailled API reference

Could you explain why the Javadoc-style comments don't suffice? These docs might be sparse, but they offer much more information than the Template.

**Comment by AndrewBelt** [comment]
Just thought I'd add: I don't care whatsoever what plugins do, behave, look, sound, etc. I just don't want people reporting issues for Rack when in fact it's a plugin's fault. Anything that steps outside the bounds of a plugin will be considered "Rack's fault", so I have to protect it accordingly.

**Comment by DomiKamu** [comment]
A plugin's fault, hack (you've used this word) for a public method. One word : lol

**Comment by AndrewBelt** [comment]
Sorry, I should have said "I have no preference whatsoever what plugins do"

**Comment by DomiKamu** [comment]
Okay, don't worry Andrew! :-)

**Comment by AndrewBelt** [comment]
Also, my policy is to not use encapsulation. (You've expressed you agree with me on this above.)

Plugins live in the same memory space as Rack, so it's impossible to sandbox plugins completely. I instead believe in documentation to state which methods can be used by plugins.

**Comment by DomiKamu** [comment]
Of course, I understand! for doc, I can understand you're too busy for VCV Rack 0.6, so they're priorities.

My new "KlokSpid" now use standard context-menu, plus addon menu to select GUI variation.
