### ISSUE TITLE
Dangling Cables

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#738]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): .5.1
This is particularly a problem if cables are stacked on a jack. Often, I will unplug a cable from its destination jack with the intention of moving it to another jack, release the mouse button and then, of course, the cable disappears. Problem is I often cannot remember which jack was the source.

Would it be possible to optionally leave a bit of cable dangling from its source when disconnecting it? Maybe holding a modifier key down as you unplugged from the destination would cause a short segment of the cable to remain at the source and maybe "pulse" to 100% opacity for a half second or so to get your attention.

**Comment by Strum** [comment]
@jonheal 

I still use multiples to avoid this problem rather than stack more than 2 or 3 cables on a socket.

The longer the cable the harder it is to trace back through the patch so I also try to keep stacked cables short so the way they are connected is easy to work out and use multiples for longer cables.

**Comment by jph-wacheski** [comment]
mults do help currently, however the dangling cable seems like an interface improvement that mirrors real world modular work flow.  We already have Right-Click to delete a cable, so left click and release should leave the cable dangle,. (perhaps a random noise flux to sim real world cables floating would be good in this state on inputs?)

jonheal - instead of opacity pules the cable could swing pendulum style,. infinitly.

**Comment by jonheal** [comment]
No comment from Andrew, so maybe he either:
- thinks it's a good idea and he is thinking about how it might be implemented, or;
- thinks it's the dumbest idea ever. :-)

**Comment by AndrewBelt** [comment]
Yeah, I don't like it. The benefit to the user is smaller than the time to implement.

**Comment by Strum** [comment]
Maybe feature requests are better made shortly after a new release rather than right before one.

This idea might be something worth looking at adding at some point in the future but there are higher priorities right now and Andrew seems to be very busy.

I do agree that it would mirror real world modular, and that was part of the original design idea wasn't it @AndrewBelt? , but it's not necessary and there's probably a long list of more important things that do need doing first.

**Comment by AndrewBelt** [comment]
It's not a matter of priorities. I just don't like this feature. I'm all for improving the efficiency of patching, but this isn't how I'd do it.
