### ISSUE TITLE
why do people say that GPU can be a big factor? 

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#746]
We’ve been measuring the CPU usage of our plugin (booty shitfter), and measuring the overall time spent in Rack’s engine thread. Trying to understand the persistent complaints from Rack users about dropouts and such. Want to make sure our plugins don’t contribute to these kinds of problems.

Do have one question – why do people say that GPU can be a big factor? On a typical 4 core system doesn’t the engine thread pretty much get full use of one core? Why would GUI rendering cause audio problems (admittedly the UI would could become unresponsive/slow)?

**Comment by Chaircrusher** [comment]
At a certain point, if the GUI thread can't keep up, I bet the audio thread ends up blocking because of the interlocks between the two threads.  I've said in the past that the default frame rate for audio is quite high the way it's coded. Choking it down to 30 refreshes per second would cut the rendering load quite a bit.

**Comment by squinkylabs** [comment]
@Chaircrusher : That would certainly explain it, but looking at the code it looks to me like the audio thread only waits on mutexes defined in the engine.cpp. There are only locked when re-patching. There is some fancy synchronization between the AudioInterface thread and the engine thread, but I don't see anything with the UI/drawing.

I've been meaning to try writing a plugin that will sleep for long times in the UI and see if that causes loss of audio. And to see if the audio thread will interrupt the UI.

**Comment by Chaircrusher** [comment]
I was totally guessing. I haven't really looked that closely at how it works because I don't want to be involved in coding, since I already code all day at work ;-) 

Is there no mutex lock between the Engine and the GUI? I guess it doesn't matter so much for things like knob moves, because if you change a variable from the GUI thread, the audio engine thread will notice the change within a few samples.  But it seems like there would be things that would require synchronization, having to do with patching, adding/deleting modules etc...

I think that if the GUI thread does cause dropouts, it may be because it's spending too much time in the video driver, which increases interrupt latency. Also there's one pool of cores that's shared across all app threads and all system threads, and there are inevitable bottlenecks when too much is happening all at once.  None of that is anything you can code an application to fix; in that case, you're up against how well the OS functions as a real time OS.

And (Windows/Linux/OSX) are none of them hard real-time OS.  They all have their own bad behavior when you push them too hard, but the real cause of dropouts at its root is what happens in the interrupt service for the audio driver:

The audio driver is set up so it gets a timer interrupt tailored to the current audio buffer size.  It then sets up the transfer of a buffers worth of samples to the actual device.  It gets the buffer's worth of audio from a ring buffer, and if the ring buffer hasn't been filled by audio apps, you get dropouts.  That's the supply side underrun. The demand-side underrun happens if general CPU contention means the audio driver doesn't get an interrupt before the last-transferred buffer has been consumed, so the circular buffer overflows and packets of samples get discarded.

I guess that would be mansplaining if there were women in this discussion (are there?) so maybe chalk it up to nerdsplaining.

**Comment by squinkylabs** [comment]
Hah - as it happens I have worked on real-time and near real-time audio a long long time. Yes, what you describe is true. In my experience, a typical "DAW" has an audio thread (or, more often, pool of audio threads). Audio threads usually run at the very highest possible priority, do not ever try to grab a mutex or semaphore or whatever, and never call OS functions that might block. While its true that none of the common OS are "real-time", they are as they say close enough for rock and roll.

From reading in the users group, it seem that dropouts and low module counts are by far the most common complaint about this otherwise wonderful and amazing software. People report that even with systems that can support very large sessions in Ableton they are unable to make large patches in VCV Rack. Squinky Labs has great optimism that after 0.6 is released VCV will tackle this issue.

**Comment by AndrewBelt** [comment]
I'll dedicate a block of two weeks to fix performance issues, but I'm not worrying about it until shortly before 1.0 in 6-9 months.

**Comment by Chaircrusher** [comment]
@squinkylabs -- I'm guessing the real problem with people running into performance problems -- and I notice that they usually don't list what CPU/GPU they're using -- is that their machine is underpowered.

As a case in point, I kept running into performance problems, & then I noticed that my heatsink wasn't tightened down flush to the CPU, and probably hadn't been for years. And yet, with a 2012 Core I5 running at 1GHZ due to thermal throttling, I was doing substantial rack patches.  I'm betting people complaining have older computers with built-in video, or they haven't done the most elementary performance tuning for audio.

@AndrewBelt Since I've really not run into performance issues, I'm not going to be the one pushing you to do CPU optimization.  I did some profiling a while back and suggested low-hanging fruit.  I suspect the biggest bottleneck -- resampling -- is not going to be an easy fix, since you're using the 'industry standard' resampler which has been tuned pretty well. I suspect that until the plugin developers do some serious profiling, the modules may be the weakest link performance-wise.

**Comment by squinkylabs** [comment]
The point of the post was to ask if you could confirm or contradict what users say - that one will experience dropouts unless their GPU is sufficient. Then there was a follow up question - if is is true, could you explain what about that software architecture causes that to be the case. As stated at the top of the thread, as plugin developers we want to know what the rules are for cooperating with the plugin host.

**Comment by AndrewBelt** [comment]
In that case, no, there's no relation between the performance of the two threads. If only the main thread has a load greater than 1, the engine thread will not be affected. Therefore, if the engine or Audio Interface thread is having dropouts, it is only the fault of those two threads.

**Comment by squinkylabs** [comment]
excellent, tx. closing.
