### ISSUE TITLE
Include the Rack API in the official Rack distributions

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#754]
It's a hassle to build Rack on all three platforms for plugin developers, so why not distribute the headers in the official distribution, so the "Building" section in this README is unneeded for plugin development.

A few unanswered questions:
- How do plugin developers get the files? Through the official installer, or through a separate ZIP SDK?
  - Actually not much is shared: `compile.mk`, `plugin.mk`, `include` would be needed but don't need to be in the official dist.
- `RACK_DIR` might solve this problem.
  - On Linux, set `RACK_DIR` to wherever you unzipped the archive. Simple.
  - On Windows, use `/c/Program Files/VCV/Rack`. Spaces mess up Makefiles.
  - On Mac, use '/Applications/Rack.app/Contents` or something.

**Comment by AndrewBelt** [comment]
Easier than I thought. Added Rack-SDK-*.zip to the `dist target in df297d329183eb58e081dc115611920fa6812b74
Haven't tested on Windows. Will likely need the libRack.a file.

**Comment by leopard86** [comment]
Hello Andrew,
if I get it right, we don't need to have Rack compiled on each platform because the makefile copies include/ and dep/include/ headers to the plugin folder so we can compile against it even if we did not build Rack. The linker will not complain because it will find precompiled libraries in Rack-SDK-*.zip, is that right?

**Comment by AndrewBelt** [comment]
No libraries needed (except you need libRack.a on Windows because DLLs are different). Just the build framework (Makefiles) and headers.

**Comment by JerrySievert** [comment]
linux/windows use gcc/g++, macOS uses clang/clang++ - most of the developers seem to either have VM's set up, or have friends do their cross-compiles for them (I do some linux/Mac compilations for a friend myself).

I'm wondering if maybe a couple of docker images doing cross-compilation might be the way to go for building (once the headers and .a/.dylib/.dll stuff is built for each platform).  it could easily include a test harness to make sure functionality is a-ok, and if all else fails provide a CaaS (compilation as a service) kind of deal.  besides, having docker images with the cross compilation would make it easy for anyone to do development.

as an aside, I had been putting the finishing touches on a testing suite for my modules when you announced the rearrangement of modules for 0.6 (the test suite is written, I had just started separating out my  gfx code from the logic for testing) - I'd  be happy to contribute what I have.

thoughts?

**Comment by AndrewBelt** [comment]
I don't like automated testing because they solve maybe 0.1% of potential problems and are used as an excuse to avoid manual testing, which solves 90% of problems.
An exception is potentially unstable DSP code. Make sure you test that.

Docker is good for builds but since you need to test on all three OS's, I don't see how they're helpful. The Build Team in the VCV Community will handle that for you the proper way, so I don't see the point.

**Comment by JerrySievert** [comment]
I'm sorry you feel that way.  when porting my own vcvrack modules from macOS to linux/windows, I was very happy to have tests that helped me find issues that were popping up due to compiler differences, as it saved me a lot of time to track down any issues.  alternately, when helping friends port theirs to macOS/linux, memory/stack issues were showing up from executable ordering differences that were not occurring under windows - some simple tests would have helped find these, but instead I spent a couple of hours in lldb tracking down the problems.

I, personally, find tests to be very helpful.

**Comment by AndrewBelt** [comment]
>memory/stack issues were showing up from executable ordering differences

Sounds like you're relying a lot of undefined behavior.

**Comment by leopard86** [comment]
Jerry, just out of curiosity, I'm wondering what kind of automated tests you perform. I used to work on this for a big company years ago and the thing was particularly useful to track down regressions on a large software that would stand for years. For modules of <1000 lines of code I see it less valuable but I'm curious to learn, there's surely some use case I'm not thinking about...

**Comment by JerrySievert** [comment]
> Sounds like you're relying a lot of undefined behavior. I suppose it would help in this case.

@AndrewBelt no, in his case, there was a buffer overrun occurring that was not evident in windows because of the differences between ELF and COFF/PE segmentation of stack and memory.  in my case, it was differences between initializations and memory sanitization between the clang and gcc environments (both doing it a little differently - gcc doing it a little bit more "sloppily", if you want me to go into detail, I'm happy to).

@leopard86 beyond being an open source developer and maintainer myself, I've worked in small (<10 engineer) organizations, as well as those with several thousand engineers, legacy code bases, and green-field.  in all of them, we've relied on tests for the following:

* prove algorithmic correctness (we were doing a lot of math, that had to be 100% correct)
* allow for refactoring in order to make code more efficient while showing that we were still correct
* allow for multi-platform development, since compilers and executable formats vary significantly
* show that interfaces are orthogonal
* eliminate "black boxes"

all of these work very well for modules < 1000 lines of code, and for me, the first 3 have translated very well for module development for vcvrack.
