### ISSUE TITLE
ASIO4ALL Issues 0.5.1

### ISSUE THREAD

**Issue by lfrym** [VCVRack/Rack#793]
Operating system(s): Windows 10 64-bit
Version if official Rack release, commit hash and/or branch if from source: 0.5.1

Rack crashes when attempting to change anything on screen while Audio Device in Core Audio Interface is set to ASIO4ALL. Reopening Rack without deleting the settings file in Documents results in an immediate crash.

It is possible this is being caused by my audio interface (Alesis iO4). The only lead I have is that upon changing the audio device to ASIO4ALL, sample rate is set to 33000 Hz without any dropdown options to change it. The audio interface I use does not support that sample rate, so this might be causing a crash in ASIO4ALL leading to a crash in Rack.

[log.txt](https://github.com/VCVRack/Rack/files/1800185/log.txt)

**Comment by Coirt** [comment]
If you delete the autosave file located in the rack directory rack will use the default empty rack next time you open.

**Comment by prophecynine** [comment]
I have a similar issue. It's not as simple as that though. I am not able to use the ASIO output at all because as soon as I hit the dropdown menu to choose the ASIO driver, ASIO4ALL is loaded and crashes.
If I could, I would be choosing a different option and avoid the crash, but I don't get a chance.

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
