### ISSUE TITLE
Endgame for 0.6 module developers

### ISSUE THREAD

**Issue by jhoar** [VCVRack/Rack#801]
Hi,

It's now... 1d6+5 days before 0.6 goes live. Could you give us an idea of what you'd like us module developers to do and when? I think we'd all be keen to have our modules available as quickly as possible (if not simultaneously).

Also, what version numbering scheme is preferred? I was planning on 0.6.9 for AH (0.6 corresponding to the Rack version, and the 9 corresponding the 9th release of the modules). I guess that so long as the major.minor convention is respected, you are not bothered either way

thanks.

**Comment by AndrewBelt** [comment]
Rack `master` branch is API-compatible with the upcoming Rack 0.6 but not yet ABI-compatible, so the goal in the next week or so is to get all the plugins up to date so that they will build when Rack 0.6 releases. I'll handle building and hosting everything for the first couple weeks as long as everything is in the `v2` branch of the community repo.

For versioning, I prefer to reset the revision number when a new Rack version releases, but you can do whatever you want.

**Comment by jhoar** [comment]
OK, great. What's currently in the community repo is a bit out of date with what I would hope to release with so I expect that there'll be a final clone before release against the v0.6 branch. In any case I'll guess we'll hear more in the near future.

**Comment by AndrewBelt** [comment]
See https://github.com/VCVRack/community#for-plugin-developers-addingupdating-your-plugin for updating your plugin in the community repository.
