### ISSUE TITLE
Request to change module controls to be viewport dependent

### ISSUE THREAD

**Issue by cunabula27** [VCVRack/Rack#825]
I assume this behaviour is the same across all operating systems.

As currently implemented the resolution of controls within a module is locked to the display resolution of the computer while moving around the screen is sensibly mapped to the viewport resolution within Rack. If possible it would be better if the controls within the module had the same behaviour.

If you change the zoom in Rack to 50% you can move around the layout and patch cables twice as fast, however the controls within a module require the same amount of mouse movement regardless of the displayed size of the module.

I expect this behaviour is only super noticeable at higher screen resolutions but the mismatch between the two behaviours becomes really obvious and it doesn't make a whole heap of sense.

Currently with Rack's viewport at 100% mouse travel for the mixer slider is 5cm with my setup (which is too high anyway but this change would make it easy for the user to adjust themselves - they'd just zoom out a bit). It remains 5cm with the viewport set to 25% (when everything on the screen is tiny). It feels like pushing the controller through treacle, makes quick changes very difficult to accomplish and the visual feedback is very mismatched with the mouse pointer usually whipping round the patch and then super slow when changing a parameter.

If I halve the resolution of my screen I can double the responsiveness of the modules, so there's a workaround, that I'm happy to use, it's just suboptimal.

Also if the module behaviour was changed in this way it would give users another way to produce fine changes other than just using CTRL/CMD click and drag.

**Comment by AndrewBelt** [comment]
So you basically want mouse sensitivity to scale with zoom level?

**Comment by cunabula27** [comment]
Yes, if a controller is displayed half the size I'd like to have to move the mouse half as far.

Bit like in Photoshop or similar when drawing, if you zoom in you have finer control over the brush.

**Comment by cunabula27** [comment]
Would also mean that if you have to use someone else's computer for whatever reason as long as you have everything at the same size on their screen as yours your muscle memory will be fine. 

As currently implemented someone on a 1080p screen won't be able to use Rack on my screen as effectively as they'll have to move the mouse twice as far for the same visual result.

**Comment by cunabula27** [comment]
Rough mock up (I hope for clarity) - that there's a difference between mouse travel between moving a control and moving around a patch is fine, it's that it doesn't scale on zoom that is a bother:

![image3355](https://user-images.githubusercontent.com/24782488/37650085-d11d020a-2c2b-11e8-9ab3-83ff6b676a2c.png)

**Comment by AndrewBelt** [comment]
I understand what you mean. This whole issue could have been condensed into that one sentence.

I tried it, didn't *exactly* like it. With a linear relationship, the effect is too harsh. It might make sense to scale the effect by `sensitivity ~ zoom**0.5` or `zoom**0.25` just to give a small effect, but this seems weird. If I wanted to try to explain why it shouldn't be scaled, I believe that when moving a knob, your mind wants to change the angle, which is *not* scaled. When moving faders, your mind abstracts away the current zoom level and wants to use the sensitivity to change the *value* of the fader, not the position. If the faders jumped to the clicked position, it would of course be effectively scaled to the zoom level, but since they are not (to allow more control over the value), they should have the same sensitivity so you can close your eyes and feel the change with your ears without the zoom level affecting the sensitivity which you have learned.
