### ISSUE TITLE
More wire colors?

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [VCVRack/Rack#829]
```C++
    nvgRGB(142,12,133), // purple
    nvgRGB(201,90,14), // orange
```
These don't look bad with the others

**Comment by AndrewBelt** [comment]
@milholen

**Comment by AndrewBelt** [comment]
The current colors are essentially the look and feel of Rack. You can change them on your end, as a benefit of being able to compile the source.

As an unplanned side effect of colors being saved in patches in Rack 0.6, your custom colors will also be saved, and people who open your patches will be alarmed by your custom colors. I guess that's a good thing since it encourages people to compile from source, which increases the number of bleeding edge testers of Rack (which will be slowly dropping as the software stabalizes.)

**Comment by WIZARDISHUNGRY** [comment]
At some far off point, it'd be cool to be able to use that sweet osdialog color picker & have user defined schemes 😄. I tried using [solarized](http://ethanschoonover.com/solarized) but the pink, red and orange were too close together:

```C++
    nvgRGB(0xb5, 0x89, 0x00),  // yellow
    nvgRGB(0xcb, 0x4b, 0x16),  // orange
    nvgRGB(0xdc, 0x32, 0x2f),  // red COMMENT ME OUT
    nvgRGB(0xd3, 0x36, 0x82),  // magenta
    nvgRGB(0x6c, 0x71, 0xc4),  // violet
    nvgRGB(0x26, 0x8b, 0xd2),  // blue
    nvgRGB(0x2a, 0xa1, 0x98),  // cyan
    nvgRGB(0x85, 0x99, 0x00),  // green
```

(in case anyone is interested)

**Comment by retoid** [comment]
Option to select wire colors to be used? I am constantly re-wiring every black cable to be another color cause it's the color to get lost in the mix the quickest and it difficult for me to trace.

**Comment by WIZARDISHUNGRY** [comment]
@retoid you're in luck, black wires are gone in 0.6.x
