### ISSUE TITLE
PDF manual (per module in rack), F1 key (mouse cursor over module)?

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/Rack#832]
Hi,

I'll hope my question is explicit. Per module, from my collection, I'd like to open the relevant user guide (PDF) simply by pressing "F1" key when the mouse cursor is over concerned module. Of course if "F1" isn't reserved for another Rack feature, also if allowed (following guidelines), for both Rack 0.5.1 and future 0.6.

Thanks in advance. (it's not urgent, don't worry) ;)

Regards.
Dom.

**Comment by WIZARDISHUNGRY** [comment]
Why not just go to the manual link?

**Comment by cunabula27** [comment]
Its not in the new Menu system is it? Or have I just built a bunch of modules that don't have one?

**Comment by AndrewBelt** [comment]
If I added this feature, the typical experience would be:
- add module
- hover over module, press F1
- nothing happens because the developer didn't write a manual
- user loses trust in the feature and never uses it

The manual would open in the browser anyway, so it's better to start from the browser anyway, using https://vcvrack.com/plugins.html

**Comment by DomiKamu** [comment]
@WIZARDISHUNGRY Because each module (KlokSpid, RKD) having its own manual.
@AndrewBelt too bad. Perhaps a context-menu entry to access module-specific PDF. I understand/agree F1 key isn't a good idea, though.

Thanks!
