### ISSUE TITLE
Allow using existing dependencies.

### ISSUE THREAD

**Issue by MaurizioB** [VCVRack/Rack#84]
I'm not a programmer, nor an expert, but, as far as I can see, VCVRack uses static linking towards locally compiled libraries. Except for libzip, I already have the other dependencies installed and up to date.
It would be nice to allow the use of existing system libraries through dynamic linking.

**Comment by farvardin** [comment]
yeah, the same for me, I can't use it because of this. After fiddling with some symbolic link and installing external packages, all I get on my linux mint 17.3 or 18 is: 

./Rack.sh GLFW error 65539: Invalid window hint
./Rack: symbol lookup error: ./Rack: undefined symbol: glfwSetWindowSizeLimits

(I've compiled the git version from sources)

**Comment by AndrewBelt** [comment]
^ This is an example of why I'm not supporting existing dependencies. Many of the technologies used in VCV Rack are fairly new, so the APIs of the libraries change a lot. The only 100% solution is to build everything from fixed source versions and adjust LD_LIBRARY_PATH accordingly.
