### ISSUE TITLE
I am in heaven. No issue.

### ISSUE THREAD

**Issue by alto777** [VCVRack/Rack#840]
I am very happy to discover VCV Rack and I got the energy to build it and start making plugins. This mostly by pattern recognition and faking it - I encourage all daunted by the complexity of the undertaking and the brevity of the instructions to try their best - the instructions work!

So I am learning about git and repositories and amazing make, and even C++, all fun.

I have made a plugin by shamelessly hammering on SEQ3 from Fundamentals and I am wondering about the IP implications - I only plan to freely offer my creations, although I must say they will never achieve the quality of the plugins I have looked at, internally or externally. **Nice work people!** I will try to put it up for you all to see, as it does some things that I haven't found yet (but have probably been done or are do-abble by modules I haven't looked into yet).

I did see the FAQ on development (somewhere) and the major tip is to always have something that works as you move it along toward your goal. So when it breaks you can focus on what's new. Standard stuff I guess. It certainly helped me.

The most confusing part, no doubt a result of the rapid progress being made here, is the difference between versions. The Rack I first downloaded and use just for synthesis can't/doesn't tell me the version. I also got jumbled up when I found that one Template was quite different from another - I must have downloaded the two differently, but can't recall how, or it changed under my feet in the last week or so?

One feature I think is a must (!) -after zooming away from 100% it is impossible to get it back, although looking into it did lead me to the json file where I could edit the setting!

Lastly I like this comment I came across regarding Screws:

"If you don't add these to your ModuleWidget, they will fall out of the rack..."

LOL!

alto777

**Comment by phdsg** [comment]
you can reset the zoom level (and all other controls as well) by right-clicking.

**Comment by MarcBoule** [comment]
"I have made a plugin by shamelessly hammering on SEQ3 from Fundamentals and I am wondering about the IP implications"

The best for this is to take at look at LICENSE.txt in the Fundamental folder, which mentions:
```
Source code licensed under BSD-3-Clause by Andrew Belt

VCV logo is © 2017. Derivative works may not use the VCV logo.

Panel graphics in res/ are © 2017 by Grayscale. You may not create derivative works of Fundamental panels.
```
https://github.com/VCVRack/Fundamental

The graphics in Rack's Component Library can be used in non-commercial plugins.
Nice issue title by the way! :-) 👍

**Comment by MarcBoule** [comment]
Regarding your IP question, I asked something on FB a few weeks ago, and the answer from Andrew may also help give you some guidelines, so I'm putting an extract here:

MB:  _I would like to ask Wes Milholen or anyone else that knows, what font is used in the Fundamental panels? I'm designing a sequencer based on SEQ3, and I would like to keep the feel of things, and plus, all the fonts I am trying don't look as good as that one :-) it's really a killer font as far as I'm concerned!_

AB: P_anel designs are something that shouldn't be copied, since the Fundamental and VCV panel designs are Grayscale's brand._

MB: _All good AB, I will definitely comply with any guidelines like that, and will try to make my own graphic feel. Just so that I understand things properly, is it acceptable to use the Component library in Rack?_

AB: _For noncommercial use, see_ 
https://github.com/VCVRack/Rack#license
_and_ 
https://github.com/VCVRack/Fundamental#license

Hope that helps!

**Comment by AndrewBelt** [comment]
Yes, see the License section of the README for Rack and Fundamental.

**Comment by alto777** [comment]
Thank you. git wrangling turns out to be more of a challenge for me than building and hacking a plugin. I'll try to give it the time it deserves. It's hard not to just keep playing w/ Rack and my little plugin effort.

And right-click, nice. I spent too much time with a one-button mouse and it is not something I ever think to try, in factI have to keep relearning how to even do it. Sad.
