### ISSUE TITLE
error while loading shared libraries: libglfw.so.3

### ISSUE THREAD

**Issue by cinemascop89** [VCVRack/Rack#88]
I was able to compile the repo with its dependencies, but when I run ./Rack.sh, I get

`./Rack: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory`

I'm currently running Arch Linux, I tried running the binaries downloaded from the web site (version 0.3.1) and it ran without issues.

**Comment by cinemascop89** [comment]
I could make it work by installing the `glfw-x11` package, I also needed to install `libzip` and `portmidi`

Maybe a list of dependencies could be added to the wiki or README?

**Comment by MaurizioB** [comment]
According to #85, on Linux you will need to use ```make run``` to run it properly, since it uses locally built static dependencies.
The ```Rack.sh``` is not intended for general use but for distributable versions only, since the syntax is wrong. Alternatively you could also use this command:

    LD_LIBRARY_PATH=".:./dep/lib/:$LD_LIBRARY_PATH" ./Rack

As a note to @AndrewBelt, this should be added to the README.

**Comment by AndrewBelt** [comment]
Added to README
