### ISSUE TITLE
Developers – please don't rename your modules when updating for 0.6.0

### ISSUE THREAD

**Issue by vogelscheiss** [VCVRack/Rack#904]
This issue has broken patches that use modules from:

- Gratrix
- Lindenberg Research
- Autodafe
-  Vult

and probably others.

The only fix for users is to figure out the new slugs and edit their .vcv files, which is pretty tedious and really shouldn't be necessary. If you've made a lot of patches using modules that have been renamed, that can mean a lot of editing.

So could you please try to be mindful of naming conventions? Thanks much.

**Comment by AndrewBelt** [comment]
Yes, see under Naming https://vcvrack.com/manual/PluginDevelopmentTutorial.html

**Comment by modlfo** [comment]
I believe that over the time the developers have become aware of the problems in renaming modules. On my side, I haven't renamed any modules. I even created a mirror of the Free and paid modules to avoid breaking people's patches.

Closing this issue since the information is part of the Development tutorial.
