### ISSUE TITLE
0.6.0 / Fundamental / Mixer module / suggestion

### ISSUE THREAD

**Issue by vogelscheiss** [VCVRack/Rack#910]
Under 0.6.0 the Fundamental Mixer module has been changed to quadratic scaling. Perhaps there's a rationale I don't understand.

As you know, pots come in two basic flavors - linear and logarithmic (exponential). Due to their different behaviors In a modular synth you use 

- linear for CVs and 
- logarithmic for audio.

The Fundamental VCA for instance has a lin and an exp CV input.

Quadratic doesn't come into it. Could I suggest instead of quadratic scaling on the mixer, instead a lin/log toggle switch on the mixer to suit the module to either purpose?

Just a suggestion. Thanks.

**Comment by AndrewBelt** [comment]
Quadratic is more subtle than logarithmic (try changing it and you'll see what I mean) while linear has too little effect near the top with a drastic drop of volume near the bottom.
Won't change this.

**Comment by AndrewBelt** [comment]
Thinking back on this, here's a more rigorous explanation that I prefer polynomial/roots over logarithmic/exponential parameters. Suppose you need a parameter ranging from -N*10 dB to 0dB. Take the inverse, expand the series, take the Nth monomial, and take the inverse again to get the approximation x^{1/N}. There is little difference as you can see:

![2018-06-28-095926_1599x799_scrot](https://user-images.githubusercontent.com/338179/42038922-207cfcf6-7aba-11e8-8753-dad98810ec21.png)

With the root formula, you get the added benefit that the parameter tapers to -inf dB at its 0 position, which is desired because users typically want to mute a signal when a knob is hard-left, not attenuate at -40dB.

Also, integer powers and roots are way faster than `log10()` or `powf(10.f, x)`. See https://godbolt.org/g/v28jAP
