### ISSUE TITLE
help switching noise

### ISSUE THREAD

**Issue by alto777** [VCVRack/Rack#928]
I am switching some audio signals on and off and I get pops or clicks at each end.

Is this is because I switch at an arbitrary point in the waveform? I tried a soft kill fade-in-out switch (AS Kill Gate) which eliminates the clicks but lets in some of the post switching time waveform. I am switching between two frequencies on the same signal (long story, has to be so).

Would delaying the switch until a zero-crossing was seen work? You are correct, I could get 1/2 a period of the new frequency, but I wonder if I would get rid of the click?

I think I could test this in a few hours, which by recent records means a few days, so any dis/encouragement would help. Or if there is already a kill gate that does this I could try.

Another solution (hours, I mean days away) would be to bring the audio frequencies I use within my module and deal with it there.

TIA

**Comment by AndrewBelt** [comment]
Yeah, a bandlimited step function has lots of high frequency content, so you want to avoid making those.

>Would delaying the switch until a zero-crossing was seen work?

Not really, because the derivative of the signals will be different, and the bandlimited derivative of a step function is a minimum phase sinc function, which also has lots of high frequency content.

A general solution for anti-pop muting is to use some function f(t) with little high-frequency content and generate y(t) = f(t)*x(t). Usually a "slewed step function" is enough.

Anti-pop crossfading is easy by just considering two summed channels of anti-pop mutes.

**Comment by alto777** [comment]
Thank you that helps. Overnight an idea came, as they do, that will allow some easy experiments. Then I may or not run the whole thing to ground - just tinkering with Rack trying to chop up.
