### ISSUE TITLE
JNI Support?

### ISSUE THREAD

**Issue by MazeOfEncryption** [VCVRack/Rack#933]
I personally don't like C++ that much, and think that java would be a lot easier of a platform to develop modules for vcv on. Any way that JNI support will be added at any point?

**Comment by AndrewBelt** [comment]
No, you're welcome to write a wrapper.

**Comment by MazeOfEncryption** [comment]
If I were to write my own wrapper, any way it could ever become official?

**Comment by AndrewBelt** [comment]
No, the number of people that would use it would be less than 5, so it would quickly become out of date and unmaintained. It would also be nearly impossible to write because you would need to wrap hundreds of C++ classes, all dependencies (nanovg, GLFW, etc), and probably thousands of functions. It would be 100x easier to write a plugin in C++ than to write a Java wrapper.

**Comment by MazeOfEncryption** [comment]
Ah, okay.

**Comment by modlfo** [comment]
Closing since it will not be implemented as part of Rack.
