### ISSUE TITLE
How to force widgets redraw from a module ?

### ISSUE THREAD

**Issue by mak5555** [VCVRack/Rack#942]
Hello, I'm making my first module.
I want to recall some preset parameters (knob positions) with the popup contextual menu.
I've tried
  params[MY_PARAM].value = 1.0;
or
  engineSetParam(this, MY_PARAM, 1.0);
They work both but the widgets are not refreshed. 
I tried also to modify wires within my module with engineAddWire() and it affect the sound succesfully, 
but same problem, no wire appears.

I have studied the sources and various modules with no result.
Is it possible to force the engine to redraw the ui ?

Thanks.

**Comment by david-c14** [comment]
I'm not an expert, but this is what I've been doing:

You shouldn't directly try to control widgets from your module, because the widgets may not have been created by the time your module step is called. The module and the widget steps happen in different threads; and in theory your module can run without ever having any widgets (no UI at all).

Instead, it's probably better to do it the other  way around.  You can subclass the widget and override the step method on the widget.  It can lookup a value from your module more safely than the other way around.   

Set the parameter as you are doing, but then widget can check with the module to see if it needs to be updated and then it probably has a setValue method of it's own.

**Comment by AndrewBelt** [comment]
The `ModuleWidget` is the master/owner of the slave `Module`, and information passes unidirectionally from the Module to the ModuleWidget, with the exception of Lights and other custom widgets that read data from Module.

And yes, in the future, the Module will run without a ModuleWidget for "headless" mode.

**Comment by squinkylabs** [comment]
So it is guaranteed that the Module lifetime is such that the module always stays alive at least as long as the widget?

**Comment by AndrewBelt** [comment]
It is not even guaranteed that a ModuleWidget or Module exists. Each must handle being independent in Rack 1.

**Comment by squinkylabs** [comment]
It's pretty common for me to hold onto a module pointer in my widget to help draw the UI. Is there a supported way to get the parameters array, other than holding onto a module pointer?

**Comment by AndrewBelt** [comment]
Yup, that will need to be changed for Rack v2. You can simply add `if (module)` checks in your `ModuleWidget` constructor, since it could be NULL. For example, the Module Browser could pass a null Module if it just wants a preview of the panel.

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
