### ISSUE TITLE
OSX High Sierra clean install: OpenSSL libs not found

### ISSUE THREAD

**Issue by airwindows** [VCVRack/Rack#971]
Got completely new clean install of MacOS High Sierra, did this successfully on the new system:
brew install git wget cmake autoconf automake libtool

getting most of the way through 'make dep', but I hit this:

==> Pouring openssl-1.0.2o_1.high_sierra.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

…and make dep produced this:

configure: error: OpenSSL libs and/or directories were not found where specified!
make[1]: *** [lib/libcurl.a] Error 1
make: *** [dep] Error 2

I've tried ./configure LDFLAGS:  -L/usr/local/opt/openssl/lib CPPFLAGS: -I/usr/local/opt/openssl/include but I just get './configure: no such file'.

I feel like my chances are better starting from a freshly installed High Sierra with current XCode, but this is still rather over my head and I hope there's a way through: the erase/install was hell.

For now, leaving it at the failed 'make dep' on Rack proper, prepared to start over, or adjust whatever must be adjusted.

**Comment by AndrewBelt** [comment]
`make dep` doesn't call `brew install openssl`, even indirectly, so no "pouring" can take place. What exactly is happening here?

**Comment by airwindows** [comment]
Initially, the 'brew' stuff comes from your direction to "brew install git wget cmake autoconf automake libtool": I'm installing newest XCode on clean install of High Sierra, and I looked for possible explanations of why make dep failed.

Make dep failed, citing the configure: error below. The part above came out of what brew did when installing what I needed for Rack.

**Comment by shurikenyo** [comment]
I'm also stuck with this...i think some stuff is missing. After following the readme guide everything worked until the `make dep`..i got this:

mastaman:rack macbookpro$ `make dep`
/Library/Developer/CommandLineTools/usr/bin/make -C dep
wget -c "https://github.com/nigels-com/glew/releases/download/glew-2.1.0/glew-2.1.0.tgz"
/bin/sh: wget: command not found
make[1]: *** [lib/libGLEW.a] Error 127
make: *** [dep] Error 2

Just thought i mention that i had to manually install wget..maybe the flags not needed?:

`brew install wget --with-libressl`

Then make dep worked until this:

configure: error: OpenSSL libs and/or directories were not found where specified!
make[1]: *** [lib/libcurl.a] Error 1
make: *** [dep] Error 2

At this point i just tried to "make" and "make run" but i got the same:

configure: error: OpenSSL libs and/or directories were not found where specified!
make[1]: *** [lib/libcurl.a] Error 1
make: *** [dep] Error 2

so i tried to:

`brew install curl`

Some interesting text came up:

_This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/curl/lib
    CPPFLAGS: -I/usr/local/opt/curl/include_


Also found this while searching around on forums for problems...someone wrote this:
--------------------
_After some more thorough investigation, I determined that the configure file for cgminer does not pay attention to LDFLAGS or CPPFLAGS when testing for libcurl. Instead, it checks for LIBCURL_CFLAGS and LIBCURL_LIBS. So, I tried:

export LIBCURL_CFLAGS=-I/usr/local/opt/curl/include
export LIBCURL_LIBS=-L/usr/local/opt/curl/lib
./configure
and I got:

checking for LIBCURL... yes
And the rest of the configuration went off without a hitch. SUCCESS!_


[https://stackoverflow.com/questions/16246352/how-do-i-specify-ldflags-and-cppflags-for-configure?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](url)


Sorry if this is some noob misstake, i'm new to all this compiling stuff and how do i set the ./configure or where do i set the LDFLAGS and CPPFLAGS? Or maybe it's something else...hmm..is there a simple hack that just makes it work?...to manually copy the libcurl.a file somewhere, or link my system manually to the OpenSSL dir?

**Comment by shurikenyo** [comment]
Another day....Re-installing Xcode here, takes awhile on this slow internet here..i think i did something wrong with the xcode install...

**Comment by shurikenyo** [comment]
I got it workiing..Woooho!

What i did before i started building again …main thing is *blush* i think xcode was not installed correctly..i had some problem with using custom unzip program (for the xcode.xip)…make sure to use OSX default utillity app to unzip the xcode.xip…and also make sure to move the unzipped xcode.app file from the same directory the .xip file is in (downloads in my case) to the Applications folder…then i ran xcode.app form that folder and installed the additional stuff that came up..

I also installed JDK8 for osx

then this:

brew install ant

then cloned a new version and followed the instructions from the readme on the github page…this time no more errors!

but the main reason for me i think was that xcode.app was not installed correctly…OOOOPS! :D

**Comment by airwindows** [comment]
Woohoo! I didn't. I'll start over from scratch, since I'm still on a fresh High Sierra install and should not be having problems. I will follow the instructions and report what happens without mixing up the order of operations.

Installed recentest XCode: no issues. Got it directly from app store, no additional stuff came up upon running it.

ran brew install git wget cmake autoconf automake libtool: all dependencies claim to be installed and up to date.

ran git clone https://github.com/VCVRack/Rack.git: no issues. cd Rack/ : no issues (obviously)

ran git submodule update --init --recursive: no issues.

ran make dep: huge amount of compilation that seemed to be working, then failure with the following message
`configure: error: OpenSSL libs and/or directories were not found where specified!
make[1]: *** [lib/libcurl.a] Error 1
make: *** [dep] Error 2`

I'm afraid it's still not working over here. Why is that? I followed the instructions completely on a freshly clean installed OSX High Sierra, so I doubt it's anything I did or misconfigured this time. I hope this gets sorted out as the one reason I switched to High Sierra was to build Rack and begin developing modules for it, and it looked like the module building part was pleasingly approachable.

The pattern for me is generally 'get stuff working with much painful effort, then produce a lot of content once everything works'. I've got the first stage underway, please help me get to the second so that all Airwindows plugins can be loaded as native Rack modules once I've incorporated Rack as a platform I support :)

**Comment by AndrewBelt** [comment]
I probably won't be switching to High Sierra any time soon, but I'll reduce the problem scope a bit. Your only goal is to point libcurl to the libssl directory rather than your system's libssl directory. There are two ways of doing this with libcurl's configure script:
- `./configure --with-ssl=PATH-TO-DEP ...`, but for some reason this doesn't work at all. libcurl still ignores the headers of libssl installed to `PATH-TO-DEP` and uses the header files of your system's openssl at `/usr/include/openssl` or similar. This is my preferred solution, but it doesn't seem to work on any OS's. Perhaps the path sould be `PATH-TO-DEP/include/openssl` or maybe `PATH-TO-DEP/lib`, but neither works, so maybe I'm misunderstanding how this is support to work. I have never successfully built libcurl this way.
- `PKG_CONFIG_PATH="PATH-TO-DEP/lib/pkgconfig" ./configure ...` The libcurl project [recommends this method](https://curl.haxx.se/docs/install.html), but I don't like it because it relies on pkg-config simply to get the directory I could have told it in the first place, an overcomplication IMO. But this is the only method I have gotten it to build, so this is what `dep/Makefile` uses currently.

So to build Rack on High Sierra, your homework is to first build openssl and libcurl from source and report back how you did it. I'll test on the other OS's and implement your change.

**Comment by airwindows** [comment]
I've finally got back to my efforts. My Linux-using brother was over visiting, so I thought he could help me through the compile.

I proceeded to go through the build process again (from scratch, updating all deps) expecting to reproduce my bug, but this time around everything built perfectly, and I had no further issues. I've built the Fundamental plugins, and I think I'll be good to go (though I do have much work to do to port my plugin library to module form).

The solution is possibly due to https://github.com/VCVRack/Rack/commit/8dee77ef27dcbcab31a27eb9c34c7178e04b7ad8 , but regardless, it now works as it was meant to. I can't speak for shurikenyo, but as far as my build problems I consider the issue closed. Thank you :)
